/**
 * Fire Command Genesis — Character cards (inspired DNA, not emulations).
 * Each character loads a curated patch (+ optional arp) and focuses key modules.
 */

import {
  cloneFirePatch,
  makeModMatrix,
  type FirePatch,
  type ModRoute,
  type ModSource,
  type ModDest,
} from "./FireCommandSynth";
import type { FirePreset, PresetArp, PresetCategory } from "./firePresetBank";

const P = (over: Partial<FirePatch>): FirePatch => cloneFirePatch(over);
const MR = (source: ModSource, dest: ModDest, amount: number): ModRoute => ({ source, dest, amount });

export type FireCharacterPhase = "vintage" | "chip" | "fm";

export interface FireCharacter {
  id: string;
  name: string;
  tagline: string;
  color: string;
  phase: FireCharacterPhase;
  focusModules: string[];
  inspiration: string;
  /** Merged over DEFAULT_FIRE_PATCH on deploy. */
  patch: Partial<FirePatch>;
  arp?: PresetArp;
}

export const FIRE_CHARACTER_PHASES: { id: FireCharacterPhase; label: string; color: string }[] = [
  { id: "vintage", label: "Vintage Age", color: "#c9a66b" },
  { id: "chip", label: "Chip & Acid", color: "#6ee7a8" },
  { id: "fm", label: "FM & Vector", color: "#a78bfa" },
];

export const FIRE_CHARACTERS: FireCharacter[] = [
  // ═══════════════ Phase A — Vintage (v2.8) ═══════════════
  {
    id: "char-horizon-stack",
    name: "Horizon Stack",
    tagline: "Wide analog stack · slow filter bloom",
    color: "#ff8f5c",
    phase: "vintage",
    focusModules: ["mixer.unison", "filter", "fx.chorus", "fx.vintage", "analog.life"],
    inspiration: "early-80s poly stack",
    patch: {
      // Headroom pass: see char-formant-wall — 6-voice stack trimmed ~15%.
      oscATable: "saw", oscAPos: 0.88, oscALevel: 0.62,
      oscBTable: "saw", oscBPos: 0.78, oscBDetune: 10, oscBLevel: 0.47,
      oscCTable: "harmonic", oscCPos: 0.55, oscCOctave: 1, oscCLevel: 0.16, oscCDetune: -6,
      unison: 6, unisonDetune: 22, unisonWidth: 0.85, subWave: "sine", subLevel: 0.15,
      filterType: "lowpass", filterCutoff: 1800, filterResonance: 2.2,
      filterEnvAmount: 0.55, filtAttack: 0.08, filtDecay: 1.4, filtSustain: 0.35, filtRelease: 0.8,
      ampAttack: 0.06, ampDecay: 0.5, ampSustain: 0.85, ampRelease: 0.7,
      lfo1Wave: "sine", lfo1Rate: 0.18, lfo1Depth: 0.35, lfo1Dest: "filter",
      chorusRate: 0.35, chorusDepth: 0.5, chorusMix: 0.4,
      bbdChorus: 0.55, analogComp: 0.35, drift: 0.28, driftRate: 0.4,
      voiceInstability: 0.18, tuneVariance: 0.12, envVariance: 0.08,
      hiss: 0.04, reverbSize: 2.8, reverbMix: 0.18, masterGain: 0.78,
    },
  },
  {
    id: "char-soft-dual",
    name: "Soft Dual",
    tagline: "Dual osc poly · soft drift · creamy filter",
    color: "#62b6ff",
    phase: "vintage",
    focusModules: ["osc.a", "osc.b", "filter", "env.filt", "analog.life"],
    inspiration: "late-70s dual poly",
    patch: {
      oscATable: "saw", oscAPos: 0.7, oscALevel: 0.7,
      oscBTable: "pulse", oscBPos: 0.45, oscBDetune: 7, oscBLevel: 0.55, pulseDuty: 0.42,
      oscCLevel: 0, unison: 2, unisonDetune: 8, unisonWidth: 0.45, subLevel: 0.12,
      filterType: "lowpass", filterCutoff: 2200, filterResonance: 3.5,
      filterEnvAmount: 0.62, filtAttack: 0.01, filtDecay: 0.55, filtSustain: 0.25, filtRelease: 0.4,
      ampAttack: 0.02, ampDecay: 0.35, ampSustain: 0.75, ampRelease: 0.45,
      drift: 0.22, driftRate: 0.32, voiceInstability: 0.14, tuneVariance: 0.1,
      chorusMix: 0.22, analogComp: 0.28, cassetteGen: 0.12, wowFlutter: 0.08,
      reverbMix: 0.12, masterGain: 0.8,
    },
  },
  {
    id: "char-ensemble-bbd",
    name: "Ensemble BBD",
    tagline: "Square/saw + wet BBD chorus",
    color: "#7dd3c0",
    phase: "vintage",
    focusModules: ["mixer.unison", "fx.vintage", "fx.chorus", "filter"],
    inspiration: "early-80s ensemble poly",
    patch: {
      oscATable: "saw", oscAPos: 0.85, oscALevel: 0.55,
      oscBTable: "pulse", oscBPos: 0.5, oscBLevel: 0.45, pulseDuty: 0.5,
      oscCLevel: 0, unison: 1, subWave: "square", subLevel: 0.45,
      filterType: "lowpass", filterCutoff: 3200, filterResonance: 1.8,
      filterEnvAmount: 0.3, ampAttack: 0.03, ampDecay: 0.4, ampSustain: 0.8, ampRelease: 0.5,
      chorusRate: 0.55, chorusDepth: 0.45, chorusMix: 0.15,
      bbdChorus: 0.85, analogComp: 0.4, drift: 0.12,
      hiss: 0.03, hum: 0.02, reverbMix: 0.1, masterGain: 0.82,
    },
  },
  {
    id: "char-edge-pulse",
    name: "Edge Pulse",
    tagline: "Mono PWM lead · filter bite",
    color: "#ffb648",
    phase: "vintage",
    focusModules: ["chip", "filter", "pitch", "env.filt"],
    inspiration: "mono pulse lead",
    patch: {
      oscATable: "pulse", oscAPos: 0.55, oscALevel: 0.85, pulseDuty: 0.28,
      oscBTable: "saw", oscBPos: 0.4, oscBLevel: 0.25, oscBOctave: -1,
      oscCLevel: 0, unison: 1, subWave: "square", subLevel: 0.35, noiseLevel: 0,
      filterType: "lowpass", filterCutoff: 900, filterResonance: 8,
      filterEnvAmount: 0.75, filtAttack: 0.001, filtDecay: 0.28, filtSustain: 0.08, filtRelease: 0.12,
      ampAttack: 0.002, ampDecay: 0.25, ampSustain: 0.55, ampRelease: 0.1, velAmount: 0.85,
      mono: true, glide: 0.04, accentAmount: 0.35,
      lfo1Wave: "triangle", lfo1Rate: 4.5, lfo1Depth: 0.25, lfo1Dest: "off",
      modMatrix: makeModMatrix([MR("lfo1", "wtA", 0.4)]),
      drive: 0.18, driveMode: "soft", chorusMix: 0, reverbMix: 0.06, masterGain: 0.85,
    },
  },
  {
    id: "char-twin-layer",
    name: "Twin Layer",
    tagline: "Dual-layer detune · gentle tape",
    color: "#e8b84a",
    phase: "vintage",
    focusModules: ["osc.a", "osc.b", "filter", "fx.vintage"],
    inspiration: "dual-layer analog",
    patch: {
      oscATable: "saw", oscAPos: 0.6, oscALevel: 0.65,
      oscBTable: "saw", oscBPos: 0.55, oscBDetune: 14, oscBLevel: 0.6, oscBOctave: 0,
      oscCTable: "harmonic", oscCPos: 0.4, oscCOctave: 1, oscCLevel: 0.22, oscCDetune: -5,
      unison: 3, unisonDetune: 12, unisonWidth: 0.7, subLevel: 0.15,
      filterType: "lowpass", filterCutoff: 2800, filterResonance: 2,
      ampAttack: 0.15, ampDecay: 0.6, ampSustain: 0.9, ampRelease: 0.9,
      cassetteGen: 0.35, tapeSpeed: -0.08, wowFlutter: 0.22, vhsColor: 0.2,
      analogComp: 0.3, dust: 0.08, hiss: 0.06, printThrough: 0.1,
      drift: 0.15, voiceInstability: 0.1, chorusMix: 0.28, reverbSize: 3.2, reverbMix: 0.28,
      masterGain: 0.76,
    },
  },
  {
    id: "char-noise-bay",
    name: "Noise Bay",
    tagline: "Noise · FM · ring · filter drive",
    color: "#ff6a3d",
    phase: "vintage",
    focusModules: ["mixer.unison", "fm", "filter", "fx.drive"],
    inspiration: "modular noise bay",
    patch: {
      oscATable: "saw", oscAPos: 0.5, oscALevel: 0.7,
      oscBTable: "sync", oscBPos: 0.45, oscBLevel: 0.45, oscBDetune: 5,
      oscCLevel: 0, unison: 1, subWave: "sawtooth", subLevel: 0.25,
      noiseLevel: 0.28, noiseColor: -0.35,
      fmAmount: 0.28, fmRatio: 1.5, fmBtoA: 0.2, ringAmount: 0.22, ringFreq: 110,
      filterType: "lowpass", filterCutoff: 1400, filterResonance: 6, filterDrive: 0.45,
      filterEnvAmount: 0.55, filtDecay: 0.35,
      ampAttack: 0.005, ampDecay: 0.3, ampSustain: 0.7, ampRelease: 0.25,
      drive: 0.3, driveMode: "tube", punch: 0.25,
      cassetteGen: 0.15, hiss: 0.05, hum: 0.04, dust: 0.06,
      mono: false, masterGain: 0.8,
    },
  },

  // ═══════════════ Phase B — Chip (v2.9) ═══════════════
  {
    id: "char-pocket-chip",
    name: "Pocket Chip",
    tagline: "4-voice square · soft grit",
    color: "#9be564",
    phase: "chip",
    focusModules: ["chip", "osc.a", "filter", "fx.drive"],
    inspiration: "handheld pulse chip",
    patch: {
      oscATable: "chip", oscAPos: 0.25, oscALevel: 0.85, pulseDuty: 0.5,
      oscBTable: "pulse", oscBPos: 0.5, oscBOctave: 1, oscBLevel: 0.35,
      oscCLevel: 0, unison: 1, subLevel: 0, noiseLevel: 0.08, chipNoise: "gb",
      chipVoiceLimit: 4, hardSync: false,
      filterType: "lowpass", filterCutoff: 6000, filterResonance: 1.2,
      ampAttack: 0.001, ampDecay: 0.15, ampSustain: 0.6, ampRelease: 0.08,
      bitDepth: "8bit", sampleRateReduce: 0.45, crush: 0.12,
      drive: 0.08, chorusMix: 0, delayMix: 0, reverbMix: 0.04, masterGain: 0.82,
    },
  },
  {
    id: "char-raster-square",
    name: "Raster Square",
    tagline: "Pulse + triangle + raster noise",
    color: "#ff5c2e",
    phase: "chip",
    focusModules: ["chip", "osc.a", "osc.b", "filter"],
    inspiration: "8-bit raster square",
    patch: {
      oscATable: "pulse", oscAPos: 0.4, oscALevel: 0.75, pulseDuty: 0.25,
      oscBTable: "basic", oscBPos: 0.15, oscBLevel: 0.45, oscBOctave: -1,
      oscCLevel: 0, unison: 1, subWave: "triangle", subLevel: 0.4,
      noiseLevel: 0.15, chipNoise: "nes", chipVoiceLimit: 4,
      filterType: "lowpass", filterCutoff: 7500, filterResonance: 0.8,
      ampAttack: 0.001, ampDecay: 0.2, ampSustain: 0.5, ampRelease: 0.1,
      bitDepth: "8bit", sampleRateReduce: 0.35, crush: 0.08,
      delayTime: 0.2, delayFeedback: 0.15, delayMix: 0.08, masterGain: 0.8,
    },
  },
  {
    id: "char-grid-noise",
    name: "Grid Noise",
    tagline: "Chip growl · hard sync · ring",
    color: "#62b6ff",
    phase: "chip",
    focusModules: ["chip", "fm", "filter", "osc.a"],
    inspiration: "chip sync growl",
    patch: {
      oscATable: "saw", oscAPos: 0.7, oscALevel: 0.8,
      oscBTable: "pulse", oscBPos: 0.5, oscBLevel: 0.5, pulseDuty: 0.35, hardSync: true,
      oscCLevel: 0, unison: 1, subLevel: 0.1, noiseLevel: 0.1, chipNoise: "periodic",
      chipVoiceLimit: 3, ringAmount: 0.18, ringFreq: 220, fmAmount: 0.12, fmRatio: 2,
      filterType: "lowpass", filterCutoff: 1800, filterResonance: 5, filterDrive: 0.2,
      filterEnvAmount: 0.45, ampAttack: 0.002, ampDecay: 0.35, ampSustain: 0.55, ampRelease: 0.2,
      bitDepth: "12bit", sampleRateReduce: 0.2, drive: 0.15, masterGain: 0.82,
    },
  },
  {
    id: "char-console-fm",
    name: "Console FM",
    tagline: "FM chip grit · bright stack",
    color: "#c98bff",
    phase: "chip",
    focusModules: ["chip", "fm.rack", "fm", "filter"],
    inspiration: "console FM grit",
    patch: {
      oscATable: "metallic", oscAPos: 0.4, oscALevel: 0.7,
      oscBTable: "chip", oscBPos: 0.55, oscBLevel: 0.45, oscBDetune: 4,
      oscCTable: "bell", oscCPos: 0.5, oscCOctave: 1, oscCLevel: 0.25,
      unison: 1, subLevel: 0, chipVoiceLimit: 6, chipNoise: "white",
      fmEngine: "ops4", fmAlg: 4, fmAmount: 0.35, fmRatio: 3,
      fmOp1Level: 1, fmOp2Level: 0.75, fmOp3Level: 0.4, fmOp4Level: 0.25,
      fmOp2Ratio: 2, fmOp3Ratio: 3, fmOp4Ratio: 4, fmFeedback: 0.15,
      filterType: "lowpass", filterCutoff: 5200, filterResonance: 2,
      ampAttack: 0.001, ampDecay: 0.25, ampSustain: 0.45, ampRelease: 0.15,
      bitDepth: "12bit", sampleRateReduce: 0.15, crush: 0.05, masterGain: 0.78,
    },
  },
  {
    id: "char-raster-lead",
    name: "Raster Lead",
    tagline: "Square blip · thin digital body",
    color: "#ffd166",
    phase: "chip",
    focusModules: ["chip", "osc.a", "fx.drive", "filter"],
    inspiration: "thin square lead",
    patch: {
      oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.9, pulseDuty: 0.5,
      oscBTable: "pulse", oscBPos: 0.5, oscBOctave: 1, oscBLevel: 0.3,
      oscCLevel: 0, unison: 1, subLevel: 0, noiseLevel: 0.12, chipNoise: "periodic",
      chipVoiceLimit: 3,
      filterType: "lowpass", filterCutoff: 4500, filterResonance: 1.5,
      ampAttack: 0.001, ampDecay: 0.12, ampSustain: 0.4, ampRelease: 0.06,
      bitDepth: "8bit", sampleRateReduce: 0.55, crush: 0.18, tone: 9000,
      delayMix: 0, reverbMix: 0.03, masterGain: 0.8,
    },
  },
  {
    id: "char-acid-line",
    name: "Acid Line",
    tagline: "Accent · slide · resonant squelch",
    color: "#ff5c2e",
    phase: "chip",
    focusModules: ["chip", "filter", "pitch", "fx.drive"],
    inspiration: "acid accent slide",
    patch: {
      oscATable: "saw", oscAPos: 0.1, oscALevel: 0.92,
      oscBTable: "pulse", oscBPos: 0.35, oscBLevel: 0.15, pulseDuty: 0.55,
      oscCLevel: 0, unison: 1, subLevel: 0,
      filterType: "lowpass", filterCutoff: 380, filterResonance: 16,
      filterEnvAmount: 0.98, filterKeyTrack: 0.4, filterDrive: 0.5,
      filtAttack: 0.001, filtDecay: 0.16, filtSustain: 0.02, filtRelease: 0.06,
      ampAttack: 0.001, ampDecay: 0.2, ampSustain: 0.45, ampRelease: 0.05, velAmount: 1,
      mono: true, glide: 0.08, slideOn: true, accentAmount: 0.85,
      drive: 0.45, driveMode: "tube", punch: 0.3, tone: 12500,
      delayTime: 0.33, delayFeedback: 0.25, delayMix: 0.1, chorusMix: 0, reverbMix: 0.04,
      masterGain: 0.88,
    },
    arp: { enabled: true, mode: "up", bpm: 128, division: "1/16", octaves: 1, gate: 0.55, hold: true },
  },

  // ═══════════════ Phase C — FM / Vector (v3.0) ═══════════════
  {
    id: "char-algorithm-keys",
    name: "Algorithm Keys",
    tagline: "4-op FM electric piano DNA",
    color: "#a78bfa",
    phase: "fm",
    focusModules: ["fm.rack", "fm", "env.amp", "filter"],
    inspiration: "4-op electric keys",
    patch: {
      oscATable: "bell", oscAPos: 0.55, oscALevel: 0.85,
      oscBTable: "metallic", oscBPos: 0.4, oscBLevel: 0.2,
      oscCLevel: 0, unison: 1, subLevel: 0,
      fmEngine: "ops4", fmAlg: 5, fmAmount: 0.55, fmRatio: 2,
      fmOp1Level: 1, fmOp2Level: 0.65, fmOp3Level: 0.4, fmOp4Level: 0.2,
      fmOp2Ratio: 14, fmOp3Ratio: 1, fmOp4Ratio: 1, fmFeedback: 0.35,
      filterType: "lowpass", filterCutoff: 8000, filterResonance: 1,
      ampAttack: 0.001, ampDecay: 1.2, ampSustain: 0.15, ampRelease: 0.9,
      chorusMix: 0.12, reverbSize: 2.5, reverbMix: 0.22, delayMix: 0.08,
      masterGain: 0.78,
    },
  },
  {
    id: "char-additive-spire",
    name: "Additive Spire",
    tagline: "Bright additive FM · glassy partials",
    color: "#8fa8ff",
    phase: "fm",
    focusModules: ["fm.rack", "osc.a", "filter", "fx.reverb"],
    inspiration: "additive FM glass",
    patch: {
      oscATable: "additive", oscAPos: 0.65, oscALevel: 0.75,
      oscBTable: "harmonic", oscBPos: 0.7, oscBOctave: 1, oscBLevel: 0.4, oscBDetune: 3,
      oscCTable: "bell", oscCPos: 0.5, oscCLevel: 0.3,
      unison: 1, subLevel: 0,
      fmEngine: "ops4", fmAlg: 2, fmAmount: 0.4, fmRatio: 3.5,
      fmOp1Level: 1, fmOp2Level: 0.55, fmOp3Level: 0.55, fmOp4Level: 0.3,
      fmOp2Ratio: 2.01, fmOp3Ratio: 3.99, fmOp4Ratio: 5, fmFeedback: 0.1,
      filterType: "highpass", filterCutoff: 280, filterResonance: 1.2,
      ampAttack: 0.002, ampDecay: 0.8, ampSustain: 0.35, ampRelease: 1.2,
      reverbSize: 4, reverbMix: 0.4, delayTime: 0.4, delayMix: 0.15, masterGain: 0.74,
    },
  },
  {
    id: "char-vector-drift",
    name: "Vector Drift",
    tagline: "Vector morph · wave-sequence motion",
    color: "#62b6ff",
    phase: "fm",
    focusModules: ["morph", "fm.rack", "osc.a", "osc.b"],
    inspiration: "vector wave morph",
    patch: {
      oscATable: "harmonic", oscAPos: 0.3, oscALevel: 0.7, oscALfo: 0.15,
      oscBTable: "vocal", oscBPos: 0.55, oscBLevel: 0.6, oscBDetune: 6,
      oscCTable: "formant2", oscCPos: 0.4, oscCOctave: 1, oscCLevel: 0.3,
      unison: 2, unisonDetune: 8, unisonWidth: 0.6, subLevel: 0.08,
      vectorRate: 0.22, vectorDepth: 0.65,
      modMatrix: makeModMatrix([
        MR("lfo1", "wtA", 0.5),
        MR("lfo2", "wtB", 0.45),
      ]),
      lfo1Wave: "sine", lfo1Rate: 0.15, lfo1Depth: 0.4, lfo1Dest: "off",
      lfo2Wave: "triangle", lfo2Rate: 0.09, lfo2Depth: 0.35, lfo2Dest: "off",
      filterType: "lowpass", filterCutoff: 4200, filterResonance: 1.5,
      ampAttack: 0.2, ampDecay: 0.6, ampSustain: 0.9, ampRelease: 1.2,
      chorusMix: 0.35, reverbSize: 3.8, reverbMix: 0.35, masterGain: 0.75,
    },
  },
  {
    id: "char-color-morph",
    name: "Color Morph",
    tagline: "Colorful macros · morph pad DNA",
    color: "#ff6a9b",
    phase: "fm",
    focusModules: ["morph", "macros", "matrix", "osc.a"],
    inspiration: "macro color morph",
    patch: {
      oscATable: "fold", oscAPos: 0.45, oscALevel: 0.7, oscAEnv: 0.2,
      oscBTable: "metallic", oscBPos: 0.5, oscBLevel: 0.5, oscBDetune: 9,
      oscCTable: "harmonic", oscCPos: 0.6, oscCLevel: 0.35, oscCOctave: 1,
      unison: 4, unisonDetune: 16, unisonWidth: 0.85, subLevel: 0.1,
      warpStretch: 0.15, warpTilt: 0.1, warpComb: 0.08,
      vectorRate: 0.12, vectorDepth: 0.4,
      modMatrix: makeModMatrix([
        MR("macro1", "cutoff", 0.7),
        MR("macro2", "wtA", 0.6),
        MR("macro3", "fm", 0.5),
        MR("macro4", "reverb", 0.45),
        MR("lfo1", "pan", 0.3),
        MR("modenv", "wtB", 0.35),
      ]),
      macro1: 0.4, macro2: 0.35, macro3: 0.2, macro4: 0.3,
      lfo1Wave: "sine", lfo1Rate: 0.35, lfo1Depth: 0.3, lfo1Dest: "filter",
      filterType: "lowpass", filterCutoff: 3500, filterResonance: 2.5,
      ampAttack: 0.05, ampDecay: 0.4, ampSustain: 0.8, ampRelease: 0.6,
      chorusMix: 0.3, delayMix: 0.2, reverbMix: 0.3, spectralMode: "smear",
      spectralAmount: 0.25, spectralMix: 0.2, masterGain: 0.76,
    },
  },
  {
    id: "char-formant-wall",
    name: "Formant Wall",
    tagline: "Aggressive hypersaw · spectral bite",
    color: "#ff5c2e",
    phase: "fm",
    focusModules: ["fire.sec.warp", "mixer.unison", "filter", "fx.spectral"],
    inspiration: "hypersaw formant wall",
    patch: {
      // Headroom pass: 7-voice unison × osc sum ~1.75 guaranteed clip on
      // chords — trimmed ~18% (character intact, the wall now comes from
      // unison width + warp, not raw overload).
      oscATable: "saw", oscAPos: 0.95, oscALevel: 0.62,
      oscBTable: "fold", oscBPos: 0.6, oscBLevel: 0.46, oscBDetune: 12,
      oscCTable: "sync", oscCPos: 0.5, oscCLevel: 0.25, oscCOctave: 1,
      unison: 7, unisonDetune: 28, unisonWidth: 1, subLevel: 0.12,
      warpStretch: 0.35, warpTilt: -0.2, warpComb: 0.25,
      filterType: "lowpass", filterCutoff: 2800, filterResonance: 4, filterDrive: 0.35,
      filterEnvAmount: 0.4, ampAttack: 0.01, ampDecay: 0.3, ampSustain: 0.85, ampRelease: 0.35,
      drive: 0.28, driveMode: "hard", spectralMode: "shift", spectralAmount: 0.45, spectralMix: 0.35,
      chorusMix: 0.25, masterGain: 0.78,
    },
  },
  {
    id: "char-saw-legion",
    name: "Saw Legion",
    tagline: "Supersaw trance lead · wide chorus",
    color: "#ffb648",
    phase: "fm",
    focusModules: ["mixer.unison", "filter", "fx.chorus", "lfo.1"],
    inspiration: "wide supersaw lead",
    patch: {
      // Headroom pass: see char-formant-wall — supersaw stays super via
      // unison/detune, not via a 1.68 osc sum.
      oscATable: "saw", oscAPos: 0.92, oscALevel: 0.6, oscAEnv: 0.15,
      oscBTable: "saw", oscBPos: 0.85, oscBDetune: 11, oscBLevel: 0.5,
      oscCTable: "saw", oscCPos: 0.75, oscCOctave: 1, oscCDetune: -8, oscCLevel: 0.24,
      unison: 7, unisonDetune: 26, unisonWidth: 1, subLevel: 0.08,
      filterType: "lowpass", filterCutoff: 6500, filterResonance: 1.4,
      filterEnvAmount: 0.4, ampAttack: 0.04, ampDecay: 0.35, ampSustain: 0.85, ampRelease: 0.5,
      lfo1Wave: "sine", lfo1Rate: 0.25, lfo1Depth: 0.2, lfo1Dest: "filter",
      chorusRate: 0.55, chorusDepth: 0.55, chorusMix: 0.5,
      delayTime: 0.375, delayFeedback: 0.38, delayMix: 0.28,
      reverbSize: 3.2, reverbMix: 0.28, drive: 0.1, punch: 0.2, masterGain: 0.76,
    },
  },
  {
    id: "char-silk-pluck",
    name: "Silk Pluck",
    tagline: "Lush layered pad · soft analog",
    color: "#7ce8d5",
    phase: "fm",
    focusModules: ["osc.a", "osc.b", "filter", "env.amp"],
    inspiration: "soft layered silk",
    patch: {
      oscATable: "vocal", oscAPos: 0.4, oscALevel: 0.6, oscALfo: 0.2,
      oscBTable: "harmonic", oscBPos: 0.5, oscBDetune: 10, oscBLevel: 0.55,
      oscCTable: "formant2", oscCPos: 0.45, oscCOctave: 1, oscCLevel: 0.3, oscCDetune: -4,
      unison: 4, unisonDetune: 14, unisonWidth: 0.8, subLevel: 0.12,
      drift: 0.18, voiceInstability: 0.12, tuneVariance: 0.08,
      filterType: "lowpass", filterCutoff: 2400, filterResonance: 2,
      ampAttack: 0.6, ampDecay: 0.8, ampSustain: 0.95, ampRelease: 1.6,
      chorusMix: 0.4, phaserMix: 0.15, reverbSize: 4.5, reverbMix: 0.42,
      analogComp: 0.25, bbdChorus: 0.2, masterGain: 0.72,
    },
  },
  {
    id: "char-soft-spectrum",
    name: "Soft Spectrum",
    tagline: "Spectral partials · organic smear",
    color: "#d4a5ff",
    phase: "fm",
    focusModules: ["fire.sec.warp", "osc.a", "fx.spectral", "filter"],
    inspiration: "spectral organic smear",
    patch: {
      oscATable: "additive", oscAPos: 0.5, oscALevel: 0.7, oscALfo: 0.25,
      oscBTable: "formant2", oscBPos: 0.4, oscBLevel: 0.5, oscBDetune: 5,
      oscCTable: "harmonic", oscCPos: 0.55, oscCLevel: 0.35,
      unison: 3, unisonDetune: 10, unisonWidth: 0.75, subLevel: 0.05,
      warpStretch: 0.4, warpTilt: 0.25, warpComb: 0.15,
      filterType: "bandpass", filterCutoff: 1600, filterResonance: 2.5,
      ampAttack: 0.8, ampDecay: 1, ampSustain: 1, ampRelease: 2,
      spectralMode: "smear", spectralAmount: 0.55, spectralMix: 0.45,
      reverbSize: 5, reverbMix: 0.5, chorusMix: 0.25, masterGain: 0.7,
    },
  },
  {
    id: "char-seed-morph",
    name: "Seed Morph",
    tagline: "Generative seed · mutate-ready macros",
    color: "#9be564",
    phase: "fm",
    focusModules: ["macros", "morph", "matrix", "osc.a"],
    inspiration: "generative seed morph",
    patch: {
      oscATable: "growl", oscAPos: 0.4, oscALevel: 0.7, oscAEnv: 0.3,
      oscBTable: "fold", oscBPos: 0.55, oscBLevel: 0.5, oscBDetune: 14,
      oscCTable: "chip", oscCPos: 0.5, oscCLevel: 0.25, oscCOctave: 1,
      unison: 3, unisonDetune: 18, unisonWidth: 0.7, subLevel: 0.2,
      fmAmount: 0.18, fmRatio: 1.7, warpComb: 0.12,
      modMatrix: makeModMatrix([
        MR("macro1", "cutoff", 0.8),
        MR("macro2", "wtA", 0.7),
        MR("macro3", "volume", 0.5),
        MR("macro4", "delay", 0.4),
        MR("modenv", "fm", 0.45),
      ]),
      macro1: 0.5, macro2: 0.4, macro3: 0.25, macro4: 0.2,
      filterType: "lowpass", filterCutoff: 1800, filterResonance: 4,
      filterEnvAmount: 0.35, ampAttack: 0.02, ampDecay: 0.4, ampSustain: 0.7, ampRelease: 0.4,
      drive: 0.2, delayMix: 0.18, reverbMix: 0.2, masterGain: 0.78,
    },
  },
  {
    id: "char-dream-lattice",
    name: "Dream Lattice",
    tagline: "Dream lattice formants",
    color: "#c98bff",
    phase: "fm",
    focusModules: ["fire.sec.warp", "fx.spectral", "osc.a", "filter"],
    inspiration: "spectral formant dream",
    patch: {
      oscATable: "formant2", oscAPos: 0.45, oscALevel: 0.75, oscALfo: 0.3,
      oscBTable: "vocal", oscBPos: 0.55, oscBLevel: 0.5, oscBDetune: 8,
      oscCTable: "metallic", oscCPos: 0.4, oscCLevel: 0.3, oscCOctave: 1,
      unison: 4, unisonDetune: 12, unisonWidth: 0.9, subLevel: 0.08,
      warpStretch: 0.5, warpTilt: 0.3, warpComb: 0.2,
      filterType: "bandpass", filterCutoff: 2200, filterResonance: 3,
      ampAttack: 0.3, ampDecay: 0.7, ampSustain: 0.9, ampRelease: 1.4,
      spectralMode: "freeze", spectralAmount: 0.4, spectralMix: 0.35,
      phaserMix: 0.25, reverbSize: 5.2, reverbMix: 0.48, masterGain: 0.7,
    },
  },
  {
    id: "char-macro-atlas",
    name: "Macro Atlas",
    tagline: "Matrix · macro · performance map",
    color: "#ff9a6b",
    phase: "fm",
    focusModules: ["matrix", "macros", "morph", "gate"],
    inspiration: "macro performance atlas",
    patch: {
      oscATable: "saw", oscAPos: 0.7, oscALevel: 0.7,
      oscBTable: "pulse", oscBPos: 0.45, oscBLevel: 0.5, pulseDuty: 0.4,
      oscCTable: "harmonic", oscCPos: 0.5, oscCLevel: 0.3, oscCOctave: 1,
      unison: 5, unisonDetune: 18, unisonWidth: 0.85, subLevel: 0.15,
      modMatrix: makeModMatrix([
        MR("macro1", "cutoff", 0.85),
        MR("macro2", "resonance", 0.55),
        MR("macro3", "wtA", 0.65),
        MR("macro4", "reverb", 0.5),
        MR("lfo1", "pan", 0.4),
        MR("modenv", "wtB", 0.35),
      ]),
      macro1: 0.45, macro2: 0.3, macro3: 0.35, macro4: 0.4,
      lfo1Wave: "triangle", lfo1Rate: 0.4, lfo1Depth: 0.35, lfo1Dest: "off",
      filterType: "lowpass", filterCutoff: 3000, filterResonance: 3,
      ampAttack: 0.04, ampDecay: 0.35, ampSustain: 0.8, ampRelease: 0.45,
      gateOn: true, gateRate: 8, gateDepth: 0.7, gateSmooth: 0.35,
      chorusMix: 0.3, delayMix: 0.15, reverbMix: 0.22, masterGain: 0.78,
    },
  },
];

/** Resolve a character into a full patch ready for the engine/store. */
export function resolveCharacterPatch(character: FireCharacter): FirePatch {
  return cloneFirePatch(character.patch);
}

const PHASE_CATEGORY: Record<FireCharacterPhase, PresetCategory> = {
  vintage: "Vintage",
  chip: "Chip",
  fm: "FM",
};

/**
 * Character-linked factory presets (~23) — appear in the Patch Library under
 * Vintage / Chip / FM categories.
 */
export const CHARACTER_LINKED_PRESETS: FirePreset[] = FIRE_CHARACTERS.map((c) => ({
  id: `gen-${c.id}`,
  name: `Genesis · ${c.name}`,
  desc: `${c.tagline} — inspired by ${c.inspiration}`,
  category: PHASE_CATEGORY[c.phase],
  patch: resolveCharacterPatch(c),
  arp: c.arp,
}));
