import {
  DEFAULT_FIRE_PATCH,
  makeModMatrix,
  type FirePatch,
  type ModRoute,
  type ModSource,
  type ModDest,
} from "./FireCommandSynth";
import type { FirePreset, PresetCategory, PresetArp } from "./firePresetBank";

const P = (over: Partial<FirePatch>): FirePatch => ({ ...DEFAULT_FIRE_PATCH, ...over });
const MR = (source: ModSource, dest: ModDest, amount: number): ModRoute => ({ source, dest, amount });

function preset(
  id: string,
  name: string,
  desc: string,
  category: PresetCategory,
  patch: Partial<FirePatch>,
  arp?: PresetArp,
): FirePreset {
  return { id, name, desc, category, patch: P(patch), arp };
}

export const CURATED_PRESETS: FirePreset[] = [
  // ===== BASS (20) =====
  preset("fc-bass-sub-sine", "Sub Sine Boom", "Pure sub bass with sine wave", "Bass", {
    subLevel: 0.45,
    oscATable: "basic",
    oscALevel: 0.8,
    oscBTable: "basic",
    oscBLevel: 0.5,
    oscBOctave: -1,
    filterType: "lowpass",
    filterCutoff: 800,
    filterResonance: 0.1,
    filterEnvAmount: 0.3,
    ampAttack: 0.001,
    ampDecay: 0.4,
    ampSustain: 0.3,
    ampRelease: 0.5,
    mono: true
}),

  preset("fc-bass-reese", "Reese Detune", "Classic detuned bass", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "saw",
    oscBLevel: 0.7,
    oscBDetune: 15,
    filterType: "lowpass",
    filterCutoff: 1200,
    filterResonance: 0.3,
    filterEnvAmount: 0.5,
    ampAttack: 0.01,
    ampDecay: 0.6,
    ampSustain: 0.5,
    ampRelease: 0.3,
    unison: 3,
    unisonDetune: 10,
    mono: true
}),

  preset("fc-bass-acid-squelch", "Acid Squelch", "Mono acid bass with resonance", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.8,
    filterType: "lowpass",
    filterCutoff: 600,
    filterResonance: 0.75,
    filterEnvAmount: 0.85,
    filtAttack: 0.001,
    filtDecay: 0.35,
    filtSustain: 0.1,
    ampAttack: 0.001,
    ampDecay: 0.3,
    ampSustain: 0.6,
    ampRelease: 0.1,
    glide: 0.08,
    mono: true
}),

  preset("fc-bass-fm-punch", "FM Punch", "FM bass with attack", "Bass", {
    subLevel: 0.28,
    oscATable: "harmonic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.4,
    ringAmount: 0.3,
    filterType: "lowpass",
    filterCutoff: 1600,
    filterResonance: 0.2,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.7,
    ampRelease: 0.2,
    mono: true
}),

  preset("fc-bass-vocal-morph", "Talking Bass", "Vocal formant bass", "Bass", {
    subLevel: 0.28,
    oscATable: "vocal",
    oscALevel: 0.6,
    oscBTable: "formant2",
    oscBLevel: 0.6,
    oscBOctave: -1,
    filterType: "bandpass",
    filterCutoff: 1400,
    filterResonance: 0.5,
    filterEnvAmount: 0.4,
    ampAttack: 0.01,
    ampDecay: 0.4,
    ampSustain: 0.5,
    ampRelease: 0.3,
    lfo1Rate: 4,
    lfo1Wave: "triangle",
    lfo1Depth: 0.5,
    lfo1Dest: "filter",
    mono: true
}),

  preset("fc-bass-growl-drive", "Growling Drive", "Distorted growl bass", "Bass", {
    subLevel: 0.28,
    oscATable: "growl",
    oscALevel: 0.7,
    oscBTable: "growl",
    oscBLevel: 0.7,
    oscBDetune: -8,
    filterType: "lowpass",
    filterCutoff: 1300,
    filterResonance: 0.6,
    filterDrive: 0.7,
    ampAttack: 0.005,
    ampDecay: 0.5,
    ampSustain: 0.6,
    ampRelease: 0.4,
    mono: true
}),

  preset("fc-bass-808-thump", "808 Thump", "Clean 808-style bass", "Bass", {
    subLevel: 0.45,
    oscATable: "basic",
    oscALevel: 0.9,
    filterType: "lowpass",
    filterCutoff: 1800,
    filterResonance: 0.1,
    ampAttack: 0.001,
    ampDecay: 0.8,
    ampSustain: 0,
    ampRelease: 0.1,
    pitchEnvAmount: 0.12,
    pitchEnvTime: 0.08,
    mono: true
}),

  preset("fc-bass-mid-stab", "Mid Bass Stab", "Punchy mid-range bass", "Bass", {
    subLevel: 0.28,
    oscATable: "pulse",
    oscAPos: 0.3,
    oscALevel: 0.7,
    oscBTable: "saw",
    oscBLevel: 0.3,
    oscBOctave: 1,
    filterType: "lowpass",
    filterCutoff: 2000,
    filterResonance: 0.4,
    filterEnvAmount: 0.6,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.4,
    ampRelease: 0.15
}),

  preset("fc-bass-wobble-lfo", "Wobble LFO", "Filtered wobble bass", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "pulse",
    oscBPos: 0.2,
    oscBLevel: 0.6,
    filterType: "lowpass",
    filterCutoff: 900,
    filterResonance: 0.7,
    lfo1Rate: 8,
    lfo1Wave: "sine",
    lfo1Depth: 0.8,
    lfo1Dest: "filter",
    ampAttack: 0.01,
    ampDecay: 1,
    ampSustain: 0.8,
    ampRelease: 0.3,
    mono: true
}),

  preset("fc-bass-noisy-dirt", "Noisy Dirt", "Lo-fi dirty bass", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "pulse",
    oscBPos: 0.6,
    oscBLevel: 0.6,
    noiseLevel: 0.15,
    filterType: "lowpass",
    filterCutoff: 1400,
    filterResonance: 0.3,
    filterDrive: 0.5,
    ampAttack: 0.01,
    ampDecay: 0.5,
    ampSustain: 0.6,
    ampRelease: 0.4,
    crush: 0.3,
    mono: true
}),

  preset("fc-bass-glide-port", "Glide Portamento", "Smooth gliding bass", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "pulse",
    oscBPos: 0.4,
    oscBLevel: 0.5,
    oscBOctave: -1,
    filterType: "lowpass",
    filterCutoff: 1600,
    filterResonance: 0.3,
    glide: 0.25,
    mono: true,
    ampAttack: 0.02,
    ampDecay: 0.6,
    ampSustain: 0.7,
    ampRelease: 0.4
}),

  preset("fc-bass-soft-triangle", "Soft Triangle Under", "Mellow triangle bass", "Bass", {
    subLevel: 0.28,
    oscATable: "basic",
    oscAPos: 0.5,
    oscALevel: 0.8,
    oscBTable: "basic",
    oscBPos: 0.5,
    oscBLevel: 0.5,
    oscBOctave: -1,
    filterType: "lowpass",
    filterCutoff: 1800,
    filterResonance: 0.15,
    ampAttack: 0.02,
    ampDecay: 0.5,
    ampSustain: 0.6,
    ampRelease: 0.5
}),

  preset("fc-bass-wide-unison", "Wide Unison Monster", "Massive unison bass", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "saw",
    oscBLevel: 0.7,
    oscBDetune: 10,
    filterType: "lowpass",
    filterCutoff: 1400,
    filterResonance: 0.4,
    unison: 5,
    unisonDetune: 15,
    unisonWidth: 0.8,
    ampAttack: 0.015,
    ampDecay: 0.6,
    ampSustain: 0.6,
    ampRelease: 0.4,
    mono: true
}),

  preset("fc-bass-formant", "Formant Bass", "Vowel-like bass", "Bass", {
    subLevel: 0.28,
    oscATable: "formant2",
    oscALevel: 0.7,
    oscBTable: "vocal",
    oscBLevel: 0.6,
    filterType: "bandpass",
    filterCutoff: 1200,
    filterResonance: 0.6,
    ampAttack: 0.01,
    ampDecay: 0.5,
    ampSustain: 0.5,
    ampRelease: 0.3,
    mono: true
}),

  preset("fc-bass-sync-sweep", "Sync Sweep Bass", "Hard sync bass sweep", "Bass", {
    subLevel: 0.28,
    oscATable: "sync",
    oscAPos: 0.6,
    oscALevel: 0.7,
    oscBTable: "saw",
    oscBLevel: 0.6,
    filterType: "lowpass",
    filterCutoff: 1600,
    filterResonance: 0.5,
    filterEnvAmount: 0.5,
    ampAttack: 0.01,
    ampDecay: 0.5,
    ampSustain: 0.5,
    ampRelease: 0.3,
    mono: true
}),

  preset("fc-bass-crushed-lofi", "Crushed Lo-Fi", "Bitcrushed bass", "Bass", {
    subLevel: 0.28,
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.7,
    oscBTable: "saw",
    oscBLevel: 0.6,
    filterType: "lowpass",
    filterCutoff: 1400,
    filterResonance: 0.2,
    crush: 0.6,
    sampleRateReduce: 0.4,
    ampAttack: 0.01,
    ampDecay: 0.4,
    ampSustain: 0.5,
    ampRelease: 0.3,
    mono: true
}),

  preset("fc-bass-pitch-env", "Pitch Env Thump", "Pitch envelope bass hit", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.8,
    filterType: "lowpass",
    filterCutoff: 1600,
    filterResonance: 0.3,
    pitchEnvAmount: 0.2,
    pitchEnvTime: 0.15,
    ampAttack: 0.001,
    ampDecay: 0.6,
    ampSustain: 0.3,
    ampRelease: 0.2,
    mono: true
}),

  preset("fc-bass-ring-metal", "Ring Mod Metal", "Metallic ring mod bass", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "metallic",
    oscBLevel: 0.6,
    ringAmount: 0.6,
    filterType: "lowpass",
    filterCutoff: 1800,
    filterResonance: 0.3,
    ampAttack: 0.01,
    ampDecay: 0.5,
    ampSustain: 0.5,
    ampRelease: 0.3,
    mono: true
}),

  preset("fc-bass-dual-oct", "Dual Octave Stack", "Two octave bass stack", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "saw",
    oscBLevel: 0.6,
    oscBOctave: -1,
    filterType: "lowpass",
    filterCutoff: 1600,
    filterResonance: 0.3,
    ampAttack: 0.01,
    ampDecay: 0.6,
    ampSustain: 0.6,
    ampRelease: 0.4
}),

  preset("fc-bass-airy-high", "Airy High Bass", "High-passed airy bass", "Bass", {
    subLevel: 0.28,
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "pulse",
    oscBPos: 0.3,
    oscBLevel: 0.5,
    oscBOctave: 1,
    filterType: "highpass",
    filterCutoff: 1400,
    filterResonance: 0.2,
    ampAttack: 0.02,
    ampDecay: 0.5,
    ampSustain: 0.6,
    ampRelease: 0.5,
    reverbMix: 0.15
}),




  // ===== LEAD (20) =====
  preset("fc-lead-saw-edge", "Saw Edge Blade", "Bright mono saw with a sharp filter edge", "Lead", {
    oscATable: "saw",
    oscALevel: 0.78,
    filterType: "lowpass",
    filterCutoff: 4200,
    filterResonance: 0.45,
    filterEnvAmount: 0.55,
    ampAttack: 0.01,
    ampDecay: 0.25,
    ampSustain: 0.7,
    ampRelease: 0.2,
    mono: true,
    drive: 0.15,
  }),

  preset("fc-lead-soft-silk", "Soft Silk Lead", "Gentle soft lead with slow attack", "Lead", {
    oscATable: "basic",
    oscALevel: 0.7,
    filterCutoff: 2200,
    ampAttack: 0.08,
    ampDecay: 0.4,
    ampSustain: 0.8,
    ampRelease: 0.45,
    chorusMix: 0.2,
    mono: true,
  }),

  preset("fc-lead-supersaw", "Supersaw Horizon", "Wide unison saw that fills the stereo field", "Lead", {
    oscATable: "saw",
    oscALevel: 0.65,
    oscBTable: "saw",
    oscBLevel: 0.45,
    oscBDetune: 12,
    unison: 5,
    unisonDetune: 14,
    unisonWidth: 0.85,
    filterCutoff: 3600,
    ampAttack: 0.02,
    ampDecay: 0.3,
    ampSustain: 0.75,
    ampRelease: 0.3,
    chorusMix: 0.25,
    mono: true,
  }),

  preset("fc-lead-acid-scream", "Acid Scream", "Resonant screaming acid mono lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.8,
    filterCutoff: 900,
    filterResonance: 0.82,
    filterEnvAmount: 0.9,
    filtAttack: 0.001,
    filtDecay: 0.28,
    filtSustain: 0.05,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.55,
    ampRelease: 0.12,
    glide: 0.06,
    mono: true,
  }),

  preset("fc-lead-pulse-talk", "Pulse Talker", "Narrow pulse that chatters like a talkbox", "Lead", {
    oscATable: "pulse",
    oscAPos: 0.18,
    oscALevel: 0.75,
    filterCutoff: 2800,
    filterResonance: 0.35,
    ampAttack: 0.005,
    ampDecay: 0.22,
    ampSustain: 0.65,
    ampRelease: 0.18,
    lfo1Wave: "sine",
    lfo1Rate: 4.5,
    lfo1Depth: 0.35,
    lfo1Dest: "filter",
    mono: true,
  }),

  preset("fc-lead-fm-bell", "FM Bell Pierce", "Metallic FM bell lead with fast decay", "Lead", {
    oscATable: "bell",
    oscALevel: 0.75,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.55,
    fmRatio: 3.5,
    filterCutoff: 5200,
    ampAttack: 0.001,
    ampDecay: 0.4,
    ampSustain: 0.35,
    ampRelease: 0.35,
    delayMix: 0.2,
    mono: true,
  }),

  preset("fc-lead-portamento", "Portamento Snake", "Gliding mono snake lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.72,
    oscBTable: "pulse",
    oscBLevel: 0.35,
    oscBPos: 0.4,
    filterCutoff: 2600,
    ampAttack: 0.03,
    ampDecay: 0.35,
    ampSustain: 0.8,
    ampRelease: 0.25,
    glide: 0.22,
    mono: true,
  }),

  preset("fc-lead-trance-gate", "Trance Gate Lead", "Bright gated trance stab lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.7,
    unison: 3,
    unisonDetune: 9,
    filterCutoff: 4800,
    ampAttack: 0.005,
    ampDecay: 0.2,
    ampSustain: 0.7,
    ampRelease: 0.15,
    delayTime: 0.375,
    delayMix: 0.22,
    gateOn: true,
    gateRate: 8,
    gateDepth: 0.7,
    mono: true,
  }),

  preset("fc-lead-vintage-nasal", "Vintage Nasal", "Narrow bandpass nasal lead with tape age", "Lead", {
    oscATable: "pulse",
    oscAPos: 0.35,
    oscALevel: 0.7,
    filterType: "bandpass",
    filterCutoff: 1400,
    filterResonance: 0.55,
    ampAttack: 0.02,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.25,
    cassetteGen: 0.4,
    wowFlutter: 0.15,
    hiss: 0.12,
    mono: true,
  }),

  preset("fc-lead-chip-square", "Chip Square Zap", "Retro square lead with hard edges", "Lead", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.8,
    pulseDuty: 0.5,
    filterCutoff: 6000,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.55,
    ampRelease: 0.1,
    mono: true,
  }),

  preset("fc-lead-harmony-stack", "Harmony Stack Lead", "Stacked octaves that bloom on hold", "Lead", {
    oscATable: "saw",
    oscALevel: 0.55,
    oscBTable: "saw",
    oscBLevel: 0.5,
    oscBDetune: 8,
    oscCTable: "saw",
    oscCLevel: 0.4,
    oscCOctave: 1,
    filterCutoff: 3200,
    ampAttack: 0.04,
    ampDecay: 0.4,
    ampSustain: 0.85,
    ampRelease: 0.5,
    chorusMix: 0.3,
    reverbMix: 0.2,
  }),

  preset("fc-lead-drive-grit", "Drive Grit Lead", "Tube-driven gritty mid lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.75,
    filterCutoff: 2400,
    filterResonance: 0.3,
    ampAttack: 0.01,
    ampDecay: 0.28,
    ampSustain: 0.7,
    ampRelease: 0.22,
    drive: 0.55,
    driveMode: "tube",
    mono: true,
  }),

  preset("fc-lead-air-whistle", "Air Whistle", "High airy whistle lead", "Lead", {
    oscATable: "basic",
    oscALevel: 0.65,
    oscAOctave: 1,
    filterType: "highpass",
    filterCutoff: 1800,
    ampAttack: 0.05,
    ampDecay: 0.35,
    ampSustain: 0.75,
    ampRelease: 0.4,
    airHigh: 0.4,
    airAmount: 0.5,
    reverbMix: 0.25,
    mono: true,
  }),

  preset("fc-lead-ring-spark", "Ring Spark Lead", "Ring-mod sparks over a saw body", "Lead", {
    oscATable: "saw",
    oscALevel: 0.7,
    ringAmount: 0.35,
    ringFreq: 660,
    filterCutoff: 3800,
    ampAttack: 0.005,
    ampDecay: 0.25,
    ampSustain: 0.6,
    ampRelease: 0.2,
    mono: true,
  }),

  preset("fc-lead-lfo-wobble", "LFO Wobble Lead", "Filter wobble mono lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.72,
    filterCutoff: 1800,
    filterResonance: 0.5,
    ampAttack: 0.02,
    ampDecay: 0.3,
    ampSustain: 0.75,
    ampRelease: 0.25,
    lfo1Wave: "sine",
    lfo1Rate: 5.5,
    lfo1Depth: 0.55,
    lfo1Dest: "filter",
    mono: true,
  }),

  preset("fc-lead-plucky-hook", "Plucky Hook Lead", "Short plucky lead for hooks", "Lead", {
    oscATable: "pulse",
    oscAPos: 0.4,
    oscALevel: 0.75,
    filterCutoff: 3400,
    filterEnvAmount: 0.6,
    filtDecay: 0.15,
    ampAttack: 0.001,
    ampDecay: 0.22,
    ampSustain: 0.15,
    ampRelease: 0.12,
    delayMix: 0.15,
    mono: true,
  }),

  preset("fc-lead-warm-analog", "Warm Analog Lead", "Detuned warm analog lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.68,
    oscBTable: "saw",
    oscBLevel: 0.5,
    oscBDetune: 8,
    filterCutoff: 2100,
    ampAttack: 0.03,
    ampDecay: 0.4,
    ampSustain: 0.8,
    ampRelease: 0.35,
    chorusMix: 0.18,
    cassetteGen: 0.2,
    mono: true,
  }),

  preset("fc-lead-phase-sweep", "Phase Sweep Lead", "Phaser-swept luminous lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 4000,
    ampAttack: 0.02,
    ampDecay: 0.3,
    ampSustain: 0.75,
    ampRelease: 0.3,
    phaserRate: 0.4,
    phaserDepth: 0.7,
    phaserMix: 0.45,
    mono: true,
  }),

  preset("fc-lead-oct-scream", "Octave Scream", "Dual-octave screaming lead", "Lead", {
    oscATable: "saw",
    oscALevel: 0.6,
    oscBTable: "saw",
    oscBLevel: 0.55,
    oscBOctave: 1,
    filterCutoff: 4500,
    filterResonance: 0.35,
    ampAttack: 0.005,
    ampDecay: 0.25,
    ampSustain: 0.7,
    ampRelease: 0.2,
    drive: 0.25,
    mono: true,
  }),

  preset("fc-lead-delay-echo", "Delay Echo Lead", "Sparse lead riding long echoes", "Lead", {
    oscATable: "saw",
    oscALevel: 0.65,
    filterCutoff: 3000,
    ampAttack: 0.02,
    ampDecay: 0.35,
    ampSustain: 0.55,
    ampRelease: 0.4,
    delayTime: 0.45,
    delayFeedback: 0.55,
    delayMix: 0.4,
    reverbMix: 0.2,
    mono: true,
  }),


  // ===== PLUCK (20) =====
  preset("fc-pluck-nylon-snap", "Nylon Snap", "Soft nylon-like finger pluck", "Pluck", {
    oscATable: "pulse",
    oscAPos: 0.35,
    oscALevel: 0.7,
    filterCutoff: 2200,
    filterEnvAmount: 0.45,
    filtDecay: 0.12,
    ampAttack: 0.001,
    ampDecay: 0.28,
    ampSustain: 0.08,
    ampRelease: 0.18,
    reverbMix: 0.15,
  }),

  preset("fc-pluck-steel-twang", "Steel Twang", "Bright steel string twang", "Pluck", {
    oscATable: "saw",
    oscALevel: 0.72,
    filterCutoff: 4800,
    filterResonance: 0.25,
    filterEnvAmount: 0.7,
    filtDecay: 0.1,
    ampAttack: 0.001,
    ampDecay: 0.22,
    ampSustain: 0.05,
    ampRelease: 0.15,
  }),

  preset("fc-pluck-kalimba", "Kalimba Tine", "Metallic kalimba tine pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "bell",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.25,
    fmAmount: 0.25,
    filterCutoff: 5200,
    ampAttack: 0.001,
    ampDecay: 0.45,
    ampSustain: 0.05,
    ampRelease: 0.35,
    reverbMix: 0.25,
  }),

  preset("fc-pluck-harp-gliss", "Harp Gliss", "Airy harp gliss pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "basic",
    oscALevel: 0.65,
    filterCutoff: 3600,
    ampAttack: 0.002,
    ampDecay: 0.5,
    ampSustain: 0.1,
    ampRelease: 0.6,
    chorusMix: 0.2,
    reverbMix: 0.35,
  }),

  preset("fc-pluck-muted-funk", "Muted Funk Pluck", "Muted funk guitar-style pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "pulse",
    oscAPos: 0.2,
    oscALevel: 0.75,
    filterCutoff: 1800,
    filterResonance: 0.3,
    ampAttack: 0.001,
    ampDecay: 0.12,
    ampSustain: 0.02,
    ampRelease: 0.08,
    punch: 0.3,
  }),

  preset("fc-pluck-glass-tap", "Glass Tap", "Glass-tapping crystalline pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "bell",
    oscALevel: 0.68,
    filterType: "highpass",
    filterCutoff: 1200,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.05,
    ampRelease: 0.4,
    delayMix: 0.2,
    reverbMix: 0.3,
  }),

  preset("fc-pluck-bass-thump", "Bass Pluck Thump", "Low thumpy bass pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "basic",
    oscALevel: 0.8,
    oscAOctave: -1,
    subLevel: 0.35,
    filterCutoff: 900,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.1,
    ampRelease: 0.2,
    mono: true,
    punch: 0.4,
  }),

  preset("fc-pluck-chip-blip", "Chip Blip", "8-bit chip blip pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "pulse",
    oscAPos: 0.5,
    pulseDuty: 0.25,
    oscALevel: 0.75,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 0.15,
    ampSustain: 0.05,
    ampRelease: 0.08,
  }),

  preset("fc-pluck-bloom-tail", "Bloom Tail Pluck", "Pluck that blooms into a soft pad tail", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "saw",
    oscALevel: 0.6,
    filterCutoff: 2800,
    ampAttack: 0.001,
    ampDecay: 0.4,
    ampSustain: 0.35,
    ampRelease: 0.9,
    reverbMix: 0.4,
    chorusMix: 0.25,
  }),

  preset("fc-pluck-resonant-zap", "Resonant Zap", "Resonant filter zap pluck", "Pluck", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 800,
    filterResonance: 0.75,
    filterEnvAmount: 0.9,
    filtDecay: 0.18,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.05,
    ampRelease: 0.12,
  }),

  preset("fc-pluck-marimba", "Marimba Wood", "Wooden marimba bar hit", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "bell",
    oscBLevel: 0.3,
    filterCutoff: 3200,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.05,
    ampRelease: 0.25,
    reverbMix: 0.18,
  }),

  preset("fc-pluck-delay-dots", "Delay Dot Plucks", "Sparse plucks painting delay dots", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "pulse",
    oscAPos: 0.4,
    oscALevel: 0.65,
    filterCutoff: 3000,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.05,
    ampRelease: 0.15,
    delayTime: 0.333,
    delayFeedback: 0.45,
    delayMix: 0.4,
  }),

  preset("fc-pluck-harmonic-ping", "Harmonic Ping", "High harmonic ping pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "harmonic",
    oscAPos: 0.6,
    oscALevel: 0.65,
    filterCutoff: 5500,
    ampAttack: 0.001,
    ampDecay: 0.4,
    ampSustain: 0.08,
    ampRelease: 0.5,
    airHigh: 0.35,
    airAmount: 0.4,
  }),

  preset("fc-pluck-vinyl-scratch", "Vinyl Scratch Pluck", "Lo-fi vinyl-scuffed pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "pulse",
    oscAPos: 0.3,
    oscALevel: 0.7,
    noiseLevel: 0.15,
    filterCutoff: 2000,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.05,
    ampRelease: 0.12,
    cassetteGen: 0.5,
    hiss: 0.25,
  }),

  preset("fc-pluck-formant", "Formant Pluck", "Vowel-shaped formant pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "vocal",
    oscAPos: 0.4,
    oscALevel: 0.7,
    filterCutoff: 2400,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.08,
    ampRelease: 0.2,
  }),

  preset("fc-pluck-wide-chorus", "Wide Chorus Pluck", "Stereo-wide chorused pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "saw",
    oscALevel: 0.65,
    unison: 3,
    unisonDetune: 8,
    unisonWidth: 0.8,
    filterCutoff: 3400,
    ampAttack: 0.001,
    ampDecay: 0.28,
    ampSustain: 0.1,
    ampRelease: 0.25,
    chorusMix: 0.45,
  }),

  preset("fc-pluck-dark-thumb", "Dark Thumb", "Dark thumb-muted pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 900,
    filterResonance: 0.2,
    ampAttack: 0.001,
    ampDecay: 0.3,
    ampSustain: 0.1,
    ampRelease: 0.2,
  }),

  preset("fc-pluck-sparkle", "Sparkle Pluck", "Air and sparkle on a short pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "bell",
    oscALevel: 0.55,
    oscBTable: "pulse",
    oscBLevel: 0.4,
    filterCutoff: 6000,
    ampAttack: 0.001,
    ampDecay: 0.22,
    ampSustain: 0.05,
    ampRelease: 0.3,
    airHigh: 0.5,
    airAmount: 0.55,
    reverbMix: 0.28,
  }),

  preset("fc-pluck-sync-snap", "Sync Snap", "Hard-sync snap pluck", "Pluck", {
    oscATable: "saw",
    oscALevel: 0.72,
    oscBTable: "saw",
    oscBLevel: 0.4,
    oscBOctave: 1,
    filterCutoff: 3800,
    filterEnvAmount: 0.5,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.05,
    ampRelease: 0.12,
  }),

  preset("fc-pluck-warm-decay", "Warm Decay Pluck", "Warm long-decay finger pluck", "Pluck", {
    filterEnvAmount: 0.5,
    oscATable: "basic",
    oscALevel: 0.7,
    filterCutoff: 1800,
    ampAttack: 0.001,
    ampDecay: 0.55,
    ampSustain: 0.12,
    ampRelease: 0.45,
    chorusMix: 0.15,
    reverbMix: 0.2,
  }),


  // ===== PAD (20) =====
  preset("hyperspace", "Hyperspace Pad", "Lush hyperspace pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.7,
    oscBTable: "pulse",
    oscBPos: 0.3,
    oscBLevel: 0.6,
    oscBDetune: 10,
    filterType: "lowpass",
    filterCutoff: 2600,
    filterResonance: 0.3,
    ampAttack: 0.5,
    ampDecay: 0.6,
    ampSustain: 0.8,
    ampRelease: 1,
    unison: 5,
    unisonDetune: 10,
    unisonWidth: 0.7,
    reverbMix: 0.4,
    chorusMix: 0.3
  }),

  preset("fc-pad-cloud-drift", "Cloud Drift", "Slow drifting cloud pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.6,
    oscBTable: "pulse",
    oscBPos: 0.4,
    oscBLevel: 0.45,
    oscBDetune: 10,
    filterCutoff: 2400,
    ampAttack: 0.8,
    ampDecay: 0.6,
    ampSustain: 0.9,
    ampRelease: 1.5,
    unison: 3,
    unisonDetune: 8,
    chorusMix: 0.35,
    reverbMix: 0.45,
  }),

  preset("fc-pad-glass-choir", "Glass Choir", "Glass-choir shimmer pad", "Pad", {
    oscATable: "harmonic",
    oscAPos: 0.45,
    oscALevel: 0.55,
    oscBTable: "bell",
    oscBLevel: 0.35,
    filterCutoff: 4200,
    ampAttack: 0.7,
    ampDecay: 0.5,
    ampSustain: 0.95,
    ampRelease: 1.8,
    chorusMix: 0.3,
    reverbMix: 0.5,
    airHigh: 0.3,
    airAmount: 0.35,
  }),

  preset("fc-pad-dark-ocean", "Dark Ocean", "Deep dark ocean pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.65,
    oscBTable: "saw",
    oscBLevel: 0.4,
    oscBOctave: -1,
    filterCutoff: 900,
    ampAttack: 1,
    ampDecay: 0.8,
    ampSustain: 0.95,
    ampRelease: 2,
    reverbSize: 4.5,
    reverbMix: 0.5,
  }),

  preset("fc-pad-warm-analog", "Warm Analog Wash", "Classic warm analog wash", "Pad", {
    oscATable: "saw",
    oscALevel: 0.65,
    oscBTable: "saw",
    oscBLevel: 0.55,
    oscBDetune: 8,
    filterCutoff: 2000,
    ampAttack: 0.6,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.2,
    unison: 4,
    unisonDetune: 10,
    chorusMix: 0.4,
    cassetteGen: 0.15,
  }),

  preset("fc-pad-vocal-aah", "Vocal Aah", "Soft vocal aah pad", "Pad", {
    oscATable: "vocal",
    oscAPos: 0.35,
    oscALevel: 0.7,
    oscBTable: "vocal",
    oscBPos: 0.55,
    oscBLevel: 0.4,
    oscBDetune: 6,
    filterCutoff: 2600,
    ampAttack: 0.5,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.3,
    reverbMix: 0.4,
  }),

  preset("fc-pad-shimmer-ice", "Shimmer Ice", "Icy shimmer pad with air", "Pad", {
    oscATable: "bell",
    oscALevel: 0.45,
    oscBTable: "harmonic",
    oscBLevel: 0.5,
    filterType: "highpass",
    filterCutoff: 800,
    ampAttack: 0.9,
    ampDecay: 0.6,
    ampSustain: 0.95,
    ampRelease: 2.2,
    reverbMix: 0.55,
    chorusMix: 0.35,
    airHigh: 0.55,
    airAmount: 0.5,
  }),

  preset("fc-pad-pulse-breath", "Pulse Breath", "Breathing pulse-width pad", "Pad", {
    oscATable: "pulse",
    oscAPos: 0.4,
    oscALevel: 0.65,
    filterCutoff: 2800,
    ampAttack: 0.7,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.4,
    lfo1Wave: "sine",
    lfo1Rate: 0.2,
    lfo1Depth: 0.4,
    lfo1Dest: "filter",
    chorusMix: 0.25,
    reverbMix: 0.35,
  }),

  preset("fc-pad-fm-glisten", "FM Glisten", "FM-glistening metallic pad", "Pad", {
    oscATable: "basic",
    oscALevel: 0.55,
    oscBTable: "bell",
    oscBLevel: 0.45,
    fmAmount: 0.35,
    fmRatio: 2,
    filterCutoff: 3600,
    ampAttack: 0.8,
    ampDecay: 0.6,
    ampSustain: 0.9,
    ampRelease: 1.6,
    reverbMix: 0.45,
  }),

  preset("fc-pad-lofi-tape", "Lo-Fi Tape Pad", "Warbly tape-saturated pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.6,
    filterCutoff: 1800,
    ampAttack: 0.7,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.3,
    cassetteGen: 0.55,
    wowFlutter: 0.35,
    hiss: 0.2,
    chorusMix: 0.2,
    reverbMix: 0.3,
  }),

  preset("fc-pad-wide-horizon", "Wide Horizon", "Ultra-wide stereo horizon pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.55,
    oscBTable: "pulse",
    oscBLevel: 0.45,
    unison: 5,
    unisonDetune: 13,
    unisonWidth: 0.95,
    filterCutoff: 3200,
    ampAttack: 0.6,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.5,
    stereoWidth: 1.3,
    chorusMix: 0.35,
    reverbMix: 0.4,
  }),

  preset("fc-pad-drone-hum", "Drone Hum", "Endless low drone hum", "Pad", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "saw",
    oscBLevel: 0.35,
    oscBOctave: -1,
    subLevel: 0.3,
    filterCutoff: 700,
    ampAttack: 1.2,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.5,
    reverbMix: 0.35,
  }),

  preset("fc-pad-phase-mist", "Phase Mist", "Phased misty pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.6,
    filterCutoff: 2500,
    ampAttack: 0.75,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.5,
    phaserRate: 0.15,
    phaserDepth: 0.65,
    phaserMix: 0.5,
    reverbMix: 0.4,
  }),

  preset("fc-pad-night-glow", "Night Glow", "Soft nightglow neon pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.6,
    oscBTable: "harmonic",
    oscBLevel: 0.35,
    filterCutoff: 2100,
    ampAttack: 0.9,
    ampDecay: 0.6,
    ampSustain: 0.95,
    ampRelease: 1.8,
    delayMix: 0.2,
    reverbMix: 0.45,
    chorusMix: 0.3,
  }),

  preset("fc-pad-formant-swarm", "Formant Swarm", "Swarming formant voices", "Pad", {
    oscATable: "vocal",
    oscALevel: 0.55,
    oscBTable: "vocal",
    oscBPos: 0.6,
    oscBLevel: 0.5,
    oscBDetune: 12,
    unison: 3,
    unisonDetune: 10,
    filterCutoff: 2200,
    ampAttack: 0.65,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.4,
    reverbMix: 0.4,
  }),

  preset("fc-pad-crystal-bed", "Crystal Bed", "Crystal bed under chords", "Pad", {
    oscATable: "bell",
    oscALevel: 0.5,
    oscBTable: "harmonic",
    oscBLevel: 0.45,
    filterCutoff: 4800,
    ampAttack: 0.5,
    ampDecay: 0.6,
    ampSustain: 0.85,
    ampRelease: 1.6,
    reverbMix: 0.5,
    delayMix: 0.18,
  }),

  preset("fc-pad-muted-cinema", "Muted Cinema", "Muted cinematic underscore pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.55,
    filterCutoff: 1200,
    ampAttack: 1,
    ampDecay: 0.7,
    ampSustain: 0.95,
    ampRelease: 2,
    reverbSize: 5,
    reverbMix: 0.55,
    stereoWidth: 1.15,
  }),

  preset("fc-pad-lfo-swell", "LFO Swell Pad", "Slow LFO-swelling pad", "Pad", {
    oscATable: "saw",
    oscALevel: 0.6,
    filterCutoff: 2000,
    ampAttack: 0.4,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.4,
    lfo1Wave: "sine",
    lfo1Rate: 0.12,
    lfo1Depth: 0.5,
    lfo1Dest: "filter",
    chorusMix: 0.3,
    reverbMix: 0.4,
  }),

  preset("fc-pad-hollow-pipe", "Hollow Pipe Pad", "Hollow pipe organ pad", "Pad", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.55,
    oscBTable: "pulse",
    oscBPos: 0.25,
    oscBLevel: 0.4,
    oscBOctave: 1,
    filterCutoff: 2800,
    ampAttack: 0.35,
    ampDecay: 0.4,
    ampSustain: 0.9,
    ampRelease: 0.9,
    reverbMix: 0.3,
  }),

  preset("fc-pad-spectral-veil", "Spectral Veil", "Spectral freeze veil pad", "Pad", {
    oscATable: "harmonic",
    oscALevel: 0.55,
    oscBTable: "metallic",
    oscBLevel: 0.35,
    filterCutoff: 2600,
    ampAttack: 0.8,
    ampDecay: 0.6,
    ampSustain: 1,
    ampRelease: 2,
    spectralMode: "freeze",
    spectralAmount: 0.55,
    spectralMix: 0.5,
    reverbMix: 0.4,
  }),


  // ===== KEYS (20) =====
  preset("fc-keys-electric-bell", "Electric Bell Keys", "Electric piano with bell sheen", "Keys", {
    oscATable: "bell",
    oscALevel: 0.55,
    oscBTable: "basic",
    oscBLevel: 0.55,
    filterCutoff: 3200,
    ampAttack: 0.002,
    ampDecay: 0.8,
    ampSustain: 0.35,
    ampRelease: 0.6,
    chorusMix: 0.25,
    reverbMix: 0.2,
  }),

  preset("fc-keys-soft-rhodes", "Soft Rhodes", "Soft Rhodes-style keys", "Keys", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "bell",
    oscBLevel: 0.25,
    filterCutoff: 2400,
    ampAttack: 0.005,
    ampDecay: 1,
    ampSustain: 0.4,
    ampRelease: 0.7,
    chorusMix: 0.35,
    cassetteGen: 0.1,
  }),

  preset("fc-keys-bright-clav", "Bright Clav", "Bright clavinet bite", "Keys", {
    oscATable: "pulse",
    oscAPos: 0.2,
    oscALevel: 0.75,
    filterCutoff: 4500,
    filterResonance: 0.3,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.15,
    ampRelease: 0.15,
    drive: 0.2,
  }),

  preset("fc-keys-organ-drawbar", "Organ Drawbar", "Drawbar organ swell", "Keys", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.5,
    oscBTable: "pulse",
    oscBPos: 0.25,
    oscBLevel: 0.4,
    oscBOctave: 1,
    oscCTable: "basic",
    oscCLevel: 0.3,
    oscCOctave: 2,
    filterCutoff: 4000,
    ampAttack: 0.01,
    ampDecay: 0.2,
    ampSustain: 0.9,
    ampRelease: 0.15,
    chorusMix: 0.2,
  }),

  preset("fc-keys-mellow-piano", "Mellow Piano", "Mellow soft piano keys", "Keys", {
    oscATable: "basic",
    oscALevel: 0.7,
    filterCutoff: 2800,
    ampAttack: 0.002,
    ampDecay: 0.9,
    ampSustain: 0.25,
    ampRelease: 0.5,
    reverbMix: 0.25,
  }),

  preset("fc-keys-harpsi", "Harpsi Pluck Keys", "Harpsichord-like keyed pluck", "Keys", {
    oscATable: "pulse",
    oscAPos: 0.4,
    oscALevel: 0.7,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.1,
    ampRelease: 0.25,
  }),

  preset("fc-keys-wurli-bark", "Wurli Bark", "Barky Wurlitzer keys", "Keys", {
    oscATable: "saw",
    oscALevel: 0.65,
    oscBTable: "pulse",
    oscBPos: 0.3,
    oscBLevel: 0.4,
    filterCutoff: 2200,
    filterResonance: 0.35,
    ampAttack: 0.002,
    ampDecay: 0.7,
    ampSustain: 0.3,
    ampRelease: 0.4,
    drive: 0.3,
    driveMode: "tube",
  }),

  preset("fc-keys-glass-mallet", "Glass Mallet", "Glass mallet keyboard", "Keys", {
    oscATable: "bell",
    oscALevel: 0.7,
    filterCutoff: 5600,
    ampAttack: 0.001,
    ampDecay: 0.6,
    ampSustain: 0.15,
    ampRelease: 0.7,
    reverbMix: 0.35,
    delayMix: 0.15,
  }),

  preset("fc-keys-lofi", "Lo-Fi Keys", "Dusty lo-fi keyboard", "Keys", {
    oscATable: "basic",
    oscALevel: 0.65,
    filterCutoff: 1800,
    ampAttack: 0.005,
    ampDecay: 0.8,
    ampSustain: 0.3,
    ampRelease: 0.5,
    cassetteGen: 0.45,
    wowFlutter: 0.25,
    hiss: 0.2,
    chorusMix: 0.2,
  }),

  preset("fc-keys-bright-ep", "Bright EP Sparkle", "Bright sparkly electric piano", "Keys", {
    oscATable: "bell",
    oscALevel: 0.45,
    oscBTable: "basic",
    oscBLevel: 0.6,
    filterCutoff: 4200,
    ampAttack: 0.002,
    ampDecay: 0.7,
    ampSustain: 0.3,
    ampRelease: 0.55,
    chorusMix: 0.3,
    airHigh: 0.3,
    airAmount: 0.35,
  }),

  preset("fc-keys-pad-bloom", "Pad Keys Bloom", "Keys that bloom into a pad", "Keys", {
    oscATable: "saw",
    oscALevel: 0.55,
    oscBTable: "basic",
    oscBLevel: 0.4,
    filterCutoff: 2600,
    ampAttack: 0.05,
    ampDecay: 0.6,
    ampSustain: 0.7,
    ampRelease: 1.2,
    chorusMix: 0.3,
    reverbMix: 0.4,
  }),

  preset("fc-keys-fm-ep", "Classic FM EP", "Classic FM electric piano", "Keys", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.4,
    fmRatio: 1,
    filterCutoff: 3600,
    ampAttack: 0.002,
    ampDecay: 0.9,
    ampSustain: 0.25,
    ampRelease: 0.55,
    chorusMix: 0.25,
  }),

  preset("fc-keys-church-pipe", "Church Pipe", "Church pipe organ keys", "Keys", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.5,
    oscBTable: "saw",
    oscBLevel: 0.35,
    oscBOctave: 1,
    filterCutoff: 3000,
    ampAttack: 0.08,
    ampDecay: 0.3,
    ampSustain: 0.95,
    ampRelease: 0.4,
    reverbSize: 4,
    reverbMix: 0.45,
  }),

  preset("fc-keys-toy-piano", "Toy Piano", "Tiny toy piano keys", "Keys", {
    oscATable: "bell",
    oscALevel: 0.65,
    oscAOctave: 1,
    filterCutoff: 4800,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.1,
    ampRelease: 0.3,
    reverbMix: 0.2,
  }),

  preset("fc-keys-muted-jazz", "Muted Jazz Keys", "Muted jazz-comp keys", "Keys", {
    oscATable: "basic",
    oscALevel: 0.7,
    filterCutoff: 1600,
    ampAttack: 0.003,
    ampDecay: 0.6,
    ampSustain: 0.35,
    ampRelease: 0.4,
    chorusMix: 0.15,
  }),

  preset("fc-keys-celesta", "Celesta Twinkle", "Celesta twinkle keys", "Keys", {
    oscATable: "bell",
    oscALevel: 0.7,
    oscAOctave: 1,
    filterCutoff: 6000,
    ampAttack: 0.001,
    ampDecay: 0.7,
    ampSustain: 0.1,
    ampRelease: 0.8,
    reverbMix: 0.4,
  }),

  preset("fc-keys-house-stab", "House Stab Keys", "Classic house chord stab", "Keys", {
    oscATable: "saw",
    oscALevel: 0.65,
    oscBTable: "saw",
    oscBLevel: 0.45,
    oscBDetune: 5,
    filterCutoff: 3800,
    filterEnvAmount: 0.4,
    filtDecay: 0.25,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.4,
    ampRelease: 0.25,
    delayMix: 0.15,
  }),

  preset("fc-keys-warm-comp", "Warm Comp Keys", "Warm companion keys for ballads", "Keys", {
    oscATable: "saw",
    oscALevel: 0.6,
    oscBTable: "basic",
    oscBLevel: 0.4,
    filterCutoff: 2000,
    ampAttack: 0.01,
    ampDecay: 0.7,
    ampSustain: 0.5,
    ampRelease: 0.6,
    chorusMix: 0.2,
    reverbMix: 0.25,
  }),

  preset("fc-keys-percussive", "Percussive Keys", "Percussive short key hits", "Keys", {
    oscATable: "pulse",
    oscAPos: 0.35,
    oscALevel: 0.75,
    filterCutoff: 3400,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.05,
    ampRelease: 0.12,
    punch: 0.35,
  }),

  preset("fc-keys-dream-ep", "Dream EP", "Dreamy washed electric piano", "Keys", {
    oscATable: "bell",
    oscALevel: 0.5,
    oscBTable: "basic",
    oscBLevel: 0.5,
    filterCutoff: 2800,
    ampAttack: 0.01,
    ampDecay: 1,
    ampSustain: 0.45,
    ampRelease: 1,
    chorusMix: 0.4,
    reverbMix: 0.45,
    delayMix: 0.2,
  }),


  // ===== ARP (20) =====
  preset("fc-arp-crystal-up", "Crystal Up Arp", "Bright crystal ascending arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "bell",
    oscALevel: 0.65,
    filterCutoff: 5200,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.15,
    ampRelease: 0.15,
    delayMix: 0.25,
    reverbMix: 0.2,
  }, { enabled: true, mode: "up", bpm: 128, division: "1/16", octaves: 2, gate: 0.65 }),

  preset("fc-arp-saw-cascade", "Saw Cascade", "Cascading saw arp waterfall", "Arp", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 3600,
    filterEnvAmount: 0.4,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.2,
    ampRelease: 0.12,
    delayMix: 0.2,
  }, { enabled: true, mode: "updown", bpm: 120, division: "1/16", octaves: 3, gate: 0.55 }),

  preset("fc-arp-pluck-rain", "Pluck Rain", "Raindrop pluck arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "pulse",
    oscAPos: 0.4,
    oscALevel: 0.65,
    filterCutoff: 3000,
    ampAttack: 0.001,
    ampDecay: 0.22,
    ampSustain: 0.08,
    ampRelease: 0.18,
    reverbMix: 0.3,
  }, { enabled: true, mode: "random", bpm: 110, division: "1/16", octaves: 2, gate: 0.5 }),

  preset("fc-arp-trance-drive", "Trance Drive Arp", "Driving trance arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "saw",
    oscALevel: 0.7,
    unison: 3,
    unisonDetune: 8,
    filterCutoff: 4200,
    ampAttack: 0.001,
    ampDecay: 0.15,
    ampSustain: 0.25,
    ampRelease: 0.1,
    delayTime: 0.375,
    delayMix: 0.28,
  }, { enabled: true, mode: "up", bpm: 138, division: "1/16", octaves: 2, gate: 0.7 }),

  preset("fc-arp-chip-run", "Chip Run", "Fast chip-tune run", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "pulse",
    oscAPos: 0.5,
    pulseDuty: 0.5,
    oscALevel: 0.75,
    filterCutoff: 5500,
    ampAttack: 0.001,
    ampDecay: 0.12,
    ampSustain: 0.15,
    ampRelease: 0.08,
  }, { enabled: true, mode: "up", bpm: 150, division: "1/32", octaves: 3, gate: 0.8 }),

  preset("fc-arp-soft-lullaby", "Soft Lullaby Arp", "Soft lullaby rolling arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "basic",
    oscALevel: 0.6,
    filterCutoff: 2200,
    ampAttack: 0.01,
    ampDecay: 0.3,
    ampSustain: 0.3,
    ampRelease: 0.35,
    chorusMix: 0.25,
    reverbMix: 0.35,
  }, { enabled: true, mode: "updown", bpm: 90, division: "1/8", octaves: 2, gate: 0.7 }),

  preset("fc-arp-acid-steps", "Acid Steps", "Acid filter-step arp", "Arp", {
    oscATable: "saw",
    oscALevel: 0.75,
    filterCutoff: 700,
    filterResonance: 0.78,
    filterEnvAmount: 0.85,
    filtDecay: 0.2,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.4,
    ampRelease: 0.1,
    mono: true,
  }, { enabled: true, mode: "up", bpm: 125, division: "1/16", octaves: 1, gate: 0.6 }),

  preset("fc-arp-glass-ladder", "Glass Ladder", "Glass ladder ascending arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "bell",
    oscALevel: 0.6,
    oscBTable: "harmonic",
    oscBLevel: 0.35,
    filterCutoff: 4800,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.15,
    ampRelease: 0.3,
    reverbMix: 0.35,
  }, { enabled: true, mode: "up", bpm: 100, division: "1/8", octaves: 3, gate: 0.55 }),

  preset("fc-arp-pulse-machine", "Pulse Machine", "Mechanical pulse arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "pulse",
    oscAPos: 0.25,
    oscALevel: 0.7,
    filterCutoff: 2800,
    ampAttack: 0.001,
    ampDecay: 0.15,
    ampSustain: 0.2,
    ampRelease: 0.1,
    punch: 0.25,
  }, { enabled: true, mode: "down", bpm: 130, division: "1/16", octaves: 2, gate: 0.75 }),

  preset("fc-arp-echo-garden", "Echo Garden", "Garden of delayed arp echoes", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "saw",
    oscALevel: 0.55,
    filterCutoff: 3200,
    ampAttack: 0.005,
    ampDecay: 0.25,
    ampSustain: 0.2,
    ampRelease: 0.4,
    delayTime: 0.5,
    delayFeedback: 0.55,
    delayMix: 0.45,
    reverbMix: 0.3,
  }, { enabled: true, mode: "updown", bpm: 105, division: "1/8", octaves: 2, gate: 0.5 }),

  preset("fc-arp-bass-gallop", "Bass Gallop Arp", "Galloping bass arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "saw",
    oscALevel: 0.75,
    oscAOctave: -1,
    subLevel: 0.3,
    filterCutoff: 1200,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.25,
    ampRelease: 0.1,
    mono: true,
  }, { enabled: true, mode: "up", bpm: 128, division: "1/16", octaves: 1, gate: 0.55 }),

  preset("fc-arp-vocal-chatter", "Vocal Chatter Arp", "Chattering vocal formant arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "vocal",
    oscAPos: 0.4,
    oscALevel: 0.65,
    filterCutoff: 2400,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.2,
    ampRelease: 0.15,
  }, { enabled: true, mode: "random", bpm: 115, division: "1/16", octaves: 2, gate: 0.6 }),

  preset("fc-arp-wide-sparkle", "Wide Sparkle Arp", "Wide sparkling unison arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "saw",
    oscALevel: 0.55,
    unison: 4,
    unisonDetune: 10,
    unisonWidth: 0.85,
    filterCutoff: 4000,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.2,
    ampRelease: 0.15,
    chorusMix: 0.3,
    reverbMix: 0.25,
  }, { enabled: true, mode: "up", bpm: 120, division: "1/16", octaves: 2, gate: 0.65 }),

  preset("fc-arp-lofi-steps", "Lo-Fi Steps", "Wobbly lo-fi arp steps", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "pulse",
    oscAPos: 0.35,
    oscALevel: 0.65,
    filterCutoff: 2000,
    ampAttack: 0.002,
    ampDecay: 0.22,
    ampSustain: 0.2,
    ampRelease: 0.18,
    cassetteGen: 0.4,
    wowFlutter: 0.3,
    hiss: 0.15,
  }, { enabled: true, mode: "updown", bpm: 95, division: "1/8", octaves: 2, gate: 0.6 }),

  preset("fc-arp-fm-bells", "FM Bell Arp", "FM bell cascading arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "bell",
    oscALevel: 0.6,
    oscBTable: "basic",
    oscBLevel: 0.45,
    fmAmount: 0.45,
    fmRatio: 3,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 0.3,
    ampSustain: 0.15,
    ampRelease: 0.25,
    reverbMix: 0.3,
  }, { enabled: true, mode: "up", bpm: 110, division: "1/16", octaves: 2, gate: 0.55 }),

  preset("fc-arp-dark-crawl", "Dark Crawl Arp", "Dark crawling low arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 800,
    filterResonance: 0.4,
    ampAttack: 0.005,
    ampDecay: 0.25,
    ampSustain: 0.3,
    ampRelease: 0.2,
  }, { enabled: true, mode: "down", bpm: 100, division: "1/8", octaves: 2, gate: 0.7 }),

  preset("fc-arp-staccato-laser", "Staccato Laser", "Staccato laser zap arp", "Arp", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 4500,
    filterEnvAmount: 0.6,
    filtDecay: 0.08,
    ampAttack: 0.001,
    ampDecay: 0.1,
    ampSustain: 0.05,
    ampRelease: 0.08,
  }, { enabled: true, mode: "up", bpm: 140, division: "1/16", octaves: 2, gate: 0.4 }),

  preset("fc-arp-warm-circle", "Warm Circle Arp", "Warm circling arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "basic",
    oscALevel: 0.65,
    oscBTable: "saw",
    oscBLevel: 0.35,
    oscBDetune: 5,
    filterCutoff: 2400,
    ampAttack: 0.01,
    ampDecay: 0.3,
    ampSustain: 0.35,
    ampRelease: 0.3,
    chorusMix: 0.2,
    reverbMix: 0.25,
  }, { enabled: true, mode: "updown", bpm: 108, division: "1/8", octaves: 2, gate: 0.7 }),

  preset("fc-arp-noise-sparkle", "Noise Sparkle Arp", "Noise-kissed sparkle arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "bell",
    oscALevel: 0.5,
    noiseLevel: 0.2,
    filterType: "highpass",
    filterCutoff: 2000,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.1,
    ampRelease: 0.2,
    reverbMix: 0.3,
  }, { enabled: true, mode: "random", bpm: 120, division: "1/16", octaves: 2, gate: 0.5 }),

  preset("fc-arp-octave-bounce", "Octave Bounce", "Octave-bouncing playful arp", "Arp", {
    filterEnvAmount: 0.35,
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.7,
    filterCutoff: 3400,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.2,
    ampRelease: 0.12,
  }, { enabled: true, mode: "updown", bpm: 125, division: "1/16", octaves: 3, gate: 0.65 }),


  // ===== FX (20) =====
  preset("fc-fx-noise-sweep", "Noise Sweep Riser", "Filtered noise sweep riser", "FX", {
    oscATable: "saw",
    oscALevel: 0.3,
    noiseLevel: 0.7,
    filterType: "bandpass",
    filterCutoff: 800,
    filterResonance: 0.4,
    ampAttack: 0.8,
    ampDecay: 0.5,
    ampSustain: 0.8,
    ampRelease: 0.8,
    lfo1Wave: "sawtooth",
    lfo1Rate: 0.15,
    lfo1Depth: 0.7,
    lfo1Dest: "filter",
  }),

  preset("fc-fx-laser-zap", "Laser Zap", "Classic laser zap FX", "FX", {
    oscATable: "saw",
    oscALevel: 0.8,
    filterCutoff: 5000,
    filterEnvAmount: 0.9,
    filtDecay: 0.15,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.05,
    ampRelease: 0.15,
    pitchEnvAmount: 0.6,
    pitchEnvTime: 0.2,
  }),

  preset("fc-fx-impact-boom", "Impact Boom", "Cinematic impact boom", "FX", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscAOctave: -2,
    noiseLevel: 0.4,
    subLevel: 0.5,
    filterCutoff: 400,
    ampAttack: 0.001,
    ampDecay: 0.8,
    ampSustain: 0.1,
    ampRelease: 0.9,
    reverbMix: 0.45,
    punch: 0.6,
  }),

  preset("fc-fx-whoosh", "Air Whoosh", "Air whoosh pass-by", "FX", {
    oscALevel: 0.2,
    noiseLevel: 0.8,
    filterType: "bandpass",
    filterCutoff: 2000,
    filterResonance: 0.3,
    ampAttack: 0.15,
    ampDecay: 0.6,
    ampSustain: 0.3,
    ampRelease: 0.7,
    stereoWidth: 1.3,
    lfo1Rate: 0.4,
    lfo1Depth: 0.5,
    lfo1Dest: "pan",
  }),

  preset("fc-fx-glitch-stutter", "Glitch Stutter", "Glitchy stutter FX", "FX", {
    oscATable: "pulse",
    oscAPos: 0.3,
    oscALevel: 0.65,
    noiseLevel: 0.25,
    filterCutoff: 3000,
    ampAttack: 0.001,
    ampDecay: 0.08,
    ampSustain: 0.2,
    ampRelease: 0.08,
    gateOn: true,
    gateRate: 16,
    gateDepth: 1,
    drive: 0.3,
  }),

  preset("fc-fx-alarm-pulse", "Alarm Pulse", "Alarm pulse siren", "FX", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.75,
    filterCutoff: 2800,
    ampAttack: 0.01,
    ampDecay: 0.2,
    ampSustain: 0.8,
    ampRelease: 0.2,
    lfo1Wave: "square",
    lfo1Rate: 6,
    lfo1Depth: 0.6,
    lfo1Dest: "pitch",
  }),

  preset("fc-fx-reverse-swell", "Reverse Swell", "Reverse-like swell FX", "FX", {
    oscATable: "saw",
    oscALevel: 0.55,
    noiseLevel: 0.3,
    filterCutoff: 1800,
    ampAttack: 1.2,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.2,
    reverbMix: 0.5,
  }),

  preset("fc-fx-metallic-hit", "Metallic Hit", "Metallic industrial hit", "FX", {
    oscATable: "metallic",
    oscALevel: 0.7,
    oscBTable: "bell",
    oscBLevel: 0.4,
    fmAmount: 0.4,
    filterCutoff: 4000,
    ampAttack: 0.001,
    ampDecay: 0.4,
    ampSustain: 0.05,
    ampRelease: 0.5,
    reverbMix: 0.3,
    drive: 0.25,
  }),

  preset("fc-fx-sub-drop", "Sub Drop", "Falling sub drop FX", "FX", {
    oscATable: "basic",
    oscALevel: 0.8,
    oscAOctave: -2,
    subLevel: 0.6,
    filterCutoff: 500,
    ampAttack: 0.01,
    ampDecay: 0.9,
    ampSustain: 0.2,
    ampRelease: 0.6,
    pitchEnvAmount: -0.7,
    pitchEnvTime: 0.8,
  }),

  preset("fc-fx-bitcrush-rain", "Bitcrush Rain", "Bitcrushed rain texture", "FX", {
    noiseLevel: 0.7,
    oscALevel: 0.2,
    filterType: "highpass",
    filterCutoff: 2500,
    ampAttack: 0.3,
    ampDecay: 0.5,
    ampSustain: 0.8,
    ampRelease: 0.8,
    cassetteGen: 0.6,
    hiss: 0.4,
  }),

  preset("fc-fx-phone-ring", "Phone Ring Tone", "Retro phone ring tone", "FX", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.5,
    oscBDetune: 2,
    filterCutoff: 3000,
    ampAttack: 0.001,
    ampDecay: 0.15,
    ampSustain: 0.7,
    ampRelease: 0.1,
    lfo1Wave: "square",
    lfo1Rate: 5,
    lfo1Depth: 0.4,
    lfo1Dest: "volume",
  }),

  preset("fc-fx-wind-howl", "Wind Howl", "Howling wind texture", "FX", {
    noiseLevel: 0.85,
    oscALevel: 0.15,
    filterType: "bandpass",
    filterCutoff: 900,
    filterResonance: 0.5,
    ampAttack: 0.5,
    ampDecay: 0.6,
    ampSustain: 0.9,
    ampRelease: 1.2,
    lfo1Rate: 0.25,
    lfo1Depth: 0.55,
    lfo1Dest: "filter",
    reverbMix: 0.4,
  }),

  preset("fc-fx-sparkle-burst", "Sparkle Burst", "Short sparkle burst FX", "FX", {
    oscATable: "bell",
    oscALevel: 0.6,
    noiseLevel: 0.2,
    filterCutoff: 6000,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.05,
    ampRelease: 0.5,
    reverbMix: 0.4,
    delayMix: 0.2,
  }),

  preset("fc-fx-drone-horror", "Horror Drone", "Uneasy horror drone FX", "FX", {
    oscATable: "saw",
    oscALevel: 0.5,
    oscBTable: "saw",
    oscBLevel: 0.45,
    oscBDetune: 20,
    filterCutoff: 600,
    ampAttack: 1,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2,
    lfo1Rate: 0.08,
    lfo1Depth: 0.4,
    lfo1Dest: "pitch",
    reverbMix: 0.45,
  }),

  preset("fc-fx-tape-stop", "Tape Stop", "Tape-stop pitch dive", "FX", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 2800,
    ampAttack: 0.01,
    ampDecay: 0.5,
    ampSustain: 0.6,
    ampRelease: 0.8,
    pitchEnvAmount: -0.9,
    pitchEnvTime: 0.6,
    cassetteGen: 0.5,
    wowFlutter: 0.4,
  }),

  preset("fc-fx-radio-static", "Radio Static", "Tuned radio static FX", "FX", {
    noiseLevel: 0.8,
    oscATable: "pulse",
    oscALevel: 0.25,
    filterType: "bandpass",
    filterCutoff: 1600,
    filterResonance: 0.6,
    ampAttack: 0.05,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.4,
    hiss: 0.5,
    cassetteGen: 0.3,
  }),

  preset("fc-fx-power-down", "Power Down", "Machine power-down FX", "FX", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 3500,
    ampAttack: 0.001,
    ampDecay: 1,
    ampSustain: 0.1,
    ampRelease: 0.5,
    pitchEnvAmount: -0.8,
    pitchEnvTime: 1,
    lfo1Rate: 8,
    lfo1Depth: 0.3,
    lfo1Dest: "filter",
  }),

  preset("fc-fx-crystal-shatter", "Crystal Shatter", "Shattering crystal FX", "FX", {
    oscATable: "bell",
    oscALevel: 0.55,
    oscBTable: "metallic",
    oscBLevel: 0.45,
    noiseLevel: 0.25,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 0.5,
    ampSustain: 0.05,
    ampRelease: 0.7,
    reverbMix: 0.45,
  }),

  preset("fc-fx-heartbeat", "Heartbeat Pulse", "Deep heartbeat pulse FX", "FX", {
    oscATable: "basic",
    oscALevel: 0.8,
    oscAOctave: -2,
    subLevel: 0.5,
    filterCutoff: 300,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.05,
    ampRelease: 0.3,
    punch: 0.7,
  }),

  preset("fc-fx-space-chirp", "Space Chirp", "Sci-fi space chirp", "FX", {
    oscATable: "basic",
    oscALevel: 0.65,
    oscAOctave: 2,
    filterCutoff: 4500,
    ampAttack: 0.001,
    ampDecay: 0.3,
    ampSustain: 0.2,
    ampRelease: 0.4,
    pitchEnvAmount: 0.5,
    pitchEnvTime: 0.25,
    delayMix: 0.3,
    reverbMix: 0.35,
  }),


  // ===== ATMOS (20) =====
  preset("fc-atmos-fog-bank", "Fog Bank", "Thick fog bank atmosphere", "Atmos", {
    oscATable: "saw",
    oscALevel: 0.4,
    noiseLevel: 0.35,
    filterCutoff: 900,
    ampAttack: 1.5,
    ampDecay: 1,
    ampSustain: 1,
    ampRelease: 3,
    reverbSize: 5,
    reverbMix: 0.6,
    chorusMix: 0.3,
  }),

  preset("fc-atmos-starfield", "Starfield", "Twinkling starfield bed", "Atmos", {
    oscATable: "bell",
    oscALevel: 0.35,
    oscBTable: "harmonic",
    oscBLevel: 0.4,
    noiseLevel: 0.15,
    filterCutoff: 4000,
    ampAttack: 1.2,
    ampDecay: 0.8,
    ampSustain: 0.95,
    ampRelease: 2.5,
    reverbMix: 0.55,
    delayMix: 0.25,
    airHigh: 0.4,
    airAmount: 0.4,
  }),

  preset("fc-atmos-underwater", "Underwater Room", "Muffled underwater room", "Atmos", {
    oscATable: "basic",
    oscALevel: 0.5,
    filterCutoff: 600,
    filterResonance: 0.3,
    ampAttack: 1,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.2,
    reverbMix: 0.5,
    chorusMix: 0.4,
    lfo1Rate: 0.15,
    lfo1Depth: 0.3,
    lfo1Dest: "filter",
  }),

  preset("fc-atmos-city-hum", "City Hum", "Distant city electrical hum", "Atmos", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.35,
    oscBTable: "saw",
    oscBLevel: 0.25,
    oscBDetune: 15,
    noiseLevel: 0.2,
    filterCutoff: 700,
    ampAttack: 1,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2,
    cassetteGen: 0.25,
    hiss: 0.15,
  }),

  preset("fc-atmos-aurora", "Aurora Veil", "Aurora veil shimmer", "Atmos", {
    oscATable: "harmonic",
    oscALevel: 0.45,
    oscBTable: "bell",
    oscBLevel: 0.35,
    filterCutoff: 3200,
    ampAttack: 1.4,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.8,
    phaserRate: 0.1,
    phaserDepth: 0.6,
    phaserMix: 0.4,
    reverbMix: 0.55,
  }),

  preset("fc-atmos-cave-drip", "Cave Drip", "Damp cave with distant drips", "Atmos", {
    oscATable: "basic",
    oscALevel: 0.3,
    noiseLevel: 0.25,
    filterCutoff: 1200,
    ampAttack: 0.8,
    ampDecay: 0.6,
    ampSustain: 0.9,
    ampRelease: 2,
    reverbSize: 6,
    reverbMix: 0.65,
    delayMix: 0.3,
  }),

  preset("fc-atmos-radio-space", "Radio Space", "Deep-space radio wash", "Atmos", {
    noiseLevel: 0.5,
    oscATable: "pulse",
    oscALevel: 0.25,
    filterType: "bandpass",
    filterCutoff: 1400,
    filterResonance: 0.4,
    ampAttack: 1,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.5,
    hiss: 0.35,
    reverbMix: 0.5,
  }),

  preset("fc-atmos-warm-dust", "Warm Dust", "Warm dusty loft atmosphere", "Atmos", {
    oscATable: "saw",
    oscALevel: 0.4,
    filterCutoff: 1400,
    ampAttack: 1.2,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.2,
    cassetteGen: 0.4,
    wowFlutter: 0.2,
    hiss: 0.2,
    chorusMix: 0.25,
    reverbMix: 0.4,
  }),

  preset("fc-atmos-ice-field", "Ice Field", "Frozen ice field texture", "Atmos", {
    oscATable: "bell",
    oscALevel: 0.35,
    noiseLevel: 0.3,
    filterType: "highpass",
    filterCutoff: 1500,
    ampAttack: 1.3,
    ampDecay: 0.8,
    ampSustain: 0.95,
    ampRelease: 2.5,
    reverbMix: 0.55,
    airHigh: 0.5,
    airAmount: 0.45,
  }),

  preset("fc-atmos-pulse-engine", "Pulse Engine Room", "Slow pulse engine room", "Atmos", {
    oscATable: "saw",
    oscALevel: 0.45,
    subLevel: 0.3,
    filterCutoff: 500,
    ampAttack: 0.8,
    ampDecay: 0.6,
    ampSustain: 1,
    ampRelease: 1.8,
    lfo1Rate: 0.5,
    lfo1Depth: 0.45,
    lfo1Dest: "volume",
    reverbMix: 0.35,
  }),

  preset("fc-atmos-choir-void", "Choir Void", "Distant choir in the void", "Atmos", {
    oscATable: "vocal",
    oscALevel: 0.45,
    oscBTable: "vocal",
    oscBPos: 0.6,
    oscBLevel: 0.35,
    oscBDetune: 10,
    filterCutoff: 2000,
    ampAttack: 1.5,
    ampDecay: 1,
    ampSustain: 1,
    ampRelease: 3,
    reverbSize: 5.5,
    reverbMix: 0.6,
  }),

  preset("fc-atmos-neon-rain", "Neon Rain", "Neon rain on glass", "Atmos", {
    oscATable: "pulse",
    oscAPos: 0.3,
    oscALevel: 0.35,
    noiseLevel: 0.35,
    filterCutoff: 2800,
    ampAttack: 0.9,
    ampDecay: 0.7,
    ampSustain: 0.9,
    ampRelease: 2,
    delayMix: 0.35,
    reverbMix: 0.45,
    phaserMix: 0.25,
  }),

  preset("fc-atmos-granular-ash", "Granular Ash", "Granular ash cloud", "Atmos", {
    oscATable: "metallic",
    oscALevel: 0.35,
    noiseLevel: 0.4,
    filterCutoff: 1600,
    ampAttack: 1.1,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.4,
    spectralMode: "freeze",
    spectralAmount: 0.4,
    spectralMix: 0.45,
    reverbMix: 0.5,
  }),

  preset("fc-atmos-soft-pad-air", "Soft Pad Air", "Soft airy pad atmosphere", "Atmos", {
    oscATable: "saw",
    oscALevel: 0.45,
    oscBTable: "basic",
    oscBLevel: 0.35,
    filterCutoff: 2600,
    ampAttack: 1,
    ampDecay: 0.7,
    ampSustain: 0.95,
    ampRelease: 2,
    chorusMix: 0.35,
    reverbMix: 0.5,
    airHigh: 0.35,
    airAmount: 0.4,
  }),

  preset("fc-atmos-machine-breath", "Machine Breath", "Breathing machine atmosphere", "Atmos", {
    oscATable: "saw",
    oscALevel: 0.4,
    noiseLevel: 0.3,
    filterCutoff: 1100,
    ampAttack: 0.6,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.5,
    lfo1Rate: 0.2,
    lfo1Depth: 0.5,
    lfo1Dest: "filter",
    cassetteGen: 0.2,
  }),

  preset("fc-atmos-moonlit", "Moonlit Field", "Moonlit open field", "Atmos", {
    oscATable: "harmonic",
    oscALevel: 0.4,
    oscBTable: "basic",
    oscBLevel: 0.3,
    filterCutoff: 2400,
    ampAttack: 1.3,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.6,
    chorusMix: 0.3,
    reverbMix: 0.55,
    delayMix: 0.2,
  }),

  preset("fc-atmos-static-veil", "Static Veil", "Static electricity veil", "Atmos", {
    noiseLevel: 0.65,
    oscALevel: 0.2,
    filterType: "highpass",
    filterCutoff: 3000,
    ampAttack: 0.7,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.8,
    hiss: 0.45,
    reverbMix: 0.35,
  }),

  preset("fc-atmos-deep-abyss", "Deep Abyss", "Bottomless deep abyss", "Atmos", {
    oscATable: "saw",
    oscALevel: 0.5,
    oscAOctave: -1,
    subLevel: 0.4,
    filterCutoff: 350,
    ampAttack: 1.6,
    ampDecay: 1,
    ampSustain: 1,
    ampRelease: 3.5,
    reverbMix: 0.55,
  }),

  preset("fc-atmos-glitter-dust", "Glitter Dust", "Floating glitter dust", "Atmos", {
    oscATable: "bell",
    oscALevel: 0.35,
    oscBTable: "harmonic",
    oscBLevel: 0.3,
    noiseLevel: 0.15,
    filterCutoff: 5000,
    ampAttack: 1,
    ampDecay: 0.7,
    ampSustain: 0.9,
    ampRelease: 2.2,
    delayMix: 0.3,
    reverbMix: 0.5,
    airHigh: 0.45,
    airAmount: 0.5,
  }),

  preset("fc-atmos-hollow-hall", "Hollow Hall", "Hollow hall resonance", "Atmos", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.4,
    filterCutoff: 1500,
    ampAttack: 1.1,
    ampDecay: 0.8,
    ampSustain: 1,
    ampRelease: 2.5,
    reverbSize: 6,
    reverbMix: 0.65,
    phaserMix: 0.3,
  }),


  // ===== VINTAGE (20) =====
  preset("fc-vintage-cassette-lead", "Cassette Lead Warmth", "Warm cassette-saturated lead", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 2200,
    ampAttack: 0.02,
    ampDecay: 0.3,
    ampSustain: 0.75,
    ampRelease: 0.3,
    cassetteGen: 0.55,
    wowFlutter: 0.25,
    hiss: 0.2,
    mono: true,
  }),

  preset("fc-vintage-vhs-pad", "VHS Pad Glow", "VHS-colored glowing pad", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.55,
    oscBTable: "pulse",
    oscBLevel: 0.4,
    filterCutoff: 2000,
    ampAttack: 0.7,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.4,
    cassetteGen: 0.45,
    wowFlutter: 0.35,
    hiss: 0.25,
    chorusMix: 0.3,
    reverbMix: 0.35,
  }),

  preset("fc-vintage-radio-keys", "AM Radio Keys", "AM-radio filtered keys", "Vintage", {
    oscATable: "basic",
    oscALevel: 0.65,
    filterType: "bandpass",
    filterCutoff: 1600,
    filterResonance: 0.4,
    ampAttack: 0.005,
    ampDecay: 0.7,
    ampSustain: 0.35,
    ampRelease: 0.5,
    cassetteGen: 0.35,
    hiss: 0.3,
  }),

  preset("fc-vintage-tape-bass", "Tape Bass Thump", "Tape-saturated bass thump", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.75,
    oscAOctave: -1,
    subLevel: 0.35,
    filterCutoff: 900,
    ampAttack: 0.005,
    ampDecay: 0.4,
    ampSustain: 0.5,
    ampRelease: 0.3,
    cassetteGen: 0.5,
    wowFlutter: 0.15,
    mono: true,
  }),

  preset("fc-vintage-vinyl-ep", "Vinyl EP Crackle", "Vinyl-crackled electric piano", "Vintage", {
    oscATable: "bell",
    oscALevel: 0.45,
    oscBTable: "basic",
    oscBLevel: 0.5,
    noiseLevel: 0.12,
    filterCutoff: 2600,
    ampAttack: 0.003,
    ampDecay: 0.9,
    ampSustain: 0.3,
    ampRelease: 0.6,
    cassetteGen: 0.4,
    hiss: 0.35,
    chorusMix: 0.25,
  }),

  preset("fc-vintage-warble-organ", "Warble Organ", "Wow/flutter warbling organ", "Vintage", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.5,
    oscBTable: "pulse",
    oscBPos: 0.25,
    oscBLevel: 0.4,
    oscBOctave: 1,
    filterCutoff: 3000,
    ampAttack: 0.02,
    ampDecay: 0.2,
    ampSustain: 0.9,
    ampRelease: 0.2,
    wowFlutter: 0.5,
    cassetteGen: 0.3,
  }),

  preset("fc-vintage-dusty-pluck", "Dusty Pluck", "Dusty aged pluck", "Vintage", {
    oscATable: "pulse",
    oscAPos: 0.35,
    oscALevel: 0.7,
    filterCutoff: 2400,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.08,
    ampRelease: 0.2,
    cassetteGen: 0.5,
    hiss: 0.25,
  }),

  preset("fc-vintage-boombox", "Boombox Bass", "Portable boombox bass", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.7,
    subLevel: 0.4,
    filterCutoff: 1100,
    ampAttack: 0.01,
    ampDecay: 0.35,
    ampSustain: 0.55,
    ampRelease: 0.25,
    cassetteGen: 0.4,
    drive: 0.25,
    mono: true,
  }),

  preset("fc-vintage-film-score", "Film Score Strings", "Aged film-score string pad", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.55,
    oscBTable: "saw",
    oscBLevel: 0.45,
    oscBDetune: 10,
    filterCutoff: 1800,
    ampAttack: 0.8,
    ampDecay: 0.6,
    ampSustain: 0.9,
    ampRelease: 1.6,
    cassetteGen: 0.35,
    wowFlutter: 0.2,
    reverbMix: 0.45,
  }),

  preset("fc-vintage-chatty-radio", "Chatty Radio", "Chatty talk-radio texture", "Vintage", {
    oscATable: "vocal",
    oscAPos: 0.4,
    oscALevel: 0.55,
    noiseLevel: 0.2,
    filterType: "bandpass",
    filterCutoff: 1800,
    ampAttack: 0.1,
    ampDecay: 0.4,
    ampSustain: 0.7,
    ampRelease: 0.4,
    hiss: 0.4,
    cassetteGen: 0.3,
  }),

  preset("fc-vintage-soft-synth", "Soft 80s Synth", "Soft 80s synth poly", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.6,
    oscBTable: "pulse",
    oscBLevel: 0.4,
    filterCutoff: 2800,
    ampAttack: 0.05,
    ampDecay: 0.4,
    ampSustain: 0.75,
    ampRelease: 0.5,
    chorusMix: 0.4,
    cassetteGen: 0.2,
    reverbMix: 0.25,
  }),

  preset("fc-vintage-broken-speaker", "Broken Speaker", "Broken speaker grit", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.7,
    filterCutoff: 1600,
    ampAttack: 0.01,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.25,
    drive: 0.55,
    cassetteGen: 0.45,
    hiss: 0.3,
    mono: true,
  }),

  preset("fc-vintage-lullaby-box", "Lullaby Music Box", "Aged music-box lullaby", "Vintage", {
    oscATable: "bell",
    oscALevel: 0.65,
    oscAOctave: 1,
    filterCutoff: 4000,
    ampAttack: 0.001,
    ampDecay: 0.5,
    ampSustain: 0.1,
    ampRelease: 0.6,
    wowFlutter: 0.3,
    cassetteGen: 0.25,
    reverbMix: 0.3,
  }),

  preset("fc-vintage-garage-band", "Garage Band Keys", "Garage-band keyboard", "Vintage", {
    oscATable: "basic",
    oscALevel: 0.65,
    filterCutoff: 2200,
    ampAttack: 0.005,
    ampDecay: 0.6,
    ampSustain: 0.4,
    ampRelease: 0.4,
    cassetteGen: 0.4,
    drive: 0.2,
    chorusMix: 0.15,
  }),

  preset("fc-vintage-night-drive", "Night Drive Pad", "Night-drive neon pad", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.55,
    oscBTable: "saw",
    oscBLevel: 0.4,
    oscBDetune: 8,
    filterCutoff: 2400,
    ampAttack: 0.6,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.3,
    chorusMix: 0.35,
    cassetteGen: 0.25,
    delayMix: 0.2,
    reverbMix: 0.35,
  }),

  preset("fc-vintage-shortwave", "Shortwave Ghost", "Shortwave ghost signal", "Vintage", {
    oscATable: "pulse",
    oscAPos: 0.4,
    oscALevel: 0.4,
    noiseLevel: 0.35,
    filterType: "bandpass",
    filterCutoff: 1200,
    filterResonance: 0.5,
    ampAttack: 0.4,
    ampDecay: 0.5,
    ampSustain: 0.8,
    ampRelease: 1,
    hiss: 0.45,
    wowFlutter: 0.4,
  }),

  preset("fc-vintage-analog-brass", "Analog Brass", "Vintage analog brass", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.65,
    oscBTable: "saw",
    oscBLevel: 0.5,
    oscBDetune: 6,
    filterCutoff: 2000,
    filterResonance: 0.25,
    filterEnvAmount: 0.4,
    ampAttack: 0.08,
    ampDecay: 0.35,
    ampSustain: 0.75,
    ampRelease: 0.35,
    cassetteGen: 0.2,
  }),

  preset("fc-vintage-faded-photo", "Faded Photo Pad", "Faded photograph soft pad", "Vintage", {
    oscATable: "basic",
    oscALevel: 0.5,
    oscBTable: "saw",
    oscBLevel: 0.35,
    filterCutoff: 1600,
    ampAttack: 0.9,
    ampDecay: 0.6,
    ampSustain: 0.95,
    ampRelease: 1.8,
    cassetteGen: 0.5,
    wowFlutter: 0.25,
    hiss: 0.2,
    reverbMix: 0.4,
  }),

  preset("fc-vintage-arcade-lobby", "Arcade Lobby", "80s arcade lobby ambience", "Vintage", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.4,
    oscBTable: "basic",
    oscBLevel: 0.3,
    oscBOctave: 1,
    noiseLevel: 0.15,
    filterCutoff: 2600,
    ampAttack: 0.3,
    ampDecay: 0.4,
    ampSustain: 0.8,
    ampRelease: 0.8,
    cassetteGen: 0.3,
    hiss: 0.2,
    chorusMix: 0.2,
  }),

  preset("fc-vintage-worn-strings", "Worn Strings", "Worn tape string ensemble", "Vintage", {
    oscATable: "saw",
    oscALevel: 0.55,
    oscBTable: "saw",
    oscBLevel: 0.5,
    oscBDetune: 12,
    unison: 3,
    unisonDetune: 8,
    filterCutoff: 1900,
    ampAttack: 0.7,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.5,
    cassetteGen: 0.4,
    wowFlutter: 0.3,
    reverbMix: 0.4,
  }),


  // ===== CHIP (20) =====
  preset("fc-chip-pulse-hero", "Pulse Hero", "Classic pulse hero lead", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    pulseDuty: 0.5,
    oscALevel: 0.8,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.6,
    ampRelease: 0.15,
    mono: true,
  }),

  preset("fc-chip-triangle-bass", "Triangle Bass Chip", "NES-style triangle bass", "Chip", {
    oscATable: "basic",
    oscALevel: 0.85,
    oscAOctave: -1,
    filterCutoff: 2000,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.5,
    ampRelease: 0.15,
    mono: true,
  }),

  preset("fc-chip-noise-hat", "Noise Hat Chip", "Chip noise hi-hat", "Chip", {
    noiseLevel: 0.9,
    oscALevel: 0.1,
    filterType: "highpass",
    filterCutoff: 4000,
    ampAttack: 0.001,
    ampDecay: 0.08,
    ampSustain: 0.02,
    ampRelease: 0.05,
  }),

  preset("fc-chip-duty-wobble", "Duty Wobble", "PWM duty-cycle wobble", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    pulseDuty: 0.5,
    oscALevel: 0.75,
    filterCutoff: 4000,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.6,
    ampRelease: 0.2,
    lfo1Wave: "triangle",
    lfo1Rate: 6,
    lfo1Depth: 0.5,
    lfo1Dest: "filter",
    mono: true,
  }),

  preset("fc-chip-arp-run", "Chip Arp Run", "Classic chip arp run", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    pulseDuty: 0.25,
    oscALevel: 0.75,
    filterCutoff: 5500,
    ampAttack: 0.001,
    ampDecay: 0.12,
    ampSustain: 0.2,
    ampRelease: 0.08,
  }, { enabled: true, mode: "up", bpm: 150, division: "1/16", octaves: 3, gate: 0.75 }),

  preset("fc-chip-square-stab", "Square Stab", "Short square stab", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    pulseDuty: 0.5,
    oscALevel: 0.8,
    filterCutoff: 4500,
    ampAttack: 0.001,
    ampDecay: 0.12,
    ampSustain: 0.1,
    ampRelease: 0.08,
  }),

  preset("fc-chip-vib-lead", "Vibrato Chip Lead", "Vibrato chip lead", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.75,
    filterCutoff: 4800,
    ampAttack: 0.001,
    ampDecay: 0.25,
    ampSustain: 0.65,
    ampRelease: 0.2,
    lfo1Wave: "sine",
    lfo1Rate: 5.5,
    lfo1Depth: 0.25,
    lfo1Dest: "pitch",
    mono: true,
  }),

  preset("fc-chip-oct-stack", "Octave Stack Chip", "Octave-stacked chip lead", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.55,
    oscBTable: "pulse",
    oscBPos: 0.5,
    oscBLevel: 0.5,
    oscBOctave: 1,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.6,
    ampRelease: 0.15,
  }),

  preset("fc-chip-soft-triangle", "Soft Triangle Melody", "Soft triangle melody chip", "Chip", {
    oscATable: "basic",
    oscALevel: 0.7,
    filterCutoff: 3500,
    ampAttack: 0.01,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.25,
  }),

  preset("fc-chip-battle-lead", "Battle Lead", "Aggressive battle chip lead", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.25,
    pulseDuty: 0.25,
    oscALevel: 0.8,
    filterCutoff: 5200,
    ampAttack: 0.001,
    ampDecay: 0.18,
    ampSustain: 0.55,
    ampRelease: 0.12,
    drive: 0.2,
    mono: true,
  }),

  preset("fc-chip-coin-blip", "Coin Blip", "Coin-collect blip", "Chip", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscAOctave: 2,
    filterCutoff: 6000,
    ampAttack: 0.001,
    ampDecay: 0.15,
    ampSustain: 0.05,
    ampRelease: 0.1,
    pitchEnvAmount: 0.4,
    pitchEnvTime: 0.12,
  }),

  preset("fc-chip-dungeon-drone", "Dungeon Drone", "Dark dungeon chip drone", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.5,
    oscBTable: "pulse",
    oscBLevel: 0.4,
    oscBDetune: 8,
    filterCutoff: 1800,
    ampAttack: 0.3,
    ampDecay: 0.4,
    ampSustain: 0.9,
    ampRelease: 0.8,
  }),

  preset("fc-chip-powerup", "Power-Up Sweep", "Power-up pitch sweep", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.75,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.2,
    ampRelease: 0.2,
    pitchEnvAmount: 0.8,
    pitchEnvTime: 0.35,
  }),

  preset("fc-chip-wave-channel", "Wave Channel Soft", "Soft wave-channel tone", "Chip", {
    oscATable: "basic",
    oscALevel: 0.65,
    oscBTable: "pulse",
    oscBPos: 0.5,
    oscBLevel: 0.35,
    filterCutoff: 3200,
    ampAttack: 0.005,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.3,
    chorusMix: 0.1,
  }),

  preset("fc-chip-noise-snare", "Noise Snare Chip", "Chip noise snare", "Chip", {
    noiseLevel: 0.85,
    oscALevel: 0.15,
    filterType: "bandpass",
    filterCutoff: 3000,
    filterResonance: 0.3,
    ampAttack: 0.001,
    ampDecay: 0.12,
    ampSustain: 0.02,
    ampRelease: 0.08,
  }),

  preset("fc-chip-harmony-duo", "Harmony Duo Chip", "Two-voice chip harmony", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.55,
    oscBTable: "pulse",
    oscBPos: 0.5,
    oscBLevel: 0.5,
    filterCutoff: 4800,
    ampAttack: 0.001,
    ampDecay: 0.22,
    ampSustain: 0.6,
    ampRelease: 0.18,
  }),

  preset("fc-chip-fast-arpeggio", "Fast Chip Arpeggio", "Blazing fast chip arpeggio", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    pulseDuty: 0.5,
    oscALevel: 0.75,
    filterCutoff: 5500,
    ampAttack: 0.001,
    ampDecay: 0.1,
    ampSustain: 0.15,
    ampRelease: 0.06,
  }, { enabled: true, mode: "updown", bpm: 160, division: "1/32", octaves: 2, gate: 0.7 }),

  preset("fc-chip-game-over", "Game Over Drone", "Somber game-over drone", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.5,
    oscALevel: 0.55,
    oscAOctave: -1,
    filterCutoff: 2200,
    ampAttack: 0.2,
    ampDecay: 0.5,
    ampSustain: 0.8,
    ampRelease: 1,
  }),

  preset("fc-chip-sparkle-lead", "Sparkle Chip Lead", "Bright sparkle chip lead", "Chip", {
    oscATable: "pulse",
    oscAPos: 0.125,
    pulseDuty: 0.125,
    oscALevel: 0.7,
    filterCutoff: 6000,
    ampAttack: 0.001,
    ampDecay: 0.2,
    ampSustain: 0.55,
    ampRelease: 0.15,
    airHigh: 0.3,
    airAmount: 0.3,
    mono: true,
  }),

  preset("fc-chip-menu-select", "Menu Select Blip", "UI menu select blip", "Chip", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscAOctave: 1,
    filterCutoff: 4500,
    ampAttack: 0.001,
    ampDecay: 0.1,
    ampSustain: 0.05,
    ampRelease: 0.08,
  }),


  // ===== FM (20) =====
  preset("fc-fm-electric-piano", "FM Electric Piano", "Classic FM electric piano tines", "FM", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.55,
    fmAmount: 0.45,
    fmRatio: 1,
    filterCutoff: 3600,
    ampAttack: 0.002,
    ampDecay: 0.9,
    ampSustain: 0.3,
    ampRelease: 0.55,
    chorusMix: 0.25,
  }),

  preset("fc-fm-bell-tower", "Bell Tower", "Church bell tower FM", "FM", {
    oscATable: "bell",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.6,
    fmRatio: 3.5,
    filterCutoff: 5000,
    ampAttack: 0.001,
    ampDecay: 1.2,
    ampSustain: 0.15,
    ampRelease: 1.5,
    reverbMix: 0.45,
  }),

  preset("fc-fm-bass-growl", "FM Bass Growl", "Growling FM bass", "FM", {
    oscATable: "basic",
    oscALevel: 0.8,
    oscBTable: "basic",
    oscBLevel: 0.6,
    oscAOctave: -1,
    fmAmount: 0.55,
    fmRatio: 2,
    filterCutoff: 1200,
    ampAttack: 0.005,
    ampDecay: 0.35,
    ampSustain: 0.5,
    ampRelease: 0.25,
    mono: true,
    drive: 0.2,
  }),

  preset("fc-fm-pluck-mallet", "FM Mallet Pluck", "FM mallet pluck", "FM", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.5,
    fmRatio: 3,
    filterCutoff: 4200,
    ampAttack: 0.001,
    ampDecay: 0.4,
    ampSustain: 0.1,
    ampRelease: 0.35,
    reverbMix: 0.25,
  }),

  preset("fc-fm-brass-stab", "FM Brass Stab", "FM brass stab", "FM", {
    oscATable: "saw",
    oscALevel: 0.65,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.4,
    fmRatio: 1.5,
    filterCutoff: 2800,
    filterEnvAmount: 0.5,
    filtDecay: 0.2,
    ampAttack: 0.04,
    ampDecay: 0.3,
    ampSustain: 0.6,
    ampRelease: 0.25,
  }),

  preset("fc-fm-glass-pad", "FM Glass Pad", "Glassy FM pad", "FM", {
    oscATable: "basic",
    oscALevel: 0.5,
    oscBTable: "bell",
    oscBLevel: 0.45,
    fmAmount: 0.35,
    fmRatio: 2.5,
    filterCutoff: 3800,
    ampAttack: 0.7,
    ampDecay: 0.5,
    ampSustain: 0.9,
    ampRelease: 1.5,
    reverbMix: 0.45,
    chorusMix: 0.3,
  }),

  preset("fc-fm-metallic-hit", "FM Metallic Hit", "Metallic FM hit", "FM", {
    oscATable: "metallic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.55,
    fmAmount: 0.7,
    fmRatio: 4,
    filterCutoff: 4500,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.05,
    ampRelease: 0.4,
    reverbMix: 0.3,
  }),

  preset("fc-fm-soft-tines", "Soft FM Tines", "Soft FM tine keys", "FM", {
    oscATable: "basic",
    oscALevel: 0.65,
    oscBTable: "basic",
    oscBLevel: 0.4,
    fmAmount: 0.3,
    fmRatio: 1,
    filterCutoff: 2800,
    ampAttack: 0.005,
    ampDecay: 1,
    ampSustain: 0.35,
    ampRelease: 0.7,
    chorusMix: 0.3,
  }),

  preset("fc-fm-screamer", "FM Screamer", "Aggressive FM scream lead", "FM", {
    oscATable: "basic",
    oscALevel: 0.75,
    oscBTable: "basic",
    oscBLevel: 0.6,
    fmAmount: 0.75,
    fmRatio: 5,
    filterCutoff: 4000,
    ampAttack: 0.01,
    ampDecay: 0.25,
    ampSustain: 0.65,
    ampRelease: 0.2,
    drive: 0.3,
    mono: true,
  }),

  preset("fc-fm-hollow-wood", "Hollow Wood FM", "Hollow wooden FM tone", "FM", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.45,
    fmAmount: 0.4,
    fmRatio: 2.7,
    filterCutoff: 2200,
    ampAttack: 0.001,
    ampDecay: 0.5,
    ampSustain: 0.15,
    ampRelease: 0.4,
  }),

  preset("fc-fm-organ-sparkle", "FM Organ Sparkle", "Sparkly FM organ", "FM", {
    oscATable: "basic",
    oscALevel: 0.55,
    oscBTable: "basic",
    oscBLevel: 0.4,
    oscBOctave: 1,
    fmAmount: 0.35,
    fmRatio: 2,
    filterCutoff: 3600,
    ampAttack: 0.02,
    ampDecay: 0.3,
    ampSustain: 0.85,
    ampRelease: 0.3,
    chorusMix: 0.2,
  }),

  preset("fc-fm-deep-kick-tone", "FM Kick Tone", "Pitch-swept FM kick tone", "FM", {
    oscATable: "basic",
    oscALevel: 0.85,
    oscAOctave: -2,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.5,
    fmRatio: 1,
    filterCutoff: 600,
    ampAttack: 0.001,
    ampDecay: 0.35,
    ampSustain: 0.05,
    ampRelease: 0.25,
    pitchEnvAmount: 0.7,
    pitchEnvTime: 0.2,
    punch: 0.5,
  }),

  preset("fc-fm-crystal-chime", "Crystal Chime", "Crystal FM chime", "FM", {
    oscATable: "bell",
    oscALevel: 0.65,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.55,
    fmRatio: 6,
    filterCutoff: 5500,
    ampAttack: 0.001,
    ampDecay: 0.8,
    ampSustain: 0.1,
    ampRelease: 1,
    reverbMix: 0.4,
    delayMix: 0.2,
  }),

  preset("fc-fm-talkbox", "FM Talkbox", "Talkbox-ish FM voice", "FM", {
    oscATable: "vocal",
    oscALevel: 0.65,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.45,
    fmRatio: 2,
    filterCutoff: 2400,
    ampAttack: 0.02,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.3,
    mono: true,
  }),

  preset("fc-fm-cold-steel", "Cold Steel FM", "Cold steel FM lead", "FM", {
    oscATable: "metallic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.55,
    fmAmount: 0.6,
    fmRatio: 3,
    filterCutoff: 3800,
    ampAttack: 0.01,
    ampDecay: 0.3,
    ampSustain: 0.65,
    ampRelease: 0.25,
    mono: true,
  }),

  preset("fc-fm-warm-ep", "Warm FM EP", "Warm rounded FM EP", "FM", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.45,
    fmAmount: 0.35,
    fmRatio: 1,
    filterCutoff: 2400,
    ampAttack: 0.003,
    ampDecay: 1,
    ampSustain: 0.4,
    ampRelease: 0.65,
    chorusMix: 0.35,
    cassetteGen: 0.1,
  }),

  preset("fc-fm-chaos-stack", "Chaos Stack FM", "Chaotic stacked FM", "FM", {
    oscATable: "basic",
    oscALevel: 0.55,
    oscBTable: "bell",
    oscBLevel: 0.45,
    oscCTable: "metallic",
    oscCLevel: 0.3,
    fmAmount: 0.7,
    fmRatio: 4.5,
    fmBtoA: 0.35,
    filterCutoff: 4200,
    ampAttack: 0.01,
    ampDecay: 0.4,
    ampSustain: 0.55,
    ampRelease: 0.4,
    drive: 0.2,
  }),

  preset("fc-fm-marimba", "FM Marimba", "FM marimba bars", "FM", {
    oscATable: "basic",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.5,
    fmAmount: 0.5,
    fmRatio: 2.5,
    filterCutoff: 3400,
    ampAttack: 0.001,
    ampDecay: 0.45,
    ampSustain: 0.08,
    ampRelease: 0.3,
    reverbMix: 0.2,
  }),

  preset("fc-fm-space-gong", "Space Gong", "Huge space gong FM", "FM", {
    oscATable: "bell",
    oscALevel: 0.65,
    oscBTable: "metallic",
    oscBLevel: 0.5,
    fmAmount: 0.65,
    fmRatio: 1.4,
    filterCutoff: 3000,
    ampAttack: 0.001,
    ampDecay: 1.5,
    ampSustain: 0.2,
    ampRelease: 2.5,
    reverbSize: 5,
    reverbMix: 0.55,
  }),

  preset("fc-fm-crossmod-forge", "Cross-Mod Forge", "Cross-mod forged metallic FM", "FM", {
    oscATable: "bell",
    oscALevel: 0.7,
    oscBTable: "basic",
    oscBLevel: 0.55,
    fmAmount: 0.55,
    fmRatio: 3,
    fmBtoA: 0.45,
    ringAmount: 0.2,
    filterCutoff: 4800,
    ampAttack: 0.002,
    ampDecay: 0.35,
    ampSustain: 0.45,
    ampRelease: 0.3,
    mono: true,
  }),

];
