/**
 * Mission showcase presets — hand-tuned for Fire Command demos.
 * Designed to be sequenced (clear roles, BPM-friendly LFOs, controlled FX).
 */

import {
  DEFAULT_FIRE_PATCH,
  makeModMatrix,
  type FirePatch,
  type ModRoute,
  type ModSource,
  type ModDest,
} from "./FireCommandSynth";
import type { FirePreset } from "./firePresetBank";

const P = (over: Partial<FirePatch>): FirePatch => ({ ...DEFAULT_FIRE_PATCH, ...over });
const MR = (source: ModSource, dest: ModDest, amount: number): ModRoute => ({ source, dest, amount });

/** Specialized presets used by mission packs (also appear in the factory browser). */
export const MISSION_SHOWCASE_PRESETS: FirePreset[] = [
  // ── Trap ──
  {
    id: "ms-trap-808",
    name: "Mission · Trap 808",
    desc: "Long sub boom with a hard pitch thump — built for trap sequences",
    category: "Bass",
    patch: P({
      oscATable: "basic", oscAPos: 0, oscALevel: 0.55,
      oscBTable: "basic", oscBPos: 0.05, oscBOctave: -1, oscBLevel: 0.35,
      oscCLevel: 0,
      unison: 1, subWave: "sine", subLevel: 0.95, noiseLevel: 0,
      filterType: "lowpass", filterCutoff: 140, filterResonance: 0.8,
      filterEnvAmount: 0.15, filtDecay: 0.35, filtSustain: 0.2,
      pitchEnvAmount: 18, pitchEnvTime: 0.18,
      ampAttack: 0.002, ampDecay: 0.85, ampSustain: 0.55, ampRelease: 0.45, velAmount: 0.9,
      drive: 0.18, driveMode: "soft", punch: 0.55, tone: 5500,
      mono: true, glide: 0.12,
      chorusMix: 0, delayMix: 0, reverbMix: 0.04, reverbSize: 1.2,
      masterGain: 0.88,
    }),
  },
  {
    id: "ms-trap-bell",
    name: "Mission · Ice Bell",
    desc: "Sparse glassy bell for trap hooks",
    category: "Keys",
    patch: P({
      oscATable: "bell", oscAPos: 0.55, oscAEnv: -0.35, oscALevel: 0.85,
      oscBTable: "bell", oscBPos: 0.8, oscBOctave: 1, oscBDetune: 6, oscBLevel: 0.28,
      oscCLevel: 0, unison: 1, subLevel: 0,
      filterType: "highpass", filterCutoff: 420, filterResonance: 1.2,
      filterEnvAmount: 0.25, filtDecay: 0.5,
      ampAttack: 0.001, ampDecay: 0.9, ampSustain: 0.12, ampRelease: 0.8,
      delayTime: 0.375, delayFeedback: 0.42, delayMix: 0.32,
      reverbSize: 3.4, reverbMix: 0.38,
      drive: 0.02, chorusMix: 0.15, masterGain: 0.58,
    }),
  },

  // ── Cinematic ──
  {
    id: "ms-cinema-tick",
    name: "Mission · Tension Tick",
    desc: "Dry ticking pluck for trailer pulses",
    category: "Pluck",
    patch: P({
      oscATable: "harmonic", oscAPos: 0.35, oscAEnv: 0.4, oscALevel: 0.75,
      oscBTable: "basic", oscBPos: 0.2, oscBLevel: 0.25, oscBDetune: 3,
      unison: 1, subLevel: 0.05,
      filterType: "bandpass", filterCutoff: 1800, filterResonance: 4,
      filterEnvAmount: 0.55, filtAttack: 0.001, filtDecay: 0.12, filtSustain: 0.05,
      ampAttack: 0.001, ampDecay: 0.14, ampSustain: 0, ampRelease: 0.12,
      delayTime: 0.5, delayFeedback: 0.35, delayMix: 0.18,
      reverbSize: 4, reverbMix: 0.22,
      drive: 0.05, masterGain: 0.62,
    }),
  },
  {
    id: "ms-cinema-drone",
    name: "Mission · Low Drone",
    desc: "Ominous sustained bed for score work",
    category: "Pad",
    patch: P({
      oscATable: "growl", oscAPos: 0.2, oscALevel: 0.55, oscALfo: 0.08,
      oscBTable: "vocal", oscBPos: 0.15, oscBOctave: -1, oscBLevel: 0.45, oscBDetune: 8,
      oscCTable: "harmonic", oscCPos: 0.1, oscCOctave: -2, oscCLevel: 0.3,
      unison: 3, unisonDetune: 12, unisonWidth: 0.7, subWave: "sine", subLevel: 0.4,
      filterType: "lowpass", filterCutoff: 380, filterResonance: 2,
      ampAttack: 0.8, ampDecay: 1, ampSustain: 1, ampRelease: 1.8,
      lfo1Wave: "sine", lfo1Rate: 0.12, lfo1Depth: 0.25, lfo1Dest: "filter",
      lfo2Wave: "sine", lfo2Rate: 0.07, lfo2Depth: 0.15, lfo2Dest: "pan",
      chorusRate: 0.2, chorusDepth: 0.4, chorusMix: 0.35,
      reverbSize: 5, reverbMix: 0.45, phaserMix: 0.2, phaserRate: 0.15,
      drive: 0.12, masterGain: 0.55,
    }),
  },

  // ── Warehouse techno ──
  {
    id: "ms-techno-reese",
    name: "Mission · Floor Reese",
    desc: "Wide detuned reese that pumps under a 4/4 kick",
    category: "Bass",
    patch: P({
      oscATable: "growl", oscAPos: 0.42, oscALevel: 0.8,
      oscBTable: "growl", oscBPos: 0.62, oscBDetune: 28, oscBLevel: 0.7,
      oscCTable: "saw", oscCPos: 0.5, oscCOctave: -1, oscCDetune: -14, oscCLevel: 0.35,
      unison: 5, unisonDetune: 26, unisonWidth: 0.85, subWave: "square", subLevel: 0.45,
      warpTilt: -0.15,
      filterType: "lowpass", filterCutoff: 240, filterResonance: 4.5,
      filterEnvAmount: 0.12, filterDrive: 0.25,
      ampAttack: 0.01, ampDecay: 0.2, ampSustain: 1, ampRelease: 0.15,
      drive: 0.4, driveMode: "tube", punch: 0.35, tone: 9000,
      mono: true, glide: 0.03,
      chorusMix: 0.2, delayMix: 0, reverbMix: 0.08,
      masterGain: 0.72,
    }),
  },
  {
    id: "ms-techno-stab",
    name: "Mission · Warehouse Stab",
    desc: "Short industrial FM hit for techno peaks",
    category: "Lead",
    patch: P({
      oscATable: "metallic", oscAPos: 0.35, oscAEnv: 0.5, oscALevel: 0.7,
      oscBTable: "sync", oscBPos: 0.4, oscBLevel: 0.4, oscBDetune: 7,
      unison: 1, subLevel: 0.15,
      fmAmount: 0.22, fmRatio: 3,
      filterType: "bandpass", filterCutoff: 2200, filterResonance: 5,
      filterEnvAmount: 0.7, filtDecay: 0.1, filtSustain: 0,
      ampAttack: 0.001, ampDecay: 0.16, ampSustain: 0.05, ampRelease: 0.1,
      drive: 0.35, driveMode: "hard", crush: 0.08, punch: 0.5, tone: 11000,
      delayTime: 0.23, delayFeedback: 0.25, delayMix: 0.12,
      mono: true, masterGain: 0.58,
    }),
  },

  // ── Synthwave ──
  {
    id: "ms-wave-chord",
    name: "Mission · Neon Chord",
    desc: "Wide supersaw pad-chord for night-drive beds",
    category: "Lead",
    patch: P({
      oscATable: "saw", oscAPos: 0.9, oscALevel: 0.7, oscAEnv: 0.1,
      oscBTable: "saw", oscBPos: 0.75, oscBDetune: 12, oscBLevel: 0.55,
      oscCTable: "harmonic", oscCPos: 0.6, oscCOctave: 1, oscCLevel: 0.2, oscCDetune: -5,
      unison: 7, unisonDetune: 24, unisonWidth: 1, subLevel: 0.08,
      filterType: "lowpass", filterCutoff: 5200, filterResonance: 1.2,
      filterEnvAmount: 0.2, ampAttack: 0.08, ampDecay: 0.4, ampSustain: 0.85, ampRelease: 0.7,
      chorusRate: 0.45, chorusDepth: 0.55, chorusMix: 0.5,
      phaserRate: 0.25, phaserDepth: 0.5, phaserMix: 0.22,
      delayTime: 0.375, delayFeedback: 0.35, delayMix: 0.22,
      reverbSize: 3.2, reverbMix: 0.28,
      gateOn: true, gateRate: 8, gateDepth: 0.35, gateSmooth: 0.25,
      gatePattern: [1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0],
      drive: 0.08, masterGain: 0.58,
    }),
  },
  {
    id: "ms-wave-bass",
    name: "Mission · Cruise Bass",
    desc: "Tight octave bass for synthwave pulse",
    category: "Bass",
    patch: P({
      oscATable: "saw", oscAPos: 0.3, oscALevel: 0.65,
      oscBTable: "basic", oscBPos: 0, oscBOctave: -1, oscBLevel: 0.5,
      unison: 1, subWave: "sine", subLevel: 0.55,
      filterType: "lowpass", filterCutoff: 520, filterResonance: 2.5,
      filterEnvAmount: 0.35, filtDecay: 0.2, filtSustain: 0.35,
      ampAttack: 0.005, ampDecay: 0.18, ampSustain: 0.75, ampRelease: 0.12,
      drive: 0.22, driveMode: "tube", punch: 0.4, tone: 10000,
      mono: true, glide: 0.04, chorusMix: 0, delayMix: 0, reverbMix: 0.05,
      masterGain: 0.78,
    }),
  },

  // ── Drill ──
  {
    id: "ms-drill-808",
    name: "Mission · Drill Slide",
    desc: "Gliding mono 808 with a sharp attack thump",
    category: "Bass",
    patch: P({
      oscATable: "basic", oscAPos: 0.02, oscALevel: 0.5,
      oscBTable: "basic", oscBPos: 0, oscBOctave: -1, oscBLevel: 0.4,
      unison: 1, subWave: "sine", subLevel: 0.9,
      filterType: "lowpass", filterCutoff: 160, filterResonance: 1,
      pitchEnvAmount: 22, pitchEnvTime: 0.14,
      ampAttack: 0.001, ampDecay: 0.7, ampSustain: 0.6, ampRelease: 0.35,
      drive: 0.2, punch: 0.65, tone: 6000,
      mono: true, glide: 0.18,
      delayMix: 0, reverbMix: 0.03, masterGain: 0.9,
    }),
  },
  {
    id: "ms-drill-pluck",
    name: "Mission · Drill Pluck",
    desc: "Short dark pluck answers for drill hooks",
    category: "Pluck",
    patch: P({
      oscATable: "pulse", oscAPos: 0.4, oscAEnv: 0.35, oscALevel: 0.7,
      oscBTable: "metallic", oscBPos: 0.3, oscBLevel: 0.3, oscBDetune: 5,
      unison: 2, unisonDetune: 8, unisonWidth: 0.4, subLevel: 0,
      filterType: "lowpass", filterCutoff: 2400, filterResonance: 3,
      filterEnvAmount: 0.6, filtDecay: 0.15,
      ampAttack: 0.001, ampDecay: 0.22, ampSustain: 0.05, ampRelease: 0.2,
      delayTime: 0.28, delayFeedback: 0.3, delayMix: 0.2,
      reverbSize: 2, reverbMix: 0.18, drive: 0.1, masterGain: 0.55,
    }),
  },

  // ── Ambient ──
  {
    id: "ms-ambi-morph",
    name: "Mission · Drift Pad",
    desc: "Slow morphing vowel pad — no urgency",
    category: "Pad",
    patch: P({
      oscATable: "vocal", oscAPos: 0.35, oscALfo: 0.35, oscALevel: 0.6,
      oscBTable: "formant2", oscBPos: 0.45, oscBLfo: 0.25, oscBDetune: 10, oscBLevel: 0.5,
      oscCTable: "harmonic", oscCPos: 0.5, oscCOctave: 1, oscCLevel: 0.25, oscCDetune: -7,
      unison: 4, unisonDetune: 14, unisonWidth: 0.9, subLevel: 0.15,
      warpStretch: 0.12, warpTilt: 0.08,
      filterType: "lowpass", filterCutoff: 1800, filterResonance: 1.5,
      ampAttack: 1.4, ampDecay: 1.2, ampSustain: 1, ampRelease: 2.5,
      lfo1Wave: "sine", lfo1Rate: 0.08, lfo1Depth: 0.4, lfo1Dest: "filter",
      lfo2Wave: "triangle", lfo2Rate: 0.05, lfo2Depth: 0.2, lfo2Dest: "pan",
      modMatrix: makeModMatrix([
        MR("lfo1", "wtA", 0.45),
        MR("lfo2", "wtB", 0.35),
      ]),
      chorusRate: 0.15, chorusDepth: 0.5, chorusMix: 0.45,
      phaserRate: 0.08, phaserDepth: 0.4, phaserMix: 0.25,
      delayTime: 0.75, delayFeedback: 0.45, delayMix: 0.28,
      reverbSize: 5.5, reverbMix: 0.55,
      spectralMode: "smear", spectralAmount: 0.35, spectralMix: 0.25,
      drive: 0.04, masterGain: 0.5,
    }),
  },
  {
    id: "ms-ambi-choir",
    name: "Mission · Glass Choir",
    desc: "High shimmering choir layer for ambient bloom",
    category: "Pad",
    patch: P({
      oscATable: "vocal", oscAPos: 0.7, oscALevel: 0.55,
      oscBTable: "bell", oscBPos: 0.5, oscBOctave: 1, oscBLevel: 0.35, oscBDetune: 4,
      oscCTable: "additive", oscCPos: 0.6, oscCOctave: 1, oscCLevel: 0.25,
      unison: 5, unisonDetune: 10, unisonWidth: 1, subLevel: 0,
      filterType: "highpass", filterCutoff: 600, filterResonance: 1,
      ampAttack: 1.8, ampDecay: 1, ampSustain: 0.9, ampRelease: 3,
      chorusMix: 0.4, reverbSize: 6, reverbMix: 0.6,
      delayTime: 0.9, delayFeedback: 0.4, delayMix: 0.22,
      spectralMode: "freeze", spectralAmount: 0.2, spectralMix: 0.15,
      drive: 0.02, masterGain: 0.42,
    }),
  },

  // ── Neuro DnB ──
  {
    id: "ms-neuro-growl",
    name: "Mission · Neuro Growl",
    desc: "Fast filter wobble growl locked for 174 two-step",
    category: "Bass",
    patch: P({
      oscATable: "growl", oscAPos: 0.55, oscALfo: 0.2, oscALevel: 0.8,
      oscBTable: "vocal", oscBPos: 0.4, oscBLevel: 0.45, oscBDetune: 9,
      oscCTable: "fold", oscCPos: 0.35, oscCLevel: 0.25,
      unison: 3, unisonDetune: 14, unisonWidth: 0.55, subWave: "square", subLevel: 0.5,
      warpComb: 0.2,
      filterType: "lowpass", filterCutoff: 480, filterResonance: 7, filterDrive: 0.35,
      filterEnvAmount: 0.1,
      // ~1/4 note at 174 ≈ 2.9 Hz — readable neuro movement
      lfo1Wave: "triangle", lfo1Rate: 2.9, lfo1Depth: 0.75, lfo1Dest: "filter",
      modMatrix: makeModMatrix([MR("lfo1", "wtA", 0.35), MR("lfo1", "resonance", 0.25)]),
      ampAttack: 0.003, ampDecay: 0.15, ampSustain: 0.95, ampRelease: 0.08,
      drive: 0.38, driveMode: "tube", punch: 0.3, tone: 10500,
      mono: true, glide: 0.04,
      delayMix: 0.08, reverbMix: 0.06, masterGain: 0.68,
    }),
  },
  {
    id: "ms-neuro-razor",
    name: "Mission · Razor Stab",
    desc: "Bright short lead stabs for neuro fills",
    category: "Lead",
    patch: P({
      oscATable: "sync", oscAPos: 0.45, oscAEnv: 0.55, oscALevel: 0.75,
      oscBTable: "metallic", oscBPos: 0.5, oscBLevel: 0.4, oscBDetune: 8,
      unison: 2, unisonDetune: 10, unisonWidth: 0.5, subLevel: 0,
      filterType: "highpass", filterCutoff: 900, filterResonance: 2.5,
      filterEnvAmount: 0.4, filtDecay: 0.12,
      ampAttack: 0.001, ampDecay: 0.12, ampSustain: 0.1, ampRelease: 0.1,
      lfo1Wave: "sine", lfo1Rate: 5.5, lfo1Depth: 0.15, lfo1Dest: "pitch",
      delayTime: 0.17, delayFeedback: 0.3, delayMix: 0.18,
      drive: 0.25, driveMode: "fold", masterGain: 0.52,
    }),
  },

  // ── Acid ──
  {
    id: "ms-acid-303",
    name: "Mission · Acid 303",
    desc: "Resonant mono squelch with glide — classic acid line",
    category: "Bass",
    patch: P({
      oscATable: "saw", oscAPos: 0.12, oscALevel: 0.9,
      oscBTable: "pulse", oscBPos: 0.4, oscBLevel: 0.2, oscBDetune: 2,
      oscCLevel: 0, unison: 1, subLevel: 0,
      filterType: "lowpass", filterCutoff: 420, filterResonance: 14,
      filterEnvAmount: 0.95, filterKeyTrack: 0.35, filterDrive: 0.4,
      filtAttack: 0.001, filtDecay: 0.18, filtSustain: 0.02, filtRelease: 0.08,
      ampAttack: 0.001, ampDecay: 0.22, ampSustain: 0.5, ampRelease: 0.06, velAmount: 1,
      drive: 0.42, driveMode: "tube", tone: 13000, punch: 0.25,
      mono: true, glide: 0.065,
      delayTime: 0.33, delayFeedback: 0.28, delayMix: 0.12,
      reverbMix: 0.05, chorusMix: 0, masterGain: 0.65,
    }),
  },

  // ── Trance ──
  {
    id: "ms-trance-saw",
    name: "Mission · Uplift Saw",
    desc: "Huge supersaw stack for trance lifts",
    category: "Lead",
    patch: P({
      oscATable: "saw", oscAPos: 0.92, oscALevel: 0.7, oscAEnv: 0.12,
      oscBTable: "saw", oscBPos: 0.8, oscBDetune: 11, oscBLevel: 0.6,
      oscCTable: "saw", oscCPos: 0.7, oscCOctave: 1, oscCDetune: -8, oscCLevel: 0.3,
      unison: 7, unisonDetune: 26, unisonWidth: 1, subLevel: 0.1,
      filterType: "lowpass", filterCutoff: 7200, filterResonance: 1,
      filterEnvAmount: 0.35, ampAttack: 0.04, ampDecay: 0.35, ampSustain: 0.85, ampRelease: 0.55,
      chorusRate: 0.55, chorusDepth: 0.55, chorusMix: 0.45,
      delayTime: 0.375, delayFeedback: 0.38, delayMix: 0.28,
      reverbSize: 3.5, reverbMix: 0.3,
      drive: 0.1, punch: 0.2, masterGain: 0.55,
    }),
  },
  {
    id: "ms-trance-bass",
    name: "Mission · Offbeat Bass",
    desc: "Punchy rolling bass for trance offbeats",
    category: "Bass",
    patch: P({
      oscATable: "saw", oscAPos: 0.25, oscALevel: 0.7,
      oscBTable: "basic", oscBPos: 0, oscBOctave: -1, oscBLevel: 0.45,
      unison: 1, subWave: "sine", subLevel: 0.5,
      filterType: "lowpass", filterCutoff: 680, filterResonance: 3,
      filterEnvAmount: 0.55, filtDecay: 0.14, filtSustain: 0.25,
      ampAttack: 0.003, ampDecay: 0.14, ampSustain: 0.55, ampRelease: 0.08,
      drive: 0.28, driveMode: "soft", punch: 0.55, tone: 11000,
      mono: true, glide: 0.02,
      delayMix: 0, reverbMix: 0.04, masterGain: 0.8,
    }),
  },

  // ── Dubstep ──
  {
    id: "ms-dub-wobble",
    name: "Mission · Halftime Wobble",
    desc: "Nasty alien wobble LFO-locked for 140 halftime",
    category: "Bass",
    patch: P({
      oscATable: "growl", oscAPos: 0.6, oscALfo: 0.4, oscALevel: 0.85,
      oscBTable: "fold", oscBPos: 0.45, oscBLevel: 0.5, oscBDetune: 14,
      oscCTable: "vocal", oscCPos: 0.35, oscCLevel: 0.3,
      unison: 4, unisonDetune: 18, unisonWidth: 0.65, subWave: "square", subLevel: 0.6,
      warpStretch: 0.2, warpComb: 0.15,
      filterType: "lowpass", filterCutoff: 380, filterResonance: 8, filterDrive: 0.4,
      // Quarter-note wobble at 140 BPM ≈ 2.33 Hz
      lfo1Wave: "triangle", lfo1Rate: 2.33, lfo1Depth: 0.9, lfo1Dest: "filter",
      lfo2Wave: "square", lfo2Rate: 2.33, lfo2Depth: 0.2, lfo2Dest: "off",
      modMatrix: makeModMatrix([
        MR("lfo1", "wtA", 0.5),
        MR("lfo1", "fm", 0.3),
        MR("lfo2", "resonance", 0.35),
      ]),
      fmAmount: 0.15, fmRatio: 2,
      ampAttack: 0.004, ampDecay: 0.2, ampSustain: 1, ampRelease: 0.12,
      drive: 0.45, driveMode: "fuzz", punch: 0.4, tone: 10000, crush: 0.05,
      mono: true, glide: 0.06,
      delayMix: 0.1, reverbMix: 0.08, masterGain: 0.7,
    }),
  },
  {
    id: "ms-dub-zap",
    name: "Mission · Laser Zap",
    desc: "Short FX zap for dubstep fills",
    category: "FX",
    patch: P({
      oscATable: "sync", oscAPos: 0.2, oscAEnv: 0.8, oscALevel: 0.7,
      oscBTable: "chip", oscBPos: 0.5, oscBOctave: 1, oscBLevel: 0.4,
      unison: 1, subLevel: 0,
      filterType: "bandpass", filterCutoff: 3500, filterResonance: 6,
      filterEnvAmount: 0.85, filtDecay: 0.2,
      pitchEnvAmount: 24, pitchEnvTime: 0.12,
      ampAttack: 0.001, ampDecay: 0.18, ampSustain: 0, ampRelease: 0.15,
      delayTime: 0.2, delayFeedback: 0.4, delayMix: 0.35,
      reverbSize: 2, reverbMix: 0.2,
      drive: 0.2, masterGain: 0.5,
    }),
  },
];
