import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { getEngine, FRIENDLY_TO_EQ, type FriendlyKey } from "@/audio/AudioEngine";
import { useAudioStore } from "@/state/audioStore";
import { useCalibrationStore } from "@/state/calibrationStore";
import { useUIStore } from "@/state/uiStore";
import { SOUND_PARAM_META, type SoundParams } from "@/audio/types";
import { requestPreviewCommit } from "@/lib/previewCommitBus";

/**
 * Test frequencies: the standard audiometric octaves (250 Hz – 8 kHz) plus
 * a low extension (62/125 Hz) and a treble extension (12/16 kHz) so the
 * compensation can cover the full 10-band EQ.
 */
const FREQS = [62, 125, 250, 500, 1000, 2000, 4000, 8000, 12000, 16000] as const;

/** Slider floor — effectively silent on normal listening volume. */
const START_DB = -70;
/** Slider ceiling — kept well below 0 dBFS so the test never gets painful. */
const MAX_DB = -15;

/**
 * Compensation policy (see computeCompensation):
 * - We compensate only HALF of the measured relative loss. Fully "flattening"
 *   a hearing curve sounds harsh and unnatural (your brain already adapts to
 *   your own ears) and large boosts eat headroom / risk distortion.
 * - Boosts are capped at +6 dB and cuts at -3 dB per band.
 */
const COMP_FRACTION = 0.5;
const MAX_BOOST_DB = 6;
const MAX_CUT_DB = 3;

/** Quietest audible level per frequency; a missing key = never heard. */
type Thresholds = Partial<Record<number, number>>;

interface CompResult {
  /** Slider values (param space, -1..1) per EQ band. */
  partial: Partial<SoundParams>;
  /** Actual dB applied per band, for display. */
  bandDb: Partial<Record<FriendlyKey, number>>;
}

function dbToLin(db: number): number {
  return Math.pow(10, db / 20);
}

/** Linear interpolation of the threshold curve in log-frequency space. */
function interpThreshold(points: { f: number; th: number }[], f: number): number {
  if (f <= points[0].f) return points[0].th;
  const last = points[points.length - 1];
  if (f >= last.f) return last.th;
  for (let i = 1; i < points.length; i++) {
    if (f <= points[i].f) {
      const a = points[i - 1];
      const b = points[i];
      const w = (Math.log(f) - Math.log(a.f)) / (Math.log(b.f) - Math.log(a.f));
      return a.th + (b.th - a.th) * w;
    }
  }
  return last.th;
}

/**
 * Turn per-ear thresholds into a compensation EQ.
 *
 * 1. Average the two ears per frequency (the EQ chain is not per-channel, so
 *    a mid compensation is all we can apply). Frequencies not heard in either
 *    ear are excluded entirely — "couldn't measure" must not become a boost.
 * 2. Normalise to the 1 kHz threshold so results are RELATIVE across bands:
 *    on consumer hardware we cannot know absolute dB HL, only which bands
 *    needed more or less level than the reference.
 * 3. Sample the relative-loss curve at each EQ band's actual centre frequency
 *    (log-f interpolation) — the test frequencies don't coincide with the
 *    band centres, so a direct freq→band table would mis-assign the loss.
 * 4. Compensate COMP_FRACTION of the loss, capped to [-MAX_CUT_DB, +MAX_BOOST_DB],
 *    then convert dB into the band's slider value via its maxDb.
 */
function computeCompensation(left: Thresholds, right: Thresholds): CompResult | null {
  const points: { f: number; th: number }[] = [];
  for (const f of FREQS) {
    const l = left[f];
    const r = right[f];
    const vals = [l, r].filter((v): v is number => v !== undefined);
    if (vals.length === 0) continue;
    points.push({ f, th: vals.reduce((a, b) => a + b, 0) / vals.length });
  }
  // Need a usable curve and a mid reference to normalise against.
  if (points.length < 3) return null;
  const ref = interpThreshold(points, 1000);

  const partial: Partial<SoundParams> = {};
  const bandDb: Partial<Record<FriendlyKey, number>> = {};
  for (const key of Object.keys(FRIENDLY_TO_EQ) as FriendlyKey[]) {
    const band = FRIENDLY_TO_EQ[key];
    const delta = interpThreshold(points, band.freq) - ref;
    const compDb = Math.max(-MAX_CUT_DB, Math.min(MAX_BOOST_DB, delta * COMP_FRACTION));
    const value = Math.max(-1, Math.min(1, compDb / band.maxDb));
    partial[key] = value;
    bandDb[key] = value * band.maxDb;
  }
  return { partial, bandDb };
}

function fmtFreq(f: number): string {
  return f >= 1000 ? `${f / 1000}k` : `${f}`;
}

/**
 * Threshold sweep, method-of-adjustment style: for each ear and frequency the
 * tone starts silent and the user raises it to the quietest level they can
 * hear. Tones are pure sines routed STRAIGHT to the output (bypassing the
 * sculpt EQ / effects) so the measurement isn't coloured by the current
 * tuning, generated by a single ramped oscillator (no clicks, no per-tick
 * buffer allocations).
 */
export function HearingTestModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [step, setStep] = useState(0); // index into FREQS
  const [ear, setEar] = useState<"L" | "R">("L");
  const [dbLevel, setDbLevel] = useState(START_DB);
  const [left, setLeft] = useState<Thresholds>({});
  const [right, setRight] = useState<Thresholds>({});
  const [stage, setStage] = useState<"intro" | "test" | "done">("intro");
  const [compPreview, setCompPreview] = useState(false);

  const toneRef = useRef<{ osc: OscillatorNode; gain: GainNode; pan: StereoPannerNode } | null>(null);
  const baselineRef = useRef<SoundParams | null>(null);
  const lastCompRef = useRef<CompResult | null>(null);
  const previewingRef = useRef(false);
  const stageRef = useRef(stage);

  const setParams = useAudioStore((s) => s.setParams);
  const previewParams = useAudioStore((s) => s.previewParams);
  const setHearingTest = useCalibrationStore((s) => s.setHearingTest);
  const toast = useUIStore((s) => s.toast);

  const comp = useMemo(
    () => (stage === "done" ? computeCompensation(left, right) : null),
    [stage, left, right],
  );
  lastCompRef.current = comp;
  previewingRef.current = compPreview;
  stageRef.current = stage;

  const stopTone = () => {
    const t = toneRef.current;
    if (!t) return;
    toneRef.current = null;
    const now = t.osc.context.currentTime;
    t.gain.gain.cancelScheduledValues(now);
    t.gain.gain.setTargetAtTime(0, now, 0.02);
    window.setTimeout(() => {
      try { t.osc.stop(); } catch { /* already stopped */ }
      try { t.osc.disconnect(); } catch { /* ignore */ }
      try { t.gain.disconnect(); } catch { /* ignore */ }
      try { t.pan.disconnect(); } catch { /* ignore */ }
    }, 150);
  };

  // If the compensation is being auditioned but not committed, put the
  // affected bands back where they were.
  const restoreBaseline = () => {
    const base = baselineRef.current;
    if (base && comp) {
      const restore: Partial<SoundParams> = {};
      for (const k of Object.keys(comp.partial) as (keyof SoundParams)[]) {
        restore[k] = base[k];
      }
      previewParams(restore);
    }
    setCompPreview(false);
  };

  const handleClose = () => {
    if (compPreview) restoreBaseline();
    if (stage === "test") toast("Hearing test discarded");
    else if (stage === "done") toast("Kept current EQ");
    onClose();
  };

  useEffect(
    () => () => {
      stopTone();
      const base = baselineRef.current;
      const c = lastCompRef.current;
      if (previewingRef.current && base && c) {
        const restore: Partial<SoundParams> = {};
        for (const k of Object.keys(c.partial) as (keyof SoundParams)[]) {
          restore[k] = base[k];
        }
        useAudioStore.getState().previewParams(restore);
      }
      if (stageRef.current === "test") {
        useUIStore.getState().toast("Hearing test discarded");
      }
    },
    [],
  );

  // Escape closes the modal, like every other overlay in the app.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== "Escape") return;
      e.preventDefault();
      handleClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, onClose, compPreview, comp]);

  // Reset everything when the modal closes.
  useEffect(() => {
    if (!open) {
      stopTone();
      setStep(0);
      setEar("L");
      setDbLevel(START_DB);
      setLeft({});
      setRight({});
      setStage("intro");
      setCompPreview(false);
      baselineRef.current = null;
    }
  }, [open]);

  // One long-lived oscillator per test run; frequency / pan / level are
  // updated with short exponential ramps so there are no clicks and no
  // per-change allocations.
  useEffect(() => {
    if (stage !== "test" || !open) {
      stopTone();
      return;
    }
    const eng = getEngine();
    void eng.resume();
    const ctx = eng.ctx as AudioContext;
    let t = toneRef.current;
    if (!t) {
      const osc = ctx.createOscillator();
      osc.type = "sine";
      osc.frequency.value = FREQS[step];
      const gain = ctx.createGain();
      gain.gain.value = 0;
      const pan = ctx.createStereoPanner();
      pan.pan.value = ear === "L" ? -1 : 1;
      // Straight to the hardware — deliberately NOT through the sculpt chain.
      osc.connect(gain);
      gain.connect(pan);
      pan.connect(ctx.destination);
      osc.start();
      t = { osc, gain, pan };
      toneRef.current = t;
    }
    const now = ctx.currentTime;
    t.osc.frequency.setTargetAtTime(FREQS[step], now, 0.01);
    t.pan.pan.setTargetAtTime(ear === "L" ? -1 : 1, now, 0.01);
    t.gain.gain.setTargetAtTime(dbToLin(dbLevel), now, 0.03);
  }, [stage, open, step, ear, dbLevel]);

  if (!open) return null;

  /** Record the current frequency (level, or null for "never heard") and advance. */
  const record = (level: number | null) => {
    const freq = FREQS[step];
    const nextLeft = ear === "L" && level !== null ? { ...left, [freq]: level } : left;
    const nextRight = ear === "R" && level !== null ? { ...right, [freq]: level } : right;
    setLeft(nextLeft);
    setRight(nextRight);
    if (step + 1 < FREQS.length) {
      setStep(step + 1);
      setDbLevel(START_DB);
      return;
    }
    if (ear === "L") {
      setStep(0);
      setEar("R");
      setDbLevel(START_DB);
      return;
    }
    stopTone();
    setStage("done");
    setHearingTest({ testedAt: Date.now(), left: nextLeft, right: nextRight });
  };

  const toggleCompPreview = () => {
    if (!comp) return;
    if (compPreview) {
      restoreBaseline();
      return;
    }
    if (!baselineRef.current) {
      baselineRef.current = { ...useAudioStore.getState().params };
    }
    previewParams(comp.partial);
    setCompPreview(true);
  };

  const onApplyCompensation = () => {
    if (!comp) return;
    // Commit to the live engine AND fold into the calibration profile — the
    // Calibration view re-pushes `state.profile` whenever an A/B preview
    // ends, so compensation living only in `params` would get clobbered.
    // Also mark the preview session committed so leaving Calibration does
    // not restore the pre-test knobs over this Apply.
    requestPreviewCommit();
    const setProfileAxis = useCalibrationStore.getState().setProfileAxis;
    for (const [band, value] of Object.entries(comp.partial)) {
      setProfileAxis(band as keyof SoundParams, value as number);
    }
    setParams(comp.partial);
    setCompPreview(false);
    baselineRef.current = null;
    toast("Applied hearing compensation to those EQ bands");
    onClose();
  };

  // A stray backdrop click mid-test would silently discard progress; require
  // the explicit ✕ (or Esc) once the sweep is underway.
  const onBackdropClick = () => {
    if (stage !== "test") handleClose();
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-[90] bg-black/75 backdrop-blur-sm flex items-center justify-center p-6"
        onClick={onBackdropClick}
      >
        <motion.div
          initial={{ scale: 0.95, y: 20 }}
          animate={{ scale: 1, y: 0 }}
          exit={{ scale: 0.95, y: 20 }}
          onClick={(e) => e.stopPropagation()}
          className="glass-strong rounded-2xl max-w-xl w-full p-6"
        >
          <div className="flex items-start justify-between mb-3">
            <div>
              <div className="text-[10px] uppercase tracking-[0.3em] text-dim">
                Calibration
              </div>
              <div className="text-2xl font-semibold neon-text">Hearing Test</div>
            </div>
            <button
              type="button"
              onClick={handleClose}
              className="w-8 h-8 rounded-lg border border-white/15 text-white/60 hover:text-white"
            >
              {"\u2715"}
            </button>
          </div>

          {stage === "intro" && (
            <div>
              <p className="text-sm text-white/85 leading-relaxed">
                For each of 10 frequencies per ear, a pure tone starts silent —
                raise the slider until you can <em>just barely</em> hear it,
                then click "I can hear it". Takes about 2 minutes.
              </p>
              <ul className="text-xs text-white/70 mt-3 space-y-1 list-disc pl-4">
                <li>Use a quiet room and set your normal listening volume <em>before</em> starting — don't change it mid-test.</li>
                <li>Tones bypass your current EQ so the result reflects your ears + headphones, not your tuning.</li>
              </ul>
              <p className="text-xs text-amber-300/80 mt-3">
                This is not a medical hearing test. Consumer hardware can't
                measure absolute thresholds (dB HL) — results only show how your
                sensitivity <em>compares across frequencies</em>, including your
                headphones' own response.
              </p>
              <div className="mt-5 flex gap-3 justify-end">
                <button
                  type="button"
                  onClick={handleClose}
                  className="rounded-lg border border-white/12 px-4 py-2 text-sm"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setStage("test");
                    setStep(0);
                    setEar("L");
                    setDbLevel(START_DB);
                  }}
                  className="rounded-lg border border-cyan/60 bg-cyan/15 text-cyan px-4 py-2 text-sm font-semibold"
                >
                  Start test
                </button>
              </div>
            </div>
          )}

          {stage === "test" && (
            <div>
              <div className="flex items-center justify-between text-[11px] uppercase tracking-widest text-dim">
                <span className={ear === "L" ? "text-cyan" : "text-plasma"}>
                  {ear === "L" ? "◀ LEFT ear" : "RIGHT ear ▶"}
                </span>
                <span>
                  step {step + 1 + (ear === "R" ? FREQS.length : 0)} / {FREQS.length * 2}
                </span>
              </div>
              <div className="mt-3 text-4xl font-mono font-bold text-cyan text-center">
                {FREQS[step]} Hz
              </div>
              <div className="mt-4 text-center text-sm text-white/80">
                Raise the slider until you can <em>just</em> hear the tone.
              </div>
              <div className="mt-4 px-2">
                <input
                  type="range"
                  min={START_DB}
                  max={MAX_DB}
                  step={1}
                  value={dbLevel}
                  onChange={(e) => setDbLevel(Number(e.target.value))}
                  className="w-full accent-cyan h-8"
                />
                <div className="flex items-center justify-between text-[11px] font-mono text-dim mt-1">
                  <span>{START_DB} dBFS (silent)</span>
                  <span className="text-cyan">{dbLevel} dBFS</span>
                  <span>{MAX_DB} dBFS (loud)</span>
                </div>
              </div>
              <div className="mt-5 grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => record(null)}
                  className="rounded-lg border border-white/15 text-white/75 px-3 py-2.5 text-sm hover:bg-white/5"
                >
                  Can't hear it — skip
                </button>
                <button
                  type="button"
                  onClick={() => record(dbLevel)}
                  className="rounded-lg border border-cyan/60 bg-cyan/15 text-cyan px-3 py-2.5 text-sm font-semibold"
                >
                  I can hear it
                </button>
              </div>
            </div>
          )}

          {stage === "done" && (
            <div>
              <div className="text-sm text-white/85 mb-3">
                Your quietest audible level per ear. Higher points = better
                relative sensitivity; points near the bottom needed much more
                level than your 1 kHz reference.
              </div>

              <AudiogramChart left={left} right={right} />

              {comp ? (
                <div className="mt-4">
                  <div className="text-[11px] text-dim leading-relaxed">
                    Suggested compensation moves bands by{" "}
                    <span className="text-white/75">half</span> the measured
                    relative difference — boosts capped at +{MAX_BOOST_DB} dB,
                    cuts at −{MAX_CUT_DB} dB. Full correction tends to sound harsh
                    and costs headroom. Apply replaces those EQ sliders; other
                    knobs stay.
                  </div>
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {(Object.keys(comp.bandDb) as FriendlyKey[])
                      .filter((k) => Math.abs(comp.bandDb[k] ?? 0) >= 0.25)
                      .map((k) => {
                        const db = comp.bandDb[k]!;
                        const meta = SOUND_PARAM_META.find((m) => m.key === k);
                        return (
                          <span
                            key={k}
                            className="rounded-full border border-white/12 px-2 py-0.5 text-[10px] font-mono"
                            style={{ color: meta?.color }}
                          >
                            {meta?.label ?? k} {db > 0 ? "+" : ""}{db.toFixed(1)} dB
                          </span>
                        );
                      })}
                  </div>
                </div>
              ) : (
                <p className="mt-4 text-xs text-amber-300/80">
                  Not enough frequencies were heard to build a reliable
                  compensation — try again in a quieter room or at a higher
                  listening volume.
                </p>
              )}

              <div className="mt-5 flex flex-wrap gap-3 justify-end items-center">
                {comp && (
                  <button
                    type="button"
                    onClick={toggleCompPreview}
                    className={`rounded-lg border px-4 py-2 text-sm transition ${
                      compPreview
                        ? "border-plasma/60 bg-plasma/15 text-plasma"
                        : "border-white/15 text-white/75 hover:bg-white/5"
                    }`}
                    title="Toggle the compensation on/off while music plays to hear the difference"
                  >
                    {compPreview ? "● Previewing — tap for original" : "A/B preview"}
                  </button>
                )}
                <button
                  type="button"
                  onClick={handleClose}
                  className="rounded-lg border border-white/12 px-4 py-2 text-sm"
                >
                  Keep current EQ
                </button>
                <button
                  type="button"
                  onClick={onApplyCompensation}
                  disabled={!comp}
                  title="Replace those EQ sliders with the suggested compensation — other knobs stay"
                  className="rounded-lg border border-cyan/60 bg-cyan/15 text-cyan px-4 py-2 text-sm font-semibold disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  Apply as EQ
                </button>
              </div>
            </div>
          )}
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

/**
 * Audiogram-style per-ear chart: frequency left→right, quietest audible level
 * top→bottom (top = heard at a whisper, bottom = needed it loud). Skipped
 * frequencies render as ✕ at the floor.
 */
function AudiogramChart({ left, right }: { left: Thresholds; right: Thresholds }) {
  const W = 520;
  const H = 170;
  const padL = 34;
  const padR = 10;
  const padT = 10;
  const padB = 24;
  const x = (i: number) => padL + (i / (FREQS.length - 1)) * (W - padL - padR);
  const y = (db: number) =>
    padT + ((db - START_DB) / (MAX_DB - START_DB)) * (H - padT - padB);

  const buildLine = (th: Thresholds) => {
    let d = "";
    FREQS.forEach((f, i) => {
      const v = th[f];
      if (v === undefined) return;
      d += `${d === "" ? "M" : "L"}${x(i).toFixed(1)},${y(v).toFixed(1)} `;
    });
    return d.trim();
  };

  const gridDbs = [-70, -50, -30, -15];

  return (
    <div>
      <svg viewBox={`0 0 ${W} ${H}`} className="w-full">
        {gridDbs.map((db) => (
          <g key={db}>
            <line
              x1={padL} x2={W - padR} y1={y(db)} y2={y(db)}
              stroke="rgba(255,255,255,0.07)"
            />
            <text x={padL - 5} y={y(db) + 3} fontSize={8} fill="rgba(255,255,255,0.4)" textAnchor="end">
              {db}
            </text>
          </g>
        ))}
        {FREQS.map((f, i) => (
          <text
            key={f}
            x={x(i)} y={H - 8}
            fontSize={8.5}
            fill="rgba(255,255,255,0.5)"
            textAnchor="middle"
            className="font-mono"
          >
            {fmtFreq(f)}
          </text>
        ))}

        <path d={buildLine(left)} fill="none" stroke="rgba(34,232,255,0.8)" strokeWidth={1.5} />
        <path d={buildLine(right)} fill="none" stroke="rgba(255,43,214,0.8)" strokeWidth={1.5} />

        {FREQS.map((f, i) => {
          const l = left[f];
          const r = right[f];
          return (
            <g key={f}>
              {l !== undefined ? (
                <circle cx={x(i)} cy={y(l)} r={3.5} fill="rgba(34,232,255,0.9)" />
              ) : (
                <text x={x(i) - 4} y={y(MAX_DB) + 3} fontSize={9} fill="rgba(34,232,255,0.5)">✕</text>
              )}
              {r !== undefined ? (
                <rect x={x(i) - 3} y={y(r) - 3} width={6} height={6} fill="rgba(255,43,214,0.9)" />
              ) : (
                <text x={x(i) + 2} y={y(MAX_DB) + 3} fontSize={9} fill="rgba(255,43,214,0.5)">✕</text>
              )}
            </g>
          );
        })}
      </svg>
      <div className="flex items-center gap-4 text-[10px] text-dim mt-1">
        <span className="flex items-center gap-1.5">
          <span className="inline-block w-2.5 h-2.5 rounded-full" style={{ background: "rgba(34,232,255,0.9)" }} />
          Left ear
        </span>
        <span className="flex items-center gap-1.5">
          <span className="inline-block w-2.5 h-2.5" style={{ background: "rgba(255,43,214,0.9)" }} />
          Right ear
        </span>
        <span>✕ = not heard at max level</span>
      </div>
    </div>
  );
}
