/** Remaining curated preset rows for regen-curated-presets.mjs */

const arpCfg = (mode, bpm, division, octaves, gate) => ({ enabled: true, mode, bpm, division, octaves, gate });

export const fxs = [
  ["fc-fx-noise-sweep", "Noise Sweep Riser", "Filtered noise sweep riser", "FX",
    { oscATable: "saw", oscALevel: 0.3, noiseLevel: 0.7, filterType: "bandpass", filterCutoff: 800, filterResonance: 0.4, ampAttack: 0.8, ampDecay: 0.5, ampSustain: 0.8, ampRelease: 0.8, lfo1Wave: "sawtooth", lfo1Rate: 0.15, lfo1Depth: 0.7, lfo1Dest: "filter" }],
  ["fc-fx-laser-zap", "Laser Zap", "Classic laser zap FX", "FX",
    { oscATable: "saw", oscALevel: 0.8, filterCutoff: 5000, filterEnvAmount: 0.9, filtDecay: 0.15, ampAttack: 0.001, ampDecay: 0.25, ampSustain: 0.05, ampRelease: 0.15, pitchEnvAmount: 0.6, pitchEnvTime: 0.2 }],
  ["fc-fx-impact-boom", "Impact Boom", "Cinematic impact boom", "FX",
    { oscATable: "basic", oscALevel: 0.7, oscAOctave: -2, noiseLevel: 0.4, subLevel: 0.5, filterCutoff: 400, ampAttack: 0.001, ampDecay: 0.8, ampSustain: 0.1, ampRelease: 0.9, reverbMix: 0.45, punch: 0.6 }],
  ["fc-fx-whoosh", "Air Whoosh", "Air whoosh pass-by", "FX",
    { oscALevel: 0.2, noiseLevel: 0.8, filterType: "bandpass", filterCutoff: 2000, filterResonance: 0.3, ampAttack: 0.15, ampDecay: 0.6, ampSustain: 0.3, ampRelease: 0.7, stereoWidth: 1.3, lfo1Rate: 0.4, lfo1Depth: 0.5, lfo1Dest: "pan" }],
  ["fc-fx-glitch-stutter", "Glitch Stutter", "Glitchy stutter FX", "FX",
    { oscATable: "pulse", oscAPos: 0.3, oscALevel: 0.65, noiseLevel: 0.25, filterCutoff: 3000, ampAttack: 0.001, ampDecay: 0.08, ampSustain: 0.2, ampRelease: 0.08, gateOn: true, gateRate: 16, gateDepth: 1, drive: 0.3 }],
  ["fc-fx-alarm-pulse", "Alarm Pulse", "Alarm pulse siren", "FX",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.75, filterCutoff: 2800, ampAttack: 0.01, ampDecay: 0.2, ampSustain: 0.8, ampRelease: 0.2, lfo1Wave: "square", lfo1Rate: 6, lfo1Depth: 0.6, lfo1Dest: "pitch" }],
  ["fc-fx-reverse-swell", "Reverse Swell", "Reverse-like swell FX", "FX",
    { oscATable: "saw", oscALevel: 0.55, noiseLevel: 0.3, filterCutoff: 1800, ampAttack: 1.2, ampDecay: 0.3, ampSustain: 0.7, ampRelease: 0.2, reverbMix: 0.5 }],
  ["fc-fx-metallic-hit", "Metallic Hit", "Metallic industrial hit", "FX",
    { oscATable: "metallic", oscALevel: 0.7, oscBTable: "bell", oscBLevel: 0.4, fmAmount: 0.4, filterCutoff: 4000, ampAttack: 0.001, ampDecay: 0.4, ampSustain: 0.05, ampRelease: 0.5, reverbMix: 0.3, drive: 0.25 }],
  ["fc-fx-sub-drop", "Sub Drop", "Falling sub drop FX", "FX",
    { oscATable: "basic", oscALevel: 0.8, oscAOctave: -2, subLevel: 0.6, filterCutoff: 500, ampAttack: 0.01, ampDecay: 0.9, ampSustain: 0.2, ampRelease: 0.6, pitchEnvAmount: -0.7, pitchEnvTime: 0.8 }],
  ["fc-fx-bitcrush-rain", "Bitcrush Rain", "Bitcrushed rain texture", "FX",
    { noiseLevel: 0.7, oscALevel: 0.2, filterType: "highpass", filterCutoff: 2500, ampAttack: 0.3, ampDecay: 0.5, ampSustain: 0.8, ampRelease: 0.8, cassetteGen: 0.6, hiss: 0.4 }],
  ["fc-fx-phone-ring", "Phone Ring Tone", "Retro phone ring tone", "FX",
    { oscATable: "basic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.5, oscBDetune: 0.02, filterCutoff: 3000, ampAttack: 0.001, ampDecay: 0.15, ampSustain: 0.7, ampRelease: 0.1, lfo1Wave: "square", lfo1Rate: 5, lfo1Depth: 0.4, lfo1Dest: "volume" }],
  ["fc-fx-wind-howl", "Wind Howl", "Howling wind texture", "FX",
    { noiseLevel: 0.85, oscALevel: 0.15, filterType: "bandpass", filterCutoff: 900, filterResonance: 0.5, ampAttack: 0.5, ampDecay: 0.6, ampSustain: 0.9, ampRelease: 1.2, lfo1Rate: 0.25, lfo1Depth: 0.55, lfo1Dest: "filter", reverbMix: 0.4 }],
  ["fc-fx-sparkle-burst", "Sparkle Burst", "Short sparkle burst FX", "FX",
    { oscATable: "bell", oscALevel: 0.6, noiseLevel: 0.2, filterCutoff: 6000, ampAttack: 0.001, ampDecay: 0.35, ampSustain: 0.05, ampRelease: 0.5, reverbMix: 0.4, delayMix: 0.2 }],
  ["fc-fx-drone-horror", "Horror Drone", "Uneasy horror drone FX", "FX",
    { oscATable: "saw", oscALevel: 0.5, oscBTable: "saw", oscBLevel: 0.45, oscBDetune: 0.2, filterCutoff: 600, ampAttack: 1.0, ampDecay: 0.8, ampSustain: 1, ampRelease: 2, lfo1Rate: 0.08, lfo1Depth: 0.4, lfo1Dest: "pitch", reverbMix: 0.45 }],
  ["fc-fx-tape-stop", "Tape Stop", "Tape-stop pitch dive", "FX",
    { oscATable: "saw", oscALevel: 0.7, filterCutoff: 2800, ampAttack: 0.01, ampDecay: 0.5, ampSustain: 0.6, ampRelease: 0.8, pitchEnvAmount: -0.9, pitchEnvTime: 0.6, cassetteGen: 0.5, wowFlutter: 0.4 }],
  ["fc-fx-radio-static", "Radio Static", "Tuned radio static FX", "FX",
    { noiseLevel: 0.8, oscATable: "pulse", oscALevel: 0.25, filterType: "bandpass", filterCutoff: 1600, filterResonance: 0.6, ampAttack: 0.05, ampDecay: 0.3, ampSustain: 0.7, ampRelease: 0.4, hiss: 0.5, cassetteGen: 0.3 }],
  ["fc-fx-power-down", "Power Down", "Machine power-down FX", "FX",
    { oscATable: "saw", oscALevel: 0.7, filterCutoff: 3500, ampAttack: 0.001, ampDecay: 1.0, ampSustain: 0.1, ampRelease: 0.5, pitchEnvAmount: -0.8, pitchEnvTime: 1.0, lfo1Rate: 8, lfo1Depth: 0.3, lfo1Dest: "filter" }],
  ["fc-fx-crystal-shatter", "Crystal Shatter", "Shattering crystal FX", "FX",
    { oscATable: "bell", oscALevel: 0.55, oscBTable: "metallic", oscBLevel: 0.45, noiseLevel: 0.25, filterCutoff: 5000, ampAttack: 0.001, ampDecay: 0.5, ampSustain: 0.05, ampRelease: 0.7, reverbMix: 0.45 }],
  ["fc-fx-heartbeat", "Heartbeat Pulse", "Deep heartbeat pulse FX", "FX",
    { oscATable: "basic", oscALevel: 0.8, oscAOctave: -2, subLevel: 0.5, filterCutoff: 300, ampAttack: 0.001, ampDecay: 0.25, ampSustain: 0.05, ampRelease: 0.3, punch: 0.7 }],
  ["fc-fx-space-chirp", "Space Chirp", "Sci-fi space chirp", "FX",
    { oscATable: "basic", oscALevel: 0.65, oscAOctave: 2, filterCutoff: 4500, ampAttack: 0.001, ampDecay: 0.3, ampSustain: 0.2, ampRelease: 0.4, pitchEnvAmount: 0.5, pitchEnvTime: 0.25, delayMix: 0.3, reverbMix: 0.35 }],
];

export const atmos = [
  ["fc-atmos-fog-bank", "Fog Bank", "Thick fog bank atmosphere", "Atmos",
    { oscATable: "saw", oscALevel: 0.4, noiseLevel: 0.35, filterCutoff: 900, ampAttack: 1.5, ampDecay: 1, ampSustain: 1, ampRelease: 3, reverbSize: 5, reverbMix: 0.6, chorusMix: 0.3 }],
  ["fc-atmos-starfield", "Starfield", "Twinkling starfield bed", "Atmos",
    { oscATable: "bell", oscALevel: 0.35, oscBTable: "harmonic", oscBLevel: 0.4, noiseLevel: 0.15, filterCutoff: 4000, ampAttack: 1.2, ampDecay: 0.8, ampSustain: 0.95, ampRelease: 2.5, reverbMix: 0.55, delayMix: 0.25, airHigh: 0.4, airAmount: 0.4 }],
  ["fc-atmos-underwater", "Underwater Room", "Muffled underwater room", "Atmos",
    { oscATable: "basic", oscALevel: 0.5, filterCutoff: 600, filterResonance: 0.3, ampAttack: 1.0, ampDecay: 0.8, ampSustain: 1, ampRelease: 2.2, reverbMix: 0.5, chorusMix: 0.4, lfo1Rate: 0.15, lfo1Depth: 0.3, lfo1Dest: "filter" }],
  ["fc-atmos-city-hum", "City Hum", "Distant city electrical hum", "Atmos",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.35, oscBTable: "saw", oscBLevel: 0.25, oscBDetune: 0.15, noiseLevel: 0.2, filterCutoff: 700, ampAttack: 1.0, ampDecay: 0.8, ampSustain: 1, ampRelease: 2, cassetteGen: 0.25, hiss: 0.15 }],
  ["fc-atmos-aurora", "Aurora Veil", "Aurora veil shimmer", "Atmos",
    { oscATable: "harmonic", oscALevel: 0.45, oscBTable: "bell", oscBLevel: 0.35, filterCutoff: 3200, ampAttack: 1.4, ampDecay: 0.8, ampSustain: 1, ampRelease: 2.8, phaserRate: 0.1, phaserDepth: 0.6, phaserMix: 0.4, reverbMix: 0.55 }],
  ["fc-atmos-cave-drip", "Cave Drip", "Damp cave with distant drips", "Atmos",
    { oscATable: "basic", oscALevel: 0.3, noiseLevel: 0.25, filterCutoff: 1200, ampAttack: 0.8, ampDecay: 0.6, ampSustain: 0.9, ampRelease: 2, reverbSize: 6, reverbMix: 0.65, delayMix: 0.3 }],
  ["fc-atmos-radio-space", "Radio Space", "Deep-space radio wash", "Atmos",
    { noiseLevel: 0.5, oscATable: "pulse", oscALevel: 0.25, filterType: "bandpass", filterCutoff: 1400, filterResonance: 0.4, ampAttack: 1.0, ampDecay: 0.8, ampSustain: 1, ampRelease: 2.5, hiss: 0.35, reverbMix: 0.5 }],
  ["fc-atmos-warm-dust", "Warm Dust", "Warm dusty loft atmosphere", "Atmos",
    { oscATable: "saw", oscALevel: 0.4, filterCutoff: 1400, ampAttack: 1.2, ampDecay: 0.8, ampSustain: 1, ampRelease: 2.2, cassetteGen: 0.4, wowFlutter: 0.2, hiss: 0.2, chorusMix: 0.25, reverbMix: 0.4 }],
  ["fc-atmos-ice-field", "Ice Field", "Frozen ice field texture", "Atmos",
    { oscATable: "bell", oscALevel: 0.35, noiseLevel: 0.3, filterType: "highpass", filterCutoff: 1500, ampAttack: 1.3, ampDecay: 0.8, ampSustain: 0.95, ampRelease: 2.5, reverbMix: 0.55, airHigh: 0.5, airAmount: 0.45 }],
  ["fc-atmos-pulse-engine", "Pulse Engine Room", "Slow pulse engine room", "Atmos",
    { oscATable: "saw", oscALevel: 0.45, subLevel: 0.3, filterCutoff: 500, ampAttack: 0.8, ampDecay: 0.6, ampSustain: 1, ampRelease: 1.8, lfo1Rate: 0.5, lfo1Depth: 0.45, lfo1Dest: "volume", reverbMix: 0.35 }],
  ["fc-atmos-choir-void", "Choir Void", "Distant choir in the void", "Atmos",
    { oscATable: "vocal", oscALevel: 0.45, oscBTable: "vocal", oscBPos: 0.6, oscBLevel: 0.35, oscBDetune: 0.1, filterCutoff: 2000, ampAttack: 1.5, ampDecay: 1, ampSustain: 1, ampRelease: 3, reverbSize: 5.5, reverbMix: 0.6 }],
  ["fc-atmos-neon-rain", "Neon Rain", "Neon rain on glass", "Atmos",
    { oscATable: "pulse", oscAPos: 0.3, oscALevel: 0.35, noiseLevel: 0.35, filterCutoff: 2800, ampAttack: 0.9, ampDecay: 0.7, ampSustain: 0.9, ampRelease: 2, delayMix: 0.35, reverbMix: 0.45, phaserMix: 0.25 }],
  ["fc-atmos-granular-ash", "Granular Ash", "Granular ash cloud", "Atmos",
    { oscATable: "metallic", oscALevel: 0.35, noiseLevel: 0.4, filterCutoff: 1600, ampAttack: 1.1, ampDecay: 0.8, ampSustain: 1, ampRelease: 2.4, spectralMode: "freeze", spectralAmount: 0.4, spectralMix: 0.45, reverbMix: 0.5 }],
  ["fc-atmos-soft-pad-air", "Soft Pad Air", "Soft airy pad atmosphere", "Atmos",
    { oscATable: "saw", oscALevel: 0.45, oscBTable: "basic", oscBLevel: 0.35, filterCutoff: 2600, ampAttack: 1.0, ampDecay: 0.7, ampSustain: 0.95, ampRelease: 2.0, chorusMix: 0.35, reverbMix: 0.5, airHigh: 0.35, airAmount: 0.4 }],
  ["fc-atmos-machine-breath", "Machine Breath", "Breathing machine atmosphere", "Atmos",
    { oscATable: "saw", oscALevel: 0.4, noiseLevel: 0.3, filterCutoff: 1100, ampAttack: 0.6, ampDecay: 0.5, ampSustain: 0.9, ampRelease: 1.5, lfo1Rate: 0.2, lfo1Depth: 0.5, lfo1Dest: "filter", cassetteGen: 0.2 }],
  ["fc-atmos-moonlit", "Moonlit Field", "Moonlit open field", "Atmos",
    { oscATable: "harmonic", oscALevel: 0.4, oscBTable: "basic", oscBLevel: 0.3, filterCutoff: 2400, ampAttack: 1.3, ampDecay: 0.8, ampSustain: 1, ampRelease: 2.6, chorusMix: 0.3, reverbMix: 0.55, delayMix: 0.2 }],
  ["fc-atmos-static-veil", "Static Veil", "Static electricity veil", "Atmos",
    { noiseLevel: 0.65, oscALevel: 0.2, filterType: "highpass", filterCutoff: 3000, ampAttack: 0.7, ampDecay: 0.5, ampSustain: 0.9, ampRelease: 1.8, hiss: 0.45, reverbMix: 0.35 }],
  ["fc-atmos-deep-abyss", "Deep Abyss", "Bottomless deep abyss", "Atmos",
    { oscATable: "saw", oscALevel: 0.5, oscAOctave: -1, subLevel: 0.4, filterCutoff: 350, ampAttack: 1.6, ampDecay: 1, ampSustain: 1, ampRelease: 3.5, reverbMix: 0.55 }],
  ["fc-atmos-glitter-dust", "Glitter Dust", "Floating glitter dust", "Atmos",
    { oscATable: "bell", oscALevel: 0.35, oscBTable: "harmonic", oscBLevel: 0.3, noiseLevel: 0.15, filterCutoff: 5000, ampAttack: 1.0, ampDecay: 0.7, ampSustain: 0.9, ampRelease: 2.2, delayMix: 0.3, reverbMix: 0.5, airHigh: 0.45, airAmount: 0.5 }],
  ["fc-atmos-hollow-hall", "Hollow Hall", "Hollow hall resonance", "Atmos",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.4, filterCutoff: 1500, ampAttack: 1.1, ampDecay: 0.8, ampSustain: 1, ampRelease: 2.5, reverbSize: 6, reverbMix: 0.65, phaserMix: 0.3 }],
];

export const vintage = [
  ["fc-vintage-cassette-lead", "Cassette Lead Warmth", "Warm cassette-saturated lead", "Vintage",
    { oscATable: "saw", oscALevel: 0.7, filterCutoff: 2200, ampAttack: 0.02, ampDecay: 0.3, ampSustain: 0.75, ampRelease: 0.3, cassetteGen: 0.55, wowFlutter: 0.25, hiss: 0.2, mono: true }],
  ["fc-vintage-vhs-pad", "VHS Pad Glow", "VHS-colored glowing pad", "Vintage",
    { oscATable: "saw", oscALevel: 0.55, oscBTable: "pulse", oscBLevel: 0.4, filterCutoff: 2000, ampAttack: 0.7, ampDecay: 0.5, ampSustain: 0.9, ampRelease: 1.4, cassetteGen: 0.45, wowFlutter: 0.35, hiss: 0.25, chorusMix: 0.3, reverbMix: 0.35 }],
  ["fc-vintage-radio-keys", "AM Radio Keys", "AM-radio filtered keys", "Vintage",
    { oscATable: "basic", oscALevel: 0.65, filterType: "bandpass", filterCutoff: 1600, filterResonance: 0.4, ampAttack: 0.005, ampDecay: 0.7, ampSustain: 0.35, ampRelease: 0.5, cassetteGen: 0.35, hiss: 0.3 }],
  ["fc-vintage-tape-bass", "Tape Bass Thump", "Tape-saturated bass thump", "Vintage",
    { oscATable: "saw", oscALevel: 0.75, oscAOctave: -1, subLevel: 0.35, filterCutoff: 900, ampAttack: 0.005, ampDecay: 0.4, ampSustain: 0.5, ampRelease: 0.3, cassetteGen: 0.5, wowFlutter: 0.15, mono: true }],
  ["fc-vintage-vinyl-ep", "Vinyl EP Crackle", "Vinyl-crackled electric piano", "Vintage",
    { oscATable: "bell", oscALevel: 0.45, oscBTable: "basic", oscBLevel: 0.5, noiseLevel: 0.12, filterCutoff: 2600, ampAttack: 0.003, ampDecay: 0.9, ampSustain: 0.3, ampRelease: 0.6, cassetteGen: 0.4, hiss: 0.35, chorusMix: 0.25 }],
  ["fc-vintage-warble-organ", "Warble Organ", "Wow/flutter warbling organ", "Vintage",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.5, oscBTable: "pulse", oscBPos: 0.25, oscBLevel: 0.4, oscBOctave: 1, filterCutoff: 3000, ampAttack: 0.02, ampDecay: 0.2, ampSustain: 0.9, ampRelease: 0.2, wowFlutter: 0.5, cassetteGen: 0.3 }],
  ["fc-vintage-dusty-pluck", "Dusty Pluck", "Dusty aged pluck", "Vintage",
    { oscATable: "pulse", oscAPos: 0.35, oscALevel: 0.7, filterCutoff: 2400, ampAttack: 0.001, ampDecay: 0.25, ampSustain: 0.08, ampRelease: 0.2, cassetteGen: 0.5, hiss: 0.25 }],
  ["fc-vintage-boombox", "Boombox Bass", "Portable boombox bass", "Vintage",
    { oscATable: "saw", oscALevel: 0.7, subLevel: 0.4, filterCutoff: 1100, ampAttack: 0.01, ampDecay: 0.35, ampSustain: 0.55, ampRelease: 0.25, cassetteGen: 0.4, drive: 0.25, mono: true }],
  ["fc-vintage-film-score", "Film Score Strings", "Aged film-score string pad", "Vintage",
    { oscATable: "saw", oscALevel: 0.55, oscBTable: "saw", oscBLevel: 0.45, oscBDetune: 0.1, filterCutoff: 1800, ampAttack: 0.8, ampDecay: 0.6, ampSustain: 0.9, ampRelease: 1.6, cassetteGen: 0.35, wowFlutter: 0.2, reverbMix: 0.45 }],
  ["fc-vintage-chatty-radio", "Chatty Radio", "Chatty talk-radio texture", "Vintage",
    { oscATable: "vocal", oscAPos: 0.4, oscALevel: 0.55, noiseLevel: 0.2, filterType: "bandpass", filterCutoff: 1800, ampAttack: 0.1, ampDecay: 0.4, ampSustain: 0.7, ampRelease: 0.4, hiss: 0.4, cassetteGen: 0.3 }],
  ["fc-vintage-soft-synth", "Soft 80s Synth", "Soft 80s synth poly", "Vintage",
    { oscATable: "saw", oscALevel: 0.6, oscBTable: "pulse", oscBLevel: 0.4, filterCutoff: 2800, ampAttack: 0.05, ampDecay: 0.4, ampSustain: 0.75, ampRelease: 0.5, chorusMix: 0.4, cassetteGen: 0.2, reverbMix: 0.25 }],
  ["fc-vintage-broken-speaker", "Broken Speaker", "Broken speaker grit", "Vintage",
    { oscATable: "saw", oscALevel: 0.7, filterCutoff: 1600, ampAttack: 0.01, ampDecay: 0.3, ampSustain: 0.7, ampRelease: 0.25, drive: 0.55, cassetteGen: 0.45, hiss: 0.3, mono: true }],
  ["fc-vintage-lullaby-box", "Lullaby Music Box", "Aged music-box lullaby", "Vintage",
    { oscATable: "bell", oscALevel: 0.65, oscAOctave: 1, filterCutoff: 4000, ampAttack: 0.001, ampDecay: 0.5, ampSustain: 0.1, ampRelease: 0.6, wowFlutter: 0.3, cassetteGen: 0.25, reverbMix: 0.3 }],
  ["fc-vintage-garage-band", "Garage Band Keys", "Garage-band keyboard", "Vintage",
    { oscATable: "basic", oscALevel: 0.65, filterCutoff: 2200, ampAttack: 0.005, ampDecay: 0.6, ampSustain: 0.4, ampRelease: 0.4, cassetteGen: 0.4, drive: 0.2, chorusMix: 0.15 }],
  ["fc-vintage-night-drive", "Night Drive Pad", "Night-drive neon pad", "Vintage",
    { oscATable: "saw", oscALevel: 0.55, oscBTable: "saw", oscBLevel: 0.4, oscBDetune: 0.08, filterCutoff: 2400, ampAttack: 0.6, ampDecay: 0.5, ampSustain: 0.9, ampRelease: 1.3, chorusMix: 0.35, cassetteGen: 0.25, delayMix: 0.2, reverbMix: 0.35 }],
  ["fc-vintage-shortwave", "Shortwave Ghost", "Shortwave ghost signal", "Vintage",
    { oscATable: "pulse", oscAPos: 0.4, oscALevel: 0.4, noiseLevel: 0.35, filterType: "bandpass", filterCutoff: 1200, filterResonance: 0.5, ampAttack: 0.4, ampDecay: 0.5, ampSustain: 0.8, ampRelease: 1.0, hiss: 0.45, wowFlutter: 0.4 }],
  ["fc-vintage-analog-brass", "Analog Brass", "Vintage analog brass", "Vintage",
    { oscATable: "saw", oscALevel: 0.65, oscBTable: "saw", oscBLevel: 0.5, oscBDetune: 0.06, filterCutoff: 2000, filterResonance: 0.25, filterEnvAmount: 0.4, ampAttack: 0.08, ampDecay: 0.35, ampSustain: 0.75, ampRelease: 0.35, cassetteGen: 0.2 }],
  ["fc-vintage-faded-photo", "Faded Photo Pad", "Faded photograph soft pad", "Vintage",
    { oscATable: "basic", oscALevel: 0.5, oscBTable: "saw", oscBLevel: 0.35, filterCutoff: 1600, ampAttack: 0.9, ampDecay: 0.6, ampSustain: 0.95, ampRelease: 1.8, cassetteGen: 0.5, wowFlutter: 0.25, hiss: 0.2, reverbMix: 0.4 }],
  ["fc-vintage-arcade-lobby", "Arcade Lobby", "80s arcade lobby ambience", "Vintage",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.4, oscBTable: "basic", oscBLevel: 0.3, oscBOctave: 1, noiseLevel: 0.15, filterCutoff: 2600, ampAttack: 0.3, ampDecay: 0.4, ampSustain: 0.8, ampRelease: 0.8, cassetteGen: 0.3, hiss: 0.2, chorusMix: 0.2 }],
  ["fc-vintage-worn-strings", "Worn Strings", "Worn tape string ensemble", "Vintage",
    { oscATable: "saw", oscALevel: 0.55, oscBTable: "saw", oscBLevel: 0.5, oscBDetune: 0.12, unison: 3, unisonDetune: 0.15, filterCutoff: 1900, ampAttack: 0.7, ampDecay: 0.5, ampSustain: 0.9, ampRelease: 1.5, cassetteGen: 0.4, wowFlutter: 0.3, reverbMix: 0.4 }],
];

export const chips = [
  ["fc-chip-pulse-hero", "Pulse Hero", "Classic pulse hero lead", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, pulseDuty: 0.5, oscALevel: 0.8, filterCutoff: 5000, ampAttack: 0.001, ampDecay: 0.2, ampSustain: 0.6, ampRelease: 0.15, mono: true }],
  ["fc-chip-triangle-bass", "Triangle Bass Chip", "NES-style triangle bass", "Chip",
    { oscATable: "basic", oscALevel: 0.85, oscAOctave: -1, filterCutoff: 2000, ampAttack: 0.001, ampDecay: 0.25, ampSustain: 0.5, ampRelease: 0.15, mono: true }],
  ["fc-chip-noise-hat", "Noise Hat Chip", "Chip noise hi-hat", "Chip",
    { noiseLevel: 0.9, oscALevel: 0.1, filterType: "highpass", filterCutoff: 4000, ampAttack: 0.001, ampDecay: 0.08, ampSustain: 0.02, ampRelease: 0.05 }],
  ["fc-chip-duty-wobble", "Duty Wobble", "PWM duty-cycle wobble", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, pulseDuty: 0.5, oscALevel: 0.75, filterCutoff: 4000, ampAttack: 0.001, ampDecay: 0.25, ampSustain: 0.6, ampRelease: 0.2, lfo1Wave: "triangle", lfo1Rate: 6, lfo1Depth: 0.5, lfo1Dest: "filter", mono: true }],
  ["fc-chip-arp-run", "Chip Arp Run", "Classic chip arp run", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, pulseDuty: 0.25, oscALevel: 0.75, filterCutoff: 5500, ampAttack: 0.001, ampDecay: 0.12, ampSustain: 0.2, ampRelease: 0.08 }, arpCfg("up", 150, "1/16", 3, 0.75)],
  ["fc-chip-square-stab", "Square Stab", "Short square stab", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, pulseDuty: 0.5, oscALevel: 0.8, filterCutoff: 4500, ampAttack: 0.001, ampDecay: 0.12, ampSustain: 0.1, ampRelease: 0.08 }],
  ["fc-chip-vib-lead", "Vibrato Chip Lead", "Vibrato chip lead", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.75, filterCutoff: 4800, ampAttack: 0.001, ampDecay: 0.25, ampSustain: 0.65, ampRelease: 0.2, lfo1Wave: "sine", lfo1Rate: 5.5, lfo1Depth: 0.25, lfo1Dest: "pitch", mono: true }],
  ["fc-chip-oct-stack", "Octave Stack Chip", "Octave-stacked chip lead", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.55, oscBTable: "pulse", oscBPos: 0.5, oscBLevel: 0.5, oscBOctave: 1, filterCutoff: 5000, ampAttack: 0.001, ampDecay: 0.2, ampSustain: 0.6, ampRelease: 0.15 }],
  ["fc-chip-soft-triangle", "Soft Triangle Melody", "Soft triangle melody chip", "Chip",
    { oscATable: "basic", oscALevel: 0.7, filterCutoff: 3500, ampAttack: 0.01, ampDecay: 0.3, ampSustain: 0.7, ampRelease: 0.25 }],
  ["fc-chip-battle-lead", "Battle Lead", "Aggressive battle chip lead", "Chip",
    { oscATable: "pulse", oscAPos: 0.25, pulseDuty: 0.25, oscALevel: 0.8, filterCutoff: 5200, ampAttack: 0.001, ampDecay: 0.18, ampSustain: 0.55, ampRelease: 0.12, drive: 0.2, mono: true }],
  ["fc-chip-coin-blip", "Coin Blip", "Coin-collect blip", "Chip",
    { oscATable: "basic", oscALevel: 0.7, oscAOctave: 2, filterCutoff: 6000, ampAttack: 0.001, ampDecay: 0.15, ampSustain: 0.05, ampRelease: 0.1, pitchEnvAmount: 0.4, pitchEnvTime: 0.12 }],
  ["fc-chip-dungeon-drone", "Dungeon Drone", "Dark dungeon chip drone", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.5, oscBTable: "pulse", oscBLevel: 0.4, oscBDetune: 0.08, filterCutoff: 1800, ampAttack: 0.3, ampDecay: 0.4, ampSustain: 0.9, ampRelease: 0.8 }],
  ["fc-chip-powerup", "Power-Up Sweep", "Power-up pitch sweep", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.75, filterCutoff: 5000, ampAttack: 0.001, ampDecay: 0.35, ampSustain: 0.2, ampRelease: 0.2, pitchEnvAmount: 0.8, pitchEnvTime: 0.35 }],
  ["fc-chip-wave-channel", "Wave Channel Soft", "Soft wave-channel tone", "Chip",
    { oscATable: "basic", oscALevel: 0.65, oscBTable: "pulse", oscBPos: 0.5, oscBLevel: 0.35, filterCutoff: 3200, ampAttack: 0.005, ampDecay: 0.3, ampSustain: 0.7, ampRelease: 0.3, chorusMix: 0.1 }],
  ["fc-chip-noise-snare", "Noise Snare Chip", "Chip noise snare", "Chip",
    { noiseLevel: 0.85, oscALevel: 0.15, filterType: "bandpass", filterCutoff: 3000, filterResonance: 0.3, ampAttack: 0.001, ampDecay: 0.12, ampSustain: 0.02, ampRelease: 0.08 }],
  ["fc-chip-harmony-duo", "Harmony Duo Chip", "Two-voice chip harmony", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.55, oscBTable: "pulse", oscBPos: 0.5, oscBLevel: 0.5, filterCutoff: 4800, ampAttack: 0.001, ampDecay: 0.22, ampSustain: 0.6, ampRelease: 0.18 }],
  ["fc-chip-fast-arpeggio", "Fast Chip Arpeggio", "Blazing fast chip arpeggio", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, pulseDuty: 0.5, oscALevel: 0.75, filterCutoff: 5500, ampAttack: 0.001, ampDecay: 0.1, ampSustain: 0.15, ampRelease: 0.06 }, arpCfg("updown", 160, "1/32", 2, 0.7)],
  ["fc-chip-game-over", "Game Over Drone", "Somber game-over drone", "Chip",
    { oscATable: "pulse", oscAPos: 0.5, oscALevel: 0.55, oscAOctave: -1, filterCutoff: 2200, ampAttack: 0.2, ampDecay: 0.5, ampSustain: 0.8, ampRelease: 1.0 }],
  ["fc-chip-sparkle-lead", "Sparkle Chip Lead", "Bright sparkle chip lead", "Chip",
    { oscATable: "pulse", oscAPos: 0.125, pulseDuty: 0.125, oscALevel: 0.7, filterCutoff: 6000, ampAttack: 0.001, ampDecay: 0.2, ampSustain: 0.55, ampRelease: 0.15, airHigh: 0.3, airAmount: 0.3, mono: true }],
  ["fc-chip-menu-select", "Menu Select Blip", "UI menu select blip", "Chip",
    { oscATable: "basic", oscALevel: 0.7, oscAOctave: 1, filterCutoff: 4500, ampAttack: 0.001, ampDecay: 0.1, ampSustain: 0.05, ampRelease: 0.08 }],
];

export const fms = [
  ["fc-fm-electric-piano", "FM Electric Piano", "Classic FM electric piano tines", "FM",
    { oscATable: "basic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.55, fmAmount: 0.45, fmRatio: 1, filterCutoff: 3600, ampAttack: 0.002, ampDecay: 0.9, ampSustain: 0.3, ampRelease: 0.55, chorusMix: 0.25 }],
  ["fc-fm-bell-tower", "Bell Tower", "Church bell tower FM", "FM",
    { oscATable: "bell", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.5, fmAmount: 0.6, fmRatio: 3.5, filterCutoff: 5000, ampAttack: 0.001, ampDecay: 1.2, ampSustain: 0.15, ampRelease: 1.5, reverbMix: 0.45 }],
  ["fc-fm-bass-growl", "FM Bass Growl", "Growling FM bass", "FM",
    { oscATable: "basic", oscALevel: 0.8, oscBTable: "basic", oscBLevel: 0.6, oscAOctave: -1, fmAmount: 0.55, fmRatio: 2, filterCutoff: 1200, ampAttack: 0.005, ampDecay: 0.35, ampSustain: 0.5, ampRelease: 0.25, mono: true, drive: 0.2 }],
  ["fc-fm-pluck-mallet", "FM Mallet Pluck", "FM mallet pluck", "FM",
    { oscATable: "basic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.5, fmAmount: 0.5, fmRatio: 3, filterCutoff: 4200, ampAttack: 0.001, ampDecay: 0.4, ampSustain: 0.1, ampRelease: 0.35, reverbMix: 0.25 }],
  ["fc-fm-brass-stab", "FM Brass Stab", "FM brass stab", "FM",
    { oscATable: "saw", oscALevel: 0.65, oscBTable: "basic", oscBLevel: 0.5, fmAmount: 0.4, fmRatio: 1.5, filterCutoff: 2800, filterEnvAmount: 0.5, filtDecay: 0.2, ampAttack: 0.04, ampDecay: 0.3, ampSustain: 0.6, ampRelease: 0.25 }],
  ["fc-fm-glass-pad", "FM Glass Pad", "Glassy FM pad", "FM",
    { oscATable: "basic", oscALevel: 0.5, oscBTable: "bell", oscBLevel: 0.45, fmAmount: 0.35, fmRatio: 2.5, filterCutoff: 3800, ampAttack: 0.7, ampDecay: 0.5, ampSustain: 0.9, ampRelease: 1.5, reverbMix: 0.45, chorusMix: 0.3 }],
  ["fc-fm-metallic-hit", "FM Metallic Hit", "Metallic FM hit", "FM",
    { oscATable: "metallic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.55, fmAmount: 0.7, fmRatio: 4, filterCutoff: 4500, ampAttack: 0.001, ampDecay: 0.35, ampSustain: 0.05, ampRelease: 0.4, reverbMix: 0.3 }],
  ["fc-fm-soft-tines", "Soft FM Tines", "Soft FM tine keys", "FM",
    { oscATable: "basic", oscALevel: 0.65, oscBTable: "basic", oscBLevel: 0.4, fmAmount: 0.3, fmRatio: 1, filterCutoff: 2800, ampAttack: 0.005, ampDecay: 1.0, ampSustain: 0.35, ampRelease: 0.7, chorusMix: 0.3 }],
  ["fc-fm-screamer", "FM Screamer", "Aggressive FM scream lead", "FM",
    { oscATable: "basic", oscALevel: 0.75, oscBTable: "basic", oscBLevel: 0.6, fmAmount: 0.75, fmRatio: 5, filterCutoff: 4000, ampAttack: 0.01, ampDecay: 0.25, ampSustain: 0.65, ampRelease: 0.2, drive: 0.3, mono: true }],
  ["fc-fm-hollow-wood", "Hollow Wood FM", "Hollow wooden FM tone", "FM",
    { oscATable: "basic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.45, fmAmount: 0.4, fmRatio: 2.7, filterCutoff: 2200, ampAttack: 0.001, ampDecay: 0.5, ampSustain: 0.15, ampRelease: 0.4 }],
  ["fc-fm-organ-sparkle", "FM Organ Sparkle", "Sparkly FM organ", "FM",
    { oscATable: "basic", oscALevel: 0.55, oscBTable: "basic", oscBLevel: 0.4, oscBOctave: 1, fmAmount: 0.35, fmRatio: 2, filterCutoff: 3600, ampAttack: 0.02, ampDecay: 0.3, ampSustain: 0.85, ampRelease: 0.3, chorusMix: 0.2 }],
  ["fc-fm-deep-kick-tone", "FM Kick Tone", "Pitch-swept FM kick tone", "FM",
    { oscATable: "basic", oscALevel: 0.85, oscAOctave: -2, oscBTable: "basic", oscBLevel: 0.5, fmAmount: 0.5, fmRatio: 1, filterCutoff: 600, ampAttack: 0.001, ampDecay: 0.35, ampSustain: 0.05, ampRelease: 0.25, pitchEnvAmount: 0.7, pitchEnvTime: 0.2, punch: 0.5 }],
  ["fc-fm-crystal-chime", "Crystal Chime", "Crystal FM chime", "FM",
    { oscATable: "bell", oscALevel: 0.65, oscBTable: "basic", oscBLevel: 0.5, fmAmount: 0.55, fmRatio: 6, filterCutoff: 5500, ampAttack: 0.001, ampDecay: 0.8, ampSustain: 0.1, ampRelease: 1.0, reverbMix: 0.4, delayMix: 0.2 }],
  ["fc-fm-talkbox", "FM Talkbox", "Talkbox-ish FM voice", "FM",
    { oscATable: "vocal", oscALevel: 0.65, oscBTable: "basic", oscBLevel: 0.5, fmAmount: 0.45, fmRatio: 2, filterCutoff: 2400, ampAttack: 0.02, ampDecay: 0.3, ampSustain: 0.7, ampRelease: 0.3, mono: true }],
  ["fc-fm-cold-steel", "Cold Steel FM", "Cold steel FM lead", "FM",
    { oscATable: "metallic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.55, fmAmount: 0.6, fmRatio: 3, filterCutoff: 3800, ampAttack: 0.01, ampDecay: 0.3, ampSustain: 0.65, ampRelease: 0.25, mono: true }],
  ["fc-fm-warm-ep", "Warm FM EP", "Warm rounded FM EP", "FM",
    { oscATable: "basic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.45, fmAmount: 0.35, fmRatio: 1, filterCutoff: 2400, ampAttack: 0.003, ampDecay: 1.0, ampSustain: 0.4, ampRelease: 0.65, chorusMix: 0.35, cassetteGen: 0.1 }],
  ["fc-fm-chaos-stack", "Chaos Stack FM", "Chaotic stacked FM", "FM",
    { oscATable: "basic", oscALevel: 0.55, oscBTable: "bell", oscBLevel: 0.45, oscCTable: "metallic", oscCLevel: 0.3, fmAmount: 0.7, fmRatio: 4.5, fmBtoA: 0.35, filterCutoff: 4200, ampAttack: 0.01, ampDecay: 0.4, ampSustain: 0.55, ampRelease: 0.4, drive: 0.2 }],
  ["fc-fm-marimba", "FM Marimba", "FM marimba bars", "FM",
    { oscATable: "basic", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.5, fmAmount: 0.5, fmRatio: 2.5, filterCutoff: 3400, ampAttack: 0.001, ampDecay: 0.45, ampSustain: 0.08, ampRelease: 0.3, reverbMix: 0.2 }],
  ["fc-fm-space-gong", "Space Gong", "Huge space gong FM", "FM",
    { oscATable: "bell", oscALevel: 0.65, oscBTable: "metallic", oscBLevel: 0.5, fmAmount: 0.65, fmRatio: 1.4, filterCutoff: 3000, ampAttack: 0.001, ampDecay: 1.5, ampSustain: 0.2, ampRelease: 2.5, reverbSize: 5, reverbMix: 0.55 }],
  ["fc-fm-crossmod-forge", "Cross-Mod Forge", "Cross-mod forged metallic FM", "FM",
    { oscATable: "bell", oscALevel: 0.7, oscBTable: "basic", oscBLevel: 0.55, fmAmount: 0.55, fmRatio: 3, fmBtoA: 0.45, ringAmount: 0.2, filterCutoff: 4800, ampAttack: 0.002, ampDecay: 0.35, ampSustain: 0.45, ampRelease: 0.3, mono: true }],
];
