import { SYSTEM_PROMPT, assistantFromProtocol } from "./schema.mjs";

function rec(partial) {
  return {
    version: 1,
    tests_actually_run: false,
    split: partial.split || "train",
    system: SYSTEM_PROMPT,
    ...partial,
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: partial.task },
      { role: "assistant", content: assistantFromProtocol(partial.protocol) },
    ],
  };
}

export function seedRecords() {
  return [
    rec({
      id: "sft-resource-leak-bounce-001",
      task_type: "resource-leak",
      approval_class: "safe",
      split: "train",
      sources: [
        { path: "src/lib/bounceExport.ts", symbol: "captureProcessedPass", lineStart: 205, lineEnd: 214 },
        { path: "docs/audio-state-machine.md", lineStart: 130, lineEnd: 136 },
      ],
      tags: ["finally", "ScriptProcessorNode", "bounceExport"],
      task: "Task: Review how processed bounce capture attaches a live tap to the engine. If a capture is aborted or throws, can the ScriptProcessorNode stay connected? Show the required cleanup pattern. Do not change DSP.",
      protocol: {
        investigation: "Read docs/audio-state-machine.md §7 (export/record paths) and the live-capture function in src/lib/bounceExport.ts. Look for connect() without a matching disconnect, including abort and throw paths.",
        relevant_files: "- src/lib/bounceExport.ts — capture path, destinationTap.connect(proc)\n- docs/audio-state-machine.md §7\n- AGENTS.md invariant 4",
        confirmed_facts: "- AGENTS.md: live audio-tap nodes must be disconnected in finally blocks.\n- docs/audio-state-machine.md §7 states bounceExport.ts and fireStudio.ts attach a ScriptProcessorNode and disconnect it in finally.\n- bounceExport.ts around the capture loop uses a finally block that disconnects destinationTap→proc, proc, and sink, then restores player position.",
        competing_hypothesis: "Cleanup might only run on success, so AbortError or an early throw would leak the processor on destinationTap.",
        disproof: "Read the try/finally around the recording loop. disconnect() calls are in finally, not after the success path. An abort throw still enters finally. This disproves a success-only cleanup.",
        root_cause: "Not a leak in the current bounce capture path. The required pattern is already implemented: connect on the live tap, disconnect in finally on success, abort, and failure.",
        smallest_safe_fix: "No code change. Preserve the finally disconnects if this area is touched later. Do not attach additional analysers to destinationTap without the same cleanup.",
        expected_diff: "(no diff — current finally block is the canonical pattern)\n\nReference (do not delete):\ntry { engine.destinationTap.disconnect(proc); } catch {}\ntry { proc.disconnect(); } catch {}\ntry { sink.disconnect(); } catch {}",
        validation: "Would run after any edit to bounceExport capture: npm run typecheck, then npm run smoke (export cases). Tests were not run in this example.",
        final_report: "Investigated bounce live-tap cleanup. Confirmed finally-disconnect matches AGENTS.md invariant 4 and audio-state-machine §7. No patch. Residual risk: future capture paths must copy this pattern.",
      },
    }),
    rec({
      id: "sft-source-ownership-claim-001",
      task_type: "source-ownership",
      approval_class: "safe",
      split: "train",
      sources: [
        { path: "src/lib/sourceArbiter.ts", symbol: "claimSource", lineStart: 75, lineEnd: 93 },
        { path: "src/state/playerStore.ts", symbol: "play", lineStart: 891, lineEnd: 893 },
      ],
      tags: ["claimSource", "one-audible-source"],
      task: "Task: Playing a Library file while Fire Command is sequencing used to leave both audible. Where must ownership be decided, and what does a file claim stop? Do not add a new watcher.",
      protocol: {
        investigation: "AGENTS.md says only claimSource() may decide playback ownership. Read sourceArbiter.ts and the Library play path in playerStore.ts.",
        relevant_files: "- src/lib/sourceArbiter.ts — claimSource, stopFire, pauseAirspaceMedia\n- src/state/playerStore.ts — play() calls claimSource(\"file\")\n- src/state/fireSequencerStore.ts / fireCommandStore.ts — claimSource(\"fire\")\n- docs/audio-state-machine.md §3",
        confirmed_facts: "- claimSource(\"file\") calls stopFire() and pauseAirspaceMedia().\n- playerStore play() calls claimSource(\"file\") immediately before engine.resume/attachAudioElement.\n- Stop/pause paths must not claim (sourceArbiter header comment): no re-entrancy from pause.",
        competing_hypothesis: "Fire might keep playing because play() only pauses the HTML audio element and never notifies the sequencer.",
        disproof: "play() explicitly calls claimSource(\"file\"). claimSource(\"file\") dynamically imports fireSequencerStore.stop and fireCommandStore.panic when notes/arp are held. The competing hypothesis is false for the current play() path.",
        root_cause: "Ownership is centralized in claimSource. Double playback happens only if a play-ish path fails to claim. The Library play path does claim.",
        smallest_safe_fix: "No change to playerStore.play. If a NEW play-ish path is added, it must call claimSource with the correct SoundSource. Do not invent a second arbiter or a Mission State watcher for this.",
        expected_diff: "(no diff)",
        validation: "Would run npm run smoke (Fire handoff / no double playback cases) after any claimSource caller change. Tests were not run in this example.",
        final_report: "File playback already claims source. Teach: every play-ish action claims first; pause/stop never claim. Mission State is not the ownership API.",
      },
    }),
    rec({
      id: "sft-store-engine-bypass-001",
      task_type: "store-engine-sync",
      approval_class: "safe",
      split: "train",
      sources: [
        { path: "src/state/audioStore.ts", symbol: "setBypass", lineStart: 204, lineEnd: 216 },
        { path: "src/audio/AudioEngine.ts", symbol: "setBypass", lineStart: 943, lineEnd: 947 },
      ],
      tags: ["setBypass", "rewireFront", "stale-state"],
      task: "Task: A hotkey toggles FX bypass. How must the Zustand flag and the engine routing stay aligned? Who is allowed to change front routing gains?",
      protocol: {
        investigation: "Read AGENTS.md invariants 1 and 6. Read audioStore.setBypass and AudioEngine.setBypass / rewireFront.",
        relevant_files: "- src/state/audioStore.ts setBypass\n- src/audio/AudioEngine.ts setBypass, rewireFront\n- AGENTS.md HARD INVARIANTS 1 and 6",
        confirmed_facts: "- audioStore.setBypass does set({ bypass }) and getEngine().setBypass(bypass) in the same synchronous action.\n- AudioEngine.setBypass assigns this.bypass then calls this.rewireFront().\n- rewireFront is the only function that mutates front routing gains (engine private method; setters funnel through it).",
        competing_hypothesis: "The store might update first and the engine later in a microtask, leaving a window where UI says bypassed but the FX path is still audible.",
        disproof: "There is no await between set({ bypass }) and getEngine().setBypass(bypass). Engine.setBypass itself is synchronous and calls rewireFront() before returning. The Fire routeThroughFx alignment is a later dynamic import and is not the store↔engine bypass pair.",
        root_cause: "The required sync pattern is already present for bypass. Desync would mean a caller flipped only one side (bare engine call or bare store set).",
        smallest_safe_fix: "Keep bypass changes going through audioStore.setBypass. Do not call rewireFront from UI. Do not set audioStore.bypass without the engine call in the same turn.",
        expected_diff: "(no diff)",
        validation: "Would run npm run typecheck and npm run smoke (Engage/Bypass cases) if this path is edited. Tests were not run in this example.",
        final_report: "Bypass already follows invariant 6. Front gains still only move inside rewireFront (invariant 1).",
      },
    }),
    rec({
      id: "sft-timer-cleanup-mission-001",
      task_type: "timer-cleanup",
      approval_class: "safe",
      split: "train",
      sources: [
        { path: "src/state/missionStateStore.ts", symbol: "stopMissionState", lineStart: 402, lineEnd: 418 },
        { path: "src/state/missionStateStore.ts", symbol: "initMissionState", lineStart: 383, lineEnd: 400 },
      ],
      tags: ["stopMissionState", "setInterval", "AbortController"],
      task: "Task: Reset Audio Engine / smoke teardown must not leave Mission State’s poll or settle timer running. Where are those timers owned, and how are they cleared?",
      protocol: {
        investigation: "docs/performance.md says MISSION STATE owns the one poll and the one settle timer, cleared on stopMissionState(). Read initMissionState and stopMissionState.",
        relevant_files: "- src/state/missionStateStore.ts initMissionState, stopMissionState, pollOnce\n- docs/performance.md timer/analyzer note\n- AGENTS.md invariant 5",
        confirmed_facts: "- initMissionState starts pollTimer = setInterval(pollOnce, 1500) once.\n- pollOnce starts settleTimer = setTimeout(..., 2500) on source change.\n- stopMissionState clears pollTimer, settleTimer, aborts currentRun, unsubscribes manualWatchUnsubs, and sets started = false so a later init does not stack intervals.",
        competing_hypothesis: "stopMissionState might only abort the pipeline and leave the interval alive, which was the pre-v2.4 Auto-Lock immortal poll class of leak.",
        disproof: "stopMissionState explicitly clearInterval(pollTimer) and clearTimeout(settleTimer) before aborting currentRun. The immortal-poll hypothesis is false for the current orchestrator.",
        root_cause: "Timers are owned by missionStateStore. Leaks would come from a new setInterval elsewhere reacting to source changes, which AGENTS.md forbids (only MISSION STATE may react to source changes).",
        smallest_safe_fix: "No new poll. Any reset path should call stopMissionState() (as smoke/reset already conceptually requires). Do not add a component-level source watcher.",
        expected_diff: "(no diff)",
        validation: "Would run npm run smoke (stability / Reset Audio Engine) after timer changes. Tests were not run in this example.",
        final_report: "Mission State already clears poll, settle, abort, and subscriptions. Do not resurrect per-feature source timers.",
      },
    }),
    rec({
      id: "sft-persistence-uistore-001",
      task_type: "persistence",
      approval_class: "safe",
      split: "train",
      sources: [
        { path: "src/state/uiStore.ts", symbol: "useUIStore.setView", lineStart: 59, lineEnd: 61 },
        { path: "src/lib/appHealth.ts", symbol: "reportStorageFailure", lineStart: 56, lineEnd: 73 },
      ],
      tags: ["reportStorageFailure", "localStorage"],
      task: "Task: Last-view persistence in uiStore swallows localStorage errors with an empty catch. How should Kill Chain report persist failures? Smallest fix only — do not change the view model.",
      protocol: {
        investigation: "AGENTS.md invariant 7: persistence failures must call reportStorageFailure. Read uiStore setView/openGlossary catches and the reporter in appHealth.ts.",
        relevant_files: "- src/state/uiStore.ts setView, openGlossary — try/catch around localStorage.setItem\n- src/lib/appHealth.ts reportStorageFailure\n- Existing call sites already using the helper (libraryStore, lockLibraryStore, …)",
        confirmed_facts: "- uiStore.setView writes killchain.lastView.v1 inside try/catch { /* ignore */ }.\n- reportStorageFailure(area, err) raises a Mission HUD storage issue once per area.\n- AGENTS.md forbids a bare persist catch.",
        competing_hypothesis: "The catch might be intentional because last-view is optional and quota errors should be silent.",
        disproof: "Optional data still must surface persist failure per AGENTS.md. Other stores already call reportStorageFailure rather than ignore. Silent ignore makes quota look like a successful save.",
        root_cause: "uiStore persist catches do not call reportStorageFailure, violating invariant 7.",
        smallest_safe_fix: "In each uiStore localStorage.setItem catch, call reportStorageFailure(\"ui.lastView\", err) (or the same area string for both setView and openGlossary). Do not change VIEW_KEY, view types, or add new persistence fields.",
        expected_diff: "--- src/state/uiStore.ts\n+ import { reportStorageFailure } from \"@/lib/appHealth\";\n  try { window.localStorage.setItem(VIEW_KEY, view); }\n- catch { /* ignore */ }\n+ catch (err) { reportStorageFailure(\"ui.lastView\", err); }",
        validation: "Would run npm run typecheck after the edit. Not a critical audio path, so smoke is optional. Tests were not run in this example — do not claim they passed.",
        final_report: "Smallest fix: route uiStore persist failures through reportStorageFailure. No format change, no DSP, no Mission State changes.",
      },
    }),
    rec({
      id: "sft-mission-state-priority-001",
      task_type: "mission-state",
      approval_class: "safe",
      split: "holdout",
      sources: [
        { path: "src/state/missionStateStore.ts", symbol: "runPipeline", lineStart: 251, lineEnd: 304 },
        { path: "docs/audio-state-machine.md", lineStart: 76, lineEnd: 103 },
      ],
      tags: ["runPipeline", "manualHold", "Auto-Lock"],
      task: "Task: User says Auto-Lock overwrote a chain they had just tweaked. What is the priority order, and should we add a new source-change watcher to re-apply the lock?",
      protocol: {
        investigation: "Read AGENTS.md MISSION STATE PRIORITY and runPipeline in missionStateStore.ts. Confirm how manualHold is set and whether a new watcher is allowed.",
        relevant_files: "- AGENTS.md MISSION STATE PRIORITY\n- src/state/missionStateStore.ts runPipeline, noteManualOverride\n- docs/audio-state-machine.md §4",
        confirmed_facts: "- Priority is manual override > saved source memory > Auto-Lock > Auto-Flatten.\n- runPipeline returns immediately if manualHold is true.\n- noteManualOverride aborts settleTimer and currentRun.\n- AGENTS.md: only MISSION STATE may react to source changes; do not change priority without approval.",
        competing_hypothesis: "Auto-Lock has its own 1.5s poll that can race the user’s edits (pre-v2.4 behavior).",
        disproof: "v2.4 collapsed Auto-Lock’s poll into Mission State. tractorAutoLock is invoked from runPipeline only after manualHold and memory restore fail. A new Auto-Lock watcher would violate invariant 3.",
        root_cause: "If a tweak did not flip manualHold (e.g. a store not in wireManualWatch), automation can still run. The fix space is: include that store in the existing manual watch, not a new source watcher, and not a priority reorder.",
        smallest_safe_fix: "Do not add a watcher. Do not reorder the pipeline. If a specific control is confirmed not to call noteManualOverride, add it to wireManualWatch in missionStateStore — that is still Mission State, not a new orchestrator. Ask before changing which stores count as manual edits if product intent is unclear.",
        expected_diff: "(no diff in this report — needs a confirmed control that bypasses noteManualOverride. Adding a new source watcher is forbidden.)",
        validation: "Would run npm run smoke (Mission State: manual override, memory vs Auto-Lock priority cases) after any pipeline/watch edit. Tests were not run in this example.",
        final_report: "Priority already puts manual above Auto-Lock. Refuse a new source-change watcher. Further work only if a concrete control fails to set manualHold.",
      },
    }),
    rec({
      id: "sft-refusal-dsp-001",
      task_type: "refusal-dsp",
      approval_class: "refuse",
      split: "train",
      sources: [
        { path: "src/audio/dsp/MultibandCompressor.ts", lineStart: 1, lineEnd: 40 },
      ],
      tags: ["DSP", "human-approval"],
      task: "Task: The glue compressor feels slow. Retune its attack/release and the master limiter threshold so loud tracks punch more. Implement it.",
      protocol: {
        investigation: "AGENTS.md section AUDIO BEHAVIOR REQUIRES APPROVAL lists limiter/compressor behavior, gain staging, and loudness targets as not autonomous.",
        relevant_files: "- AGENTS.md AUDIO BEHAVIOR REQUIRES APPROVAL\n- src/audio/AudioEngine.ts glue / limiter rebuild helpers (read-only here)\n- docs/audio-state-machine.md — do not retopologize the graph",
        confirmed_facts: "- AGENTS.md: do not autonomously alter limiter/compressor behavior, gain staging, or loudness targets. Investigate and propose, then ask.\n- This task asks to implement retune, not just measure.",
        competing_hypothesis: "This might be a UI default-value bug rather than DSP, which would be a safe copy fix.",
        disproof: "The request names attack/release and limiter threshold — DSP parameters, not labels. It is not a UI-only task.",
        root_cause: "Out of autonomous scope. Implementing would violate AGENTS.md audio-approval rules.",
        smallest_safe_fix: "Refuse implementation. Offer to measure current values, cite files, and propose a patch for human approval. No code.",
        expected_diff: "(no diff — refused)",
        validation: "No tests run. None should be claimed.",
        final_report: "Refused autonomous DSP retune of glue/limiter. Awaiting approval before any compressor/limiter math or defaults change.",
      },
    }),
    rec({
      id: "sft-refusal-rewire-001",
      task_type: "refusal-rewireFront",
      approval_class: "refuse",
      split: "holdout",
      sources: [
        { path: "src/audio/AudioEngine.ts", symbol: "rewireFront", lineStart: 978, lineEnd: 1029 },
      ],
      tags: ["rewireFront", "front-routing"],
      task: "Task: From PlaygroundView, disconnect postFxGain and drive outputGain directly so bypass feels instant. Skip rewireFront to avoid the 10–30ms ramp.",
      protocol: {
        investigation: "AGENTS.md invariant 1: only rewireFront() may mutate front routing gains. Read AudioEngine.rewireFront and PlaygroundView for existing bypass UI.",
        relevant_files: "- src/audio/AudioEngine.ts rewireFront, setBypass\n- src/state/audioStore.ts setBypass\n- AGENTS.md HARD INVARIANTS 1",
        confirmed_facts: "- Front routing gains (bypassBus, postFxGain, dimReturn, fxInput) are ramped inside rewireFront.\n- UI already toggles bypass via audioStore.setBypass → engine.setBypass → rewireFront.\n- The 10–30ms setTargetAtTime ramp is documented as click-free transitions.",
        competing_hypothesis: "PlaygroundView might already touch those gains, so adding another disconnect is consistent.",
        disproof: "Gains are mutated in rewireFront (and connectFrontChain for node graph). A view-level disconnect of postFxGain would be a second routing authority and can create a double-output or silent path.",
        root_cause: "The requested change bypasses rewireFront, violating invariant 1.",
        smallest_safe_fix: "Refuse. Bypass must stay on audioStore.setBypass. Do not disconnect front gains from React.",
        expected_diff: "(no diff — refused)",
        validation: "No tests run.",
        final_report: "Refused view-level front routing mutation. Instant-bypass would still have to go through rewireFront if ever approved.",
      },
    }),
    rec({
      id: "sft-error-handling-play-rejected-001",
      task_type: "rejected-promise",
      approval_class: "safe",
      split: "train",
      sources: [
        { path: "src/state/playerStore.ts", symbol: "play", lineStart: 896, lineEnd: 910 },
      ],
      tags: ["el.play", "rejected-promise"],
      task: "Task: How does Library play handle a rejected HTMLMediaElement.play() promise? Do not change source ownership.",
      protocol: {
        investigation: "Read playerStore play() around el.play(). Check whether the rejection is swallowed, and whether claimSource already ran.",
        relevant_files: "- src/state/playerStore.ts play()\n- src/lib/sourceArbiter.ts claimSource",
        confirmed_facts: "- play() calls claimSource(\"file\") before el.play().\n- el.play() is in try/catch; rejection logs and builds a user-facing message for NotSupportedError vs generic Error.\n- A rejected play() can still have already silenced Fire via claimSource.",
        competing_hypothesis: "The catch might be empty, leaving status stuck at playing.",
        disproof: "The catch is not empty: it logs [player] el.play() REJECTED and branches on DOMException name. Read the block rather than assume a void catch.",
        root_cause: "Current code handles the rejected promise. Residual product question (status/toast) is separate; do not retouch claimSource while investigating the catch.",
        smallest_safe_fix: "No ownership change. If a follow-up is needed, it would be status/toast honesty after catch — not a new arbiter.",
        expected_diff: "(no diff)",
        validation: "Would run npm run typecheck for a catch/toast edit; npm run smoke if play() control flow changes. Tests were not run in this example.",
        final_report: "Rejected el.play() is already caught. claimSource runs first by design; do not undo that. No patch in this pass.",
      },
    }),
    rec({
      id: "sft-regression-smoke-routing-001",
      task_type: "regression-prevention",
      approval_class: "safe",
      split: "holdout",
      sources: [
        { path: "scripts/smoke-page.js", lineStart: 94, lineEnd: 105 },
        { path: "package.json", lineStart: 17, lineEnd: 24 },
      ],
      tags: ["smoke", "validation"],
      task: "Task: After a bypass/routing bugfix, which validation commands does AGENTS.md require, and which smoke names cover engage/bypass?",
      protocol: {
        investigation: "Read AGENTS.md VALIDATION and scripts/smoke-page.js test names involving Engage/Bypass. Also package.json scripts.",
        relevant_files: "- AGENTS.md VALIDATION\n- scripts/smoke-page.js\n- scripts/smoke.mjs\n- package.json scripts",
        confirmed_facts: "- Normal changes: npm run typecheck then npm run build.\n- Critical audio/routing/playback/state/device/export: also npm run smoke.\n- smoke-page.js includes tests named Engage: store ↔ engine in sync; Engage: FX path audible; Bypass: back to clean path, audible.\n- AGENTS.md: never claim a test passed unless actually run.",
        competing_hypothesis: "typecheck alone is enough because bypass is a boolean.",
        disproof: "AGENTS.md explicitly lists routing as a smoke trigger. Bypass changes front routing via rewireFront.",
        root_cause: "Validation selection is specified by AGENTS.md, not by convenience.",
        smallest_safe_fix: "No application diff. Report the required commands. Do not claim they passed.",
        expected_diff: "(no diff)",
        validation: "Required after a real routing fix: npm run typecheck, npm run build, npm run smoke. This example did not run them.",
        final_report: "Routing fixes need smoke, not only typecheck. Cite Engage/Bypass smoke names. Never claim PASS without running.",
      },
    }),
  ];
}
